👀 Added a solution for the first homework
siriusdevs/homeworks_23 pull request #10
Opened 2023-09-30 22:56 UTC by tofickbrodaga

Added a solution, but I'm not sure if it's correct 🤹🏼‍♀️
There was supposed to be a pasta from dvach here, but unfortunately there's only sad pepe here now ☠️
![sad pepe](https://2ch.hk/b/arch/2016-07-25/src/132599364/14694686532000.jpg)

2023-09-30 23:10 UTC, tofickbrodaga commented
I forgot about the design of the tests.....Ugh

2023-09-30 23:16 UTC, tofickbrodaga commented
If there's anything else I forgot, please remind me.

2023-10-01 09:01 UTC, nazaroviktor2 commented on hw1.py
> +from typing import List, Tuple, Optional
С версии python 3.9 List, Tuple можно не импортировать из typing. https://peps.python.org/pep-0585/
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/f5c58153-15f3-425b-93c6-da533f3ac5b2)

2023-10-01 09:13 UTC, tofickbrodaga commented on hw1.py
> +from typing import List, Tuple, Optional
Fixed

2023-10-01 09:34 UTC, nazaroviktor2 commented on test_hw1.py
> +
Выглядит очень страшно и больно...

```
data_some = (  # после каждой новой открывающий скобки, которая не закрываются на той же линии, пишем с табуляции
    (  # не закрыта на этой линии значит следующая с таба
        ([], None), ([], 0),  # здесь все скобки открываются и закрываются на одной линии
    ),  # закрывающая скобка должна находится на той же табуляции
    (  # следующая открывающая после закрытой на там же уровне, так это новый элемент того же списка
        (
            [('Teachers', [5000.00, 5500.50, 6000.75])],
            None,  # на том же уровне
        ),
        (
            [
                6000.75,  # каждый элемент одного списка на одном уровне
                5500.5,
                5000.0,  # после последнего элемента лучше оставлять запятую, чтобы потом проще добавить новый элемент
            ],
            100.0,
        ),
    ),
    (
        (
            [
                ('Church', [5000.00, 5500.50, 6000.75]),
                ('Deanery', [7000.25, 7200.30, 7500.50]),
                ('IT', [6000.00, 6200.00, 6500.00]),
            ],
            None,
        ),
        (
            [7500.5, 7200.3, 7000.25],
            38.14,
        ),
    ),
)  # находится на той же начальной табуляции как и первая открытая скобка

```

2023-10-01 09:39 UTC, nazaroviktor2 commented on hw1.py
> +def top_salary(*args: Tuple[str, List[float]],
Тебе же приходит коттедж из отделов одной компании ? Тогда лучше назвать переменную company,  она будет более точно отражать то, что находится в переменной

2023-10-01 09:46 UTC, nazaroviktor2 commented on hw1.py
> +
Ты используешь переменную department_salaries - для того чтобы сохранить все заплаты по отделам, потом найти сумму их всех и топ. А нужен ли тут словарь отделов? Или можно сразу сохранять все зп в один массив? Здесь же можно и считать их сумму. 
Сейчас у тебя высокая сложность, для сохранения идешь по всем отделам, чтобы сохранить нужные, потом еще раз идешь по всем нужным отделам(а это могут быть опять все отделы), но уже чтобы получить их зп, а потом еще раз идешь по зп, чтобы получить сумму

2023-10-01 09:50 UTC, nazaroviktor2 requested changes
Очень хорошо, но надо поправить некоторые места

2023-10-01 09:55 UTC, tofickbrodaga commented on test_hw1.py
> +
It's autopep8, our teacher recommended us to use it.

I was scared myself. 🫣

2023-10-01 10:10 UTC, siriusdevs commented on test_hw1.py
> +
autopep8 was recommended only for primary formatting: to add spaces, empty lines, etc.

unfortunately, autopep is not capable of formatting the code by PEP-8

2023-10-01 10:51 UTC, tofickbrodaga commented on test_hw1.py
> +
Fixed

2023-10-01 10:52 UTC, tofickbrodaga commented on hw1.py
> +def top_salary(*args: Tuple[str, List[float]],
Fixed

2023-10-01 10:52 UTC, tofickbrodaga commented on hw1.py
> +
Fixed maybe

2023-10-01 11:45 UTC, nazaroviktor2 submitted a review, later dismissed
Молодец 👍

2023-10-01 19:12 UTC, tofickbrodaga commented
Add a halfway tag 🥲
![image](https://github.com/siriusdevs/homeworks_23/assets/101170461/90a9d259-175b-4d9e-b580-88eabf6f58a3)

2023-10-01 19:14 UTC, tofickbrodaga commented
Just wanted to post about the tag...thanks!![image](https://github.com/siriusdevs/homeworks_23/assets/101170461/3fcd7bbd-81b2-4a3f-aad2-2bea3f532563)

2023-10-01 19:25 UTC, kirillsev1 approved these changes
welcome

2023-10-04 09:02 UTC, siriusdevs commented
ZeroDivisionError when all salaries in company are zeros.

@nazaroviktor2 @kirillsev1 be more careful bext time

@tofickbrodaga fix it

2023-10-04 09:08 UTC, siriusdevs commented
Also:
![image](https://github.com/siriusdevs/homeworks_23/assets/102812997/21c6cb73-7252-4452-84a5-e5b997e1edf4)

@nazaroviktor2 @kirillsev1 ???

2023-10-04 11:07 UTC, tofickbrodaga commented
![photo_2023-10-04 14 05 34](https://github.com/siriusdevs/homeworks_23/assets/101170461/5ac03733-a528-4861-b370-53544c9deae5)
@siriusdevs 
"The hedgehogs cried and cried, but kept eating the cactus." - I don't understand how to fix these, they don't go away😭

2023-10-05 20:20 UTC, siriusdevs commented
> ![photo_2023-10-04 14 05 34](https://user-images.githubusercontent.com/101170461/272553755-5ac03733-a528-4861-b370-53544c9deae5.jpeg) @siriusdevs "The hedgehogs cried and cried, but kept eating the cactus." - I don't understand how to fix these, they don't go away😭

Aren't they self-explanatory?
It is literally written in your flake8 output what went wrong.

2023-10-05 21:16 UTC, tofickbrodaga commented
> > ![photo_2023-10-04 14 05 34](https://user-images.githubusercontent.com/101170461/272553755-5ac03733-a528-4861-b370-53544c9deae5.jpeg) @siriusdevs "The hedgehogs cried and cried, but kept eating the cactus." - I don't understand how to fix these, they don't go away😭
> 
> 
> 
> Aren't they self-explanatory?
> 
> It is literally written in your flake8 output what went wrong.

About multi-line parameters it is not very clear, autopep8 is even shocked

It gets worse when using automatic "stuff". Can I put multi-line parameters in ignore?

2023-10-05 21:18 UTC, tofickbrodaga commented
And if the first line ends with a dot flake8 still swears....
What did I do?

2023-10-06 10:15 UTC, tofickbrodaga commented
I realized it's useless. Until a better time.

2023-10-07 20:25 UTC, tofickbrodaga commented
I need a help. 
I am really annoyed that I can't hand in my homework because of two errors in linter.
1. WPS221 Found line with high Jones Complexity: 20 > 14 - After moving the line like we did in the seminars - for me it turns into: WPS318 Found extra indentation & WPS319 Found bracket in wrong position and is NOT corrected. Not by myself, not automatically, not with God's help. 
2. WPS317 Found incorrect multi-line parameters - I have searched all over the internet and have not found any answers on how to fix this.
Maybe I'm stupid or don't understand something? I'm not getting anything fixed. NOTHING.

2023-10-08 10:12 UTC, nazaroviktor2 commented
> I need a help. I am really annoyed that I can't hand in my homework because of two errors in linter.
> 
> 1. WPS221 Found line with high Jones Complexity: 20 > 14 - After moving the line like we did in the seminars - for me it turns into: WPS318 Found extra indentation & WPS319 Found bracket in wrong position and is NOT corrected. Not by myself, not automatically, not with God's help.
> 2. WPS317 Found incorrect multi-line parameters - I have searched all over the internet and have not found any answers on how to fix this.
>    Maybe I'm stupid or don't understand something? I'm not getting anything fixed. NOTHING.

```
def top_salary(
    *company: tuple[str, list[float]],
    name_departments: list[str] = None,
) -> tuple[list[float], float]:
    """Find top 3 salaries in the company, the ratio of the amount of this top to the total amount of \
    payments in the company in percentages.

    Args:
        company: Tuple[str, List[float]] - company departments and their salaries.
        name_departments: List[str] - the name departaments. Usually Optional[List[str]] = None.

    Returns:
        tuple[list[float], float] - top 3 salaries and the ratio  of the amount
        of this top to the total amount of payments.
    """
```

2023-10-08 10:14 UTC, nazaroviktor2 commented on hw1.py
> +'''Salary stats and percent's'''
"""Salary stats and percent's."""

Двойные кавычки и точка в конце

2023-10-08 10:20 UTC, nazaroviktor2 commented on hw1.py
> +    """
Тут проблема со скобками.  Вот [тут](https://github.com/siriusdevs/homeworks_23/pull/10#discussion_r1342107248) я писал как правильно ставить скобки

2023-10-08 10:24 UTC, nazaroviktor2 commented on hw1.py
> +        *company: Tuple[str, List[float]] - company departments and their salaries.
в докстрингах * * используют для выделения курсивом, не надо использовать для переменных, потому что переменная company, а не *company. Звездочка означает распаковку, а не названия переменной  

Тут я выделил *in the company*

![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/75d203f9-6b9f-49ed-8dc3-d2eb8b2d95f3)

2023-10-08 10:25 UTC, nazaroviktor2 commented on hw1.py
> +               name_departments: [list[str]] = None) -> tuple[list[float], float]:
Зачем ты обернула в скобочки list? Просто `name_departments: list[str] = None`

2023-10-08 10:33 UTC, nazaroviktor2 commented on hw1.py
> +        if name_departments is None or department_name in name_departments:
На будущие.  так как это у тебя name_departments это список то `if department_name in name_departments:` каждый раз будет выполнятся за O(n).  Но если бы name_departments - set то это проверка занимала бы O(1) - разница очень большая. Поэтому ты можешь в перед циклом сделать set(name_departments), что очень сильно ускорит твою программу

2023-10-08 10:34 UTC, nazaroviktor2 commented on hw1.py
> +    if not all_salaries or sum(all_salaries) == 0:
Избыточная проверка, можно просто оставить  sum(all_salaries)

2023-10-08 10:35 UTC, nazaroviktor2 commented on hw1.py
> +    return top_salaries, percentage
ты не округляешь top_salaries

2023-10-08 10:37 UTC, nazaroviktor2 requested changes
Надо поправить некоторый замечания

2023-10-08 12:24 UTC, tofickbrodaga commented on hw1.py
> +    return top_salaries, percentage
The task says nothing about rounding top_salaries. No operations other than sorting are performed. Yes, I understand the fact that the user will be able to enter something like 884935.0000001, but we are in the realities of life - did anyone get such a salary?

2023-10-08 12:32 UTC, nazaroviktor2 commented on hw1.py
> +    return top_salaries, percentage
> The task says nothing about rounding top_salaries. No operations other than sorting are performed. Yes, I understand the fact that the user will be able to enter something like 884935.0000001, but we are in the realities of life - did anyone get such a salary?

Как это ничего не сказано ??? _" Все числа в выводе функции округлять до второго знака после запятой"_ - все числа - значить все числа

2023-10-08 13:43 UTC, tofickbrodaga commented
I did it.

2023-10-08 15:00 UTC, nazaroviktor2 commented on hw1.py
> +            all_salaries.extend([round(salary, 2) for salary in salaries])
можно просто `all_salaries += [round(salary, 2) for salary in salaries]`

2023-10-08 15:02 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/8b8fd461-9f80-44d5-989f-03c307439b7d)

2023-10-08 20:55 UTC, kirillsev1 approved these changes

2023-10-09 09:09 UTC, merged