Krivenko_hw1
siriusdevs/homeworks_23 pull request #100
Opened 2023-12-20 18:00 UTC by BBEDITE-IMUA

i don't use chatGPT and copilot

2023-12-20 19:31 UTC, nazaroviktor2 requested changes
Молодец, надо не много поправить

2023-12-20 19:31 UTC, nazaroviktor2 commented on hw1.py
> +def salary_stats(*departments, limit=None):
Аннотации?

2023-12-20 19:31 UTC, nazaroviktor2 commented on hw1.py
> +            salaries = [salary for salary in salaries if salary >= limit]
Ошибка, когда limit = None

2023-12-20 21:18 UTC, BBEDITE-IMUA commented on hw1.py
> +            salaries = [salary for salary in salaries if salary >= limit]
Если limit не будет дан то мой список заполнится минуя if, а если limit мы задодим то тогда мы будем проходить по if и заполнять с исключением меньших. Нужно ли делать if limit is none?

2023-12-20 21:20 UTC, BBEDITE-IMUA commented on hw1.py
> +            salaries = [salary for salary in salaries if salary >= limit]
Или я не правильно понял?

2023-12-21 09:18 UTC, BBEDITE-IMUA commented on hw1.py
> +            salaries = [salary for salary in salaries if salary >= limit]
@nazaroviktor2

2023-12-21 17:37 UTC, nazaroviktor2 commented on hw1.py
> +            salaries = [salary for salary in salaries if salary >= limit]
Я не увидел if

2023-12-21 17:40 UTC, nazaroviktor2 requested changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/7620d3c8-741a-4c69-8e9b-5e6fc4472e8c)

2023-12-21 17:40 UTC, nazaroviktor2 commented on .github/workflows/pylint.yml
> +      run: flake8 ${{ matrix.homework }}
Ты уверен что это работает? Верни лучше на .

2023-12-21 17:41 UTC, BBEDITE-IMUA commented
@nazaroviktor2, также сделал hw2, нужно ли делать второй pull request или в этом сможете проверить?

2023-12-21 17:48 UTC, nazaroviktor2 commented
> @nazaroviktor2, также сделал hw2, нужно ли делать второй pull request или в этом сможете проверить?

Лучше в отдельном

2023-12-21 17:50 UTC, BBEDITE-IMUA commented on .github/workflows/pylint.yml
> +      run: flake8 ${{ matrix.homework }}
Окей. А всё остальное в hw1 и hw2 нормально?

2023-12-21 18:29 UTC, BBEDITE-IMUA commented
@nazaroviktor2 Всё исправил теперь финальный вариант hw1 и hw2

2023-12-21 20:27 UTC, nazaroviktor2 requested changes
При вызове основной функции пользователь не должен видеть traceback ошибок. Сообщение об ошибки или запись этого сообщения в файл - ок

2023-12-21 20:27 UTC, nazaroviktor2 commented on HW2/hw2.py
> +    output_data = get_stat(dataa)
Если файл не найден ?

2023-12-21 20:27 UTC, nazaroviktor2 commented on HW2/hw2.py
> +        json.dump(output_data, output_filee)
Если конечный путь не найден? см makedirs

2023-12-21 20:27 UTC, nazaroviktor2 commented on HW2/test_hw2.py
> +    with open('test_input.json', 'w') as input_file:
Тестовые данные должны быть в файлах

2023-12-21 20:27 UTC, nazaroviktor2 commented on HW2/hw2.py
> +        city_distrib[user['region']] += 1
Если ключ не найден?

2023-12-21 20:27 UTC, nazaroviktor2 commented on HW2/hw2.py
> +        year_distrib[datetime.strptime(user['registered'], '%Y-%m-%d').year] += 1
Если ключ не найден? Если он в неверное формате?

2023-12-21 21:57 UTC, BBEDITE-IMUA commented
@nazaroviktor2 Исправил!

2023-12-21 22:08 UTC, nazaroviktor2 requested changes

2023-12-21 22:08 UTC, nazaroviktor2 commented on HW2/hw2.py
> +        year_of_regisrt = datetime.strptime(dataa[user]['registered'], '%Y-%m-%d').year
Если ключи не найдены? Эта ошибка не обрабатывается в основной функции

2023-12-21 22:08 UTC, nazaroviktor2 commented on HW2/test_hw2.py
> +    os.remove('./data_test_output.json')
Тоже в файле должно быть. Файл не удаляй

2023-12-21 22:39 UTC, BBEDITE-IMUA commented on HW2/test_hw2.py
> +    os.remove('./data_test_output.json')
Так вроде тесты должны подчищать за собой файлы. Разве нет? Его нужно удалять в двух тестах или нет?

2023-12-21 22:43 UTC, BBEDITE-IMUA commented
@nazaroviktor2 Исправил

2023-12-22 10:05 UTC, BBEDITE-IMUA commented on HW2/hw2.py
> +        year_of_regisrt = datetime.strptime(dataa[user]['registered'], '%Y-%m-%d').year
@nazaroviktor2 исправил

2023-12-22 12:01 UTC, BBEDITE-IMUA commented
@nazaroviktor2 Всё теперь точно финально исправил

2023-12-22 14:52 UTC, merged