Inozemtsev HW3
siriusdevs/homeworks_23 pull request #103
Opened 2023-12-20 21:47 UTC by bliinmaker

2023-12-21 12:26 UTC, bliinmaker commented
config согласовал с @siriusdevs

2023-12-21 18:02 UTC, kirillsev1 requested changes

2023-12-21 18:02 UTC, kirillsev1 commented on hw3/test_hw3.py
> +    assert motorcar.model == 'BMW M5'
Эти тесты можно объединить в один, тем более отличаются они только годом

2023-12-21 18:02 UTC, kirillsev1 commented on hw3/test_hw3.py
> +    assert motorcar.model == 'BMW M5'
С остальными тестами тоже самое. Там, где тесты почти совпадают, можно в один объединить

2023-12-21 18:03 UTC, nazaroviktor2 submitted a review, later dismissed
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/b9bdef46-c7b7-4e82-8e90-5fba53e23543)

2023-12-21 18:03 UTC, nazaroviktor2 commented on hw3/hw3.py
> +            raise InvalidTypeError(new_year, 'str')
тут наверное опечатка и надо int

2023-12-21 18:03 UTC, nazaroviktor2 commented on hw3/hw3.py
> +            raise InvalidTypeError(new_price, 'str')
тоже самое

2023-12-21 18:03 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        if not isinstance(new_payload, int):
Грузоподьемность не может быть float?

2023-12-21 18:03 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        return [str(car) for car in self._cars]
Зачем к str?

2023-12-21 18:04 UTC, kirillsev1 commented on hw3/hw3.py
> +        self._cars = new_cars
По заданию, тут не надо делать геттер/сеттер(`Получить список всех автомобилей в автопарке`), если бы не это, поставил бы апрув

2023-12-21 18:12 UTC, kirillsev1 approved these changes

2023-12-21 18:44 UTC, bliinmaker commented on hw3/hw3.py
> +        return [str(car) for car in self._cars]
чтобы вызывать строковой метод у Car

2023-12-21 18:45 UTC, bliinmaker commented on hw3/hw3.py
> +        if not isinstance(new_payload, int):
может, исправил

2023-12-21 20:11 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        return [str(car) for car in self._cars]
Я знаю, что такое str) Просто зачем вы возвращаем строки вместо объектов?  Приходит запрос:
- посчитать грузоподьемность всех машин в автопарке
Как это сделать в текущей реализации?) Мы же возвращаем только строку, доступа к другим атрибутам объектам нет

2023-12-22 12:44 UTC, siriusdevs approved these changes

2023-12-22 12:44 UTC, merged