Pazych hw2
siriusdevs/homeworks_23 pull request #109
Opened 2023-12-21 12:17 UTC by VikaPaz

2023-12-21 19:00 UTC, kirillsev1 commented
Дубликат #66

2023-12-21 22:10 UTC, VikaPaz commented
последние коммиты различаются

2023-12-24 15:31 UTC, kirillsev1 requested changes

2023-12-24 15:31 UTC, kirillsev1 commented on hw2.py
> +        online_duration[onlene_item[0]] = onlene_item[1] / total_clients * 100
ZeroDivisionError

2023-12-24 15:31 UTC, kirillsev1 commented on test_hw2.py
> +    },
Добавь тесткейсы, которые предположительно могут сломать программу, для проверки валидаторов

2023-12-25 21:02 UTC, nazaroviktor2 commented
У тебя конфликты

2024-04-16 16:10 UTC, closed without merging