Inozemtsev
siriusdevs/homeworks_23 pull request #11
Opened 2023-10-01 07:09 UTC by bliinmaker

first homework done

2023-10-01 10:07 UTC, nazaroviktor2 commented on setup.cfg
> +                WPS226
Setup нельзя менять

2023-10-01 10:14 UTC, nazaroviktor2 commented on hw1.py
> +
Сумму зарплат тоже можно тут считать, но в принципе норм

2023-10-01 10:23 UTC, nazaroviktor2 commented on hw1.py
> +def work_statistics(company_part: dict, ex_company_part: tuple = ()) -> tuple:
ex_company_part: tuple = () - вот так лучше не делать
 
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/f666ff81-9e3b-427e-a582-06b23f23fa0c)

В твоей случае это не принес не какого вреда, но дальше лучше пиши вот так
```
def magic_in_python(element, magic_list: list = None):
    if magic_list is None:
        magic_list = []
    magic_list.append(element)
    return magic_list
```

2023-10-01 10:25 UTC, nazaroviktor2 requested changes
Изменение setup.cfg - карается законом

2023-10-01 11:33 UTC, nazaroviktor2 commented on hw1.py
> +        ex_company_part (tuple): used to exclude certain departments, defaults to ().
Тут забыл поменять, что default None

2023-10-01 11:38 UTC, nazaroviktor2 commented on hw1.py
> +    return (lowest_top, percent_of_lowest)
При возврате кортежа не надо оборачивать в () 
https://www.geeksforgeeks.org/g-fact-41-multiple-return-values-in-python/

2023-10-01 11:40 UTC, nazaroviktor2 submitted a review, later dismissed
Молодец, поменять докстринги и return, и все ок

2023-10-01 21:39 UTC, annashutova requested changes

2023-10-02 11:10 UTC, nazaroviktor2 submitted a review, later dismissed
Молодец

2023-10-02 11:36 UTC, KatyaGotskina requested changes

2023-10-02 11:41 UTC, KatyaGotskina requested changes

2023-10-02 11:41 UTC, KatyaGotskina commented on hw1.py
> +                all_salaries.append(salary)
Не округляешь зарплаты до 2-го знака после запятой, а этого требует условие

2023-10-02 11:45 UTC, KatyaGotskina commented on hw1.py
> +    return lowest_top, percent_of_lowest
Предлагаю такое решение:

sum_salaries = sum(all_salaries)
percent_of_lowest = 0 if sum_salaries == 0 else sum(lowest_top) / sum_salaries * 100
return lowest_top, round(percent_of_lowest, 2)

Сумма всех зарплат не считается два раза, что уже делает программу быстрее

2023-10-02 11:47 UTC, bliinmaker commented on hw1.py
> +                all_salaries.append(salary)
округление есть, просто чуть ниже)

2023-10-02 12:04 UTC, KatyaGotskina commented on hw1.py
> +                all_salaries.append(salary)
Какая строка? По-моему его нет

2023-10-02 12:05 UTC, KatyaGotskina commented on hw1.py
> +                all_salaries.append(salary)
Какая строка? По-моему его нет

2023-10-02 12:07 UTC, bliinmaker commented on hw1.py
> +                all_salaries.append(salary)
25 строка
 percent_of_lowest = round(sum(lowest_top) / sum(all_salaries) * 100, 2)

2023-10-03 12:22 UTC, KatyaGotskina approved these changes
круто :D

2023-10-03 14:17 UTC, annashutova approved these changes
good job)

2023-10-04 07:14 UTC, merged