Zayceff_hw2
siriusdevs/homeworks_23 pull request #112
Opened 2023-12-21 12:38 UTC by anonim767bn

2023-12-21 18:54 UTC, kirillsev1 requested changes

2023-12-21 18:54 UTC, kirillsev1 commented on HW2/hw2.py
> +        4 if output_file is not writable
Не надо так, просто int, если что то кроме 0, то это ошибка, лучше так

2023-12-21 18:54 UTC, kirillsev1 commented on HW2/utilites.py
> +    age60 = 60
Если объявляешь константу, то выноси ее в начало файла, как минимум. И называй их капслоком

2023-12-21 18:54 UTC, kirillsev1 commented on HW2/utilites.py
> +        age group
Плохой докстринг. Нет типов данных и `:`

2023-12-21 18:54 UTC, kirillsev1 commented on HW2/utilites.py
> +        dict with age stats
Плохой докстринг. Нет типов данных и `:`

2023-12-21 18:54 UTC, kirillsev1 commented on HW2/utilites.py
> +        dict with last login stats
Докстринг

2023-12-21 18:54 UTC, kirillsev1 commented on HW2/utilites.py
> +        last login group
Докстринг

2023-12-21 18:54 UTC, kirillsev1 commented on HW2/test_hw2.py
> +    assert process_data('./HW2/input/data_hw2.json', '/nesuchestvuyushaya_papka/1/1/1/1.json') == 3
Используй parametrize

2023-12-21 20:39 UTC, anonim767bn commented
@kirillsev1, исправил

2023-12-21 20:48 UTC, kirillsev1 requested changes

2023-12-21 20:48 UTC, kirillsev1 commented on HW2/hw2.py
> +    return 0
Эти return int выглядят максимально плохо, я подумал, сделай возвращение строк, чтобы было хотя бы понятно что это за ошибка и поставлю

2023-12-21 21:28 UTC, anonim767bn commented on HW2/hw2.py
> +    return 0
@kirillsev1, исправил

2023-12-21 22:11 UTC, kirillsev1 approved these changes

2023-12-22 13:28 UTC, siriusdevs commented
@anonim767bn rebase your commits

2023-12-22 14:01 UTC, closed without merging