Tereshin HW3
siriusdevs/homeworks_23 pull request #117
Opened 2023-12-21 18:08 UTC by ArTeria21

2023-12-21 18:13 UTC, kirillsev1 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/2bec44ed-2423-4e51-b876-2d3a3666d084)
Нет workflows

2023-12-21 18:13 UTC, kirillsev1 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/2bec44ed-2423-4e51-b876-2d3a3666d084)
Нет workflows

2023-12-21 18:20 UTC, kirillsev1 requested changes
Во втором дз не надо рейзить ошибки, достаточно логировать их, в третьей тесты, а так хорошо

2023-12-21 18:20 UTC, kirillsev1 commented on hw2/hw2.py
> +        super().__init__(f'File with path: {path} is not exist')
Во втором дз не надо вызывать ошибки, которые остановят программу, записывай их в файл

2023-12-21 18:20 UTC, kirillsev1 commented on hw2/hw2.py
> +    # current_date = datetime.now()
Нет докстринга

2023-12-21 18:20 UTC, kirillsev1 commented on hw2/hw2.py
> +        age = json_file[user]['age']
Нет докстринга

2023-12-21 18:20 UTC, kirillsev1 commented on hw2/test_hw2.py
> +        os.makedirs(subfolder)
Хоть какие то докстринги надо

2023-12-22 06:08 UTC, ArTeria21 commented on hw2/hw2.py
> +        super().__init__(f'File with path: {path} is not exist')
Кирилл, у меня все ошибки обрабатываются) Если возникает ошибка, она записывается в файл и программа завершается с кодом 0

2023-12-22 07:36 UTC, ArTeria21 commented
Я внес правки. 
Единственное, мне нужно апрувнуть только 3 дз, оно полностью готово, а вот 2 дз не доделано

2023-12-22 08:32 UTC, kirillsev1 commented on hw2/hw2.py
> +        super().__init__(f'File with path: {path} is not exist')
Смотри. У тебя есть 
try:
    check_extension(...)
except ...:
    ...

В check_extension ты рейзишь ошибку, вот что на это говрили Ж
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/036d511a-38f0-4958-8e16-d7e15099d335)

2023-12-22 08:35 UTC, kirillsev1 commented on hw2/hw2.py
> +        super().__init__(f'File with path: {path} is not exist')
Окей, правь докстринги

2023-12-22 08:35 UTC, kirillsev1 commented
Чтобы апрувнуть только 3 дз надо сделать реквест, где будет 3 без второй

2023-12-22 10:57 UTC, closed without merging