Otroshenko hw2
siriusdevs/homeworks_23 pull request #121
Opened 2023-12-21 20:07 UTC by AntohaOt

2023-12-21 20:22 UTC, nazaroviktor2 requested changes

2023-12-21 20:22 UTC, nazaroviktor2 commented on HW2/hw2.py
> +        email_domain = data_dict[client]['email'].split('@')[1]
Если нет ключа email?

2023-12-21 20:22 UTC, nazaroviktor2 commented on HW2/hw2.py
> +        registration_year = data_dict[client]['registered'].split('-')[0]
Если нет ключа?

2023-12-21 20:22 UTC, nazaroviktor2 commented on HW2/hw2.py
> +        return 'Output file not found!'
Это окей. Но мы можем этот путь создавать сами см os.makedirs

2023-12-21 20:22 UTC, nazaroviktor2 commented on HW2/test_hw2.py
> +
Все тестовые данные должны лежать в файлах (и входные и выходные данные)

2023-12-21 21:53 UTC, AntohaOt commented
@nazaroviktor2 Все исправил

2023-12-21 21:57 UTC, nazaroviktor2 requested changes

2023-12-21 21:57 UTC, nazaroviktor2 commented on HW2/hw2.py
> +            raise ValueError('Email key not found')
Эту ошибка основная функция не обрабатывает

2023-12-21 21:57 UTC, nazaroviktor2 commented on HW2/hw2.py
> +            raise ValueError('Registered key not found')
Тоже самое

2023-12-21 22:18 UTC, AntohaOt commented on HW2/hw2.py
> +            raise ValueError('Email key not found')
Не совсем понял вас...

2023-12-21 23:13 UTC, AntohaOt commented
@nazaroviktor2 видимо все таки понял о чем вы. Исправил

2023-12-22 12:11 UTC, AntohaOt commented
@nazaroviktor2 Еще раз исправил, теперь все правильно

2023-12-22 14:12 UTC, siriusdevs commented
Нужно обрабатывать все ошибки и записывать их в файл вывода вместо статистики, а ещё на это нужны тесты

2023-12-22 14:13 UTC, siriusdevs requested changes
Написать больше тестов и в случае ошибок обрабатывать их и отправлять в файл выхода

2023-12-22 21:31 UTC, AntohaOt commented
@nazaroviktor2 @siriusdevs. Доброй ночи. Добавил большее кол-во тестов и обработку ошибок.

2023-12-24 15:29 UTC, AntohaOt commented
@kirillsev1. Добрый вечер, сможете проверить работу?

2023-12-24 16:50 UTC, closed without merging