Tatarnikov
siriusdevs/homeworks_23 pull request #13
Opened 2023-10-01 14:07 UTC by I-AM-LAMER

2023-10-01 15:18 UTC, KatyaGotskina requested changes

2023-10-01 15:18 UTC, KatyaGotskina commented on hw1.py
> +def get_salaries(*agrs: Tuple[str, dict], dep_except: Tuple[str] = None) -> Tuple[list, float]:
Почему agrs? Может args?

2023-10-01 15:18 UTC, KatyaGotskina commented on hw1.py
> +    dep_except = '' if dep_except is None else dep_except
Переменная типа либо str, либо tuple, не хорошо. Пусть она в любом случае является кортежем

2023-10-01 15:18 UTC, KatyaGotskina commented on hw1.py
> +    top_salary = []
Почему переменная называется top_salary, если ты в нее записываешь вообще все зарплаты?

2023-10-01 15:18 UTC, KatyaGotskina commented on hw1.py
> +    in_percentage = (sum(top_3) / all_salaries) * 100
Поскольку ты в top_salary хранишь вообще все зарплаты, смысл переменной all_salaries теряется. 
sum(top_salary) полностью заменяет итоговое all_salaries

2023-10-01 15:18 UTC, KatyaGotskina commented on hw1.py
> +    return [round(i, 2) for i in top_3], round(in_percentage, 2)
Однобуквенные обозначения не приветствуются

2023-10-01 16:00 UTC, I-AM-LAMER commented on hw1.py
> +def get_salaries(*agrs: Tuple[str, dict], dep_except: Tuple[str] = None) -> Tuple[list, float]:
а в чем существенная разница, как я называю переменные? Я поменяю.

2023-10-01 17:25 UTC, KatyaGotskina commented on hw1.py
> +def get_salaries(*agrs: Tuple[str, dict], dep_except: Tuple[str] = None) -> Tuple[list, float]:
args и kwargs — это соглашения по программированию на Python, по-моему мнению, их стоит придерживаться, раз уж используешь этот набор букв :) К тому же, у тебя в докстрингах к функции написано args

2023-10-01 17:37 UTC, siriusdevs commented on hw1.py
> +def get_salaries(*agrs: Tuple[str, dict], dep_except: Tuple[str] = None) -> Tuple[list, float]:
> а в чем существенная разница, как я называю переменные? Я поменяю.

защищать опечатки, когда явно хотел написать другое, и docstring на это указывает - это какой-то новый уровень

2023-10-01 20:30 UTC, Max2288 commented on hw1.py
> +    dep_except = '' if dep_except is None else dep_except
Можно её сразу присваивать например к пустому списку или строке, чтобы небыло if, зачем пустая строка непонятно

2023-10-02 11:15 UTC, nazaroviktor2 commented on hw1.py
> +from typing import Tuple
С версии python 3.9 Tuple можно не импортировать из typing. https://peps.python.org/pep-0585/
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/cf26a32c-f123-4373-a6a2-413ec6ae8192)

2023-10-02 11:18 UTC, nazaroviktor2 commented on test_hw1.py
> +from typing import Tuple
Тут тоже самое

2023-10-02 11:30 UTC, I-AM-LAMER commented on hw1.py
> +def get_salaries(*agrs: Tuple[str, dict], dep_except: Tuple[str] = None) -> Tuple[list, float]:
ок, соре

2023-10-02 11:30 UTC, nazaroviktor2 commented on hw1.py
> +    in_percentage = (sum(top_3) / all_salaries) * 100
> Поскольку ты в top_salary хранишь вообще все зарплаты, смысл переменной all_salaries теряется. sum(top_salary) полностью заменяет итоговое all_salaries

Я считаю, что текущие решение лучше, чем предложила @KatyaGotskina . Здесь нет лишней итерации по всему списку. Когда мы вызываем sum от списка, функция пойдет по всему списку еще раз, чтобы сложить все элементы. А зачем нам идти еще раз по всему списку, когда можно добавить переменную и считать ее при первой итерации? 
Можно считать top 3 тоже при первой итерации, но это уже оптимально. Текущие решение нормально работает

2023-10-02 11:43 UTC, nazaroviktor2 commented on hw1.py
> +def get_salaries(*agrs: Tuple[str, dict], dep_except: Tuple[str] = None) -> Tuple[list, float]:
Что такое agrs? Нужно писать переменные, которые как можно точнее отражают информацию в ней. Что такое args? К тебе же приходит кортеж из отделов одной компании и работников. Почему не назвать переменную company или departments?
dep_except - уже лучше, но всего равное что это?  Сокращение от deposit? Пока Илон не купил питон, буквы все еще бесплатные и max-line-length=99, нужно писать переменные, которые как можно точнее отражают информацию в ней.

2023-10-02 11:47 UTC, nazaroviktor2 commented on hw1.py
> +    for dep in agrs:
Dep? 
`for departments in company :`
Выглядит намного лучше, разве нет?

2023-10-02 11:50 UTC, nazaroviktor2 commented on test_hw1.py
> +     ('3rd', '4th'),
Не самых плохой вариант, который я видел. Но в следующий раз можно написать лучше https://github.com/siriusdevs/homeworks_23/pull/10#discussion_r1342107248
здесь есть пример

2023-10-02 11:51 UTC, nazaroviktor2 requested changes
Надо поработать над названием переменных

2023-10-03 12:30 UTC, annashutova requested changes

2023-10-06 13:10 UTC, KatyaGotskina requested changes

2023-10-06 13:10 UTC, KatyaGotskina commented on hw1.py
> +        company (tuple): salaries in departments.
Напиши подробнее, что содержит в себе кортеж company

2023-10-06 13:10 UTC, KatyaGotskina commented on hw1.py
> +            salaries += list(department[1].values())
Обязателен ли тут list() ?

2023-10-06 13:10 UTC, KatyaGotskina commented on hw1.py
> +    if sum(salaries) == 0:
функция sum() работает за O(n), поскольку складывает все элементы, а затем уже сумма сравнивается с нулем. Я бы написала if not top_three или if not salaries, чтобы не делать лишних итераций

2023-10-06 13:10 UTC, KatyaGotskina commented on hw1.py
> +    if sum(salaries) == 0:
И еще: можно написать все в одной строке
in_percentage = 0 if not top_salaries else (sum(top_three) / sum(salaries)) * 100

2023-10-06 13:14 UTC, KatyaGotskina commented on test_hw1.py
> +        None,
Зачем передавать None?

2023-10-06 13:14 UTC, KatyaGotskina commented on test_hw1.py
> +            ('3', {'5': 100.0, '6': 600.0}),
Было бы круто, если бы у департаментов и сотрудников были хорошие длинные имена. Так легче работать с тестовыми данными

2023-10-06 13:22 UTC, I-AM-LAMER commented on hw1.py
> +    if sum(salaries) == 0:
а можно использовать try блок?

2023-10-06 13:26 UTC, KatyaGotskina commented on hw1.py
> +    if sum(salaries) == 0:
Если хочешь вызывать кастомную ошибку, то можно, но тебе нужно будет сделать для нее собственный класс

2023-10-06 13:27 UTC, I-AM-LAMER commented on test_hw1.py
> +        None,
потому что без none у меня тесты падают в ошибку

2023-10-06 13:27 UTC, I-AM-LAMER commented on test_hw1.py
> +        None,
не знаю как обойти это

2023-10-07 10:59 UTC, nazaroviktor2 commented on setup.cfg
> +        WPS317
setup.cfg нельзя менять без разрешения @siriusdevs

2023-10-07 11:50 UTC, I-AM-LAMER commented on setup.cfg
> +        WPS317
@siriusdevs разрешил добавить ошибку

2023-10-07 11:59 UTC, nazaroviktor2 commented on hw1.py
> +from typing import Tuple
@I-AM-LAMER  Это не исправлено

2023-10-07 12:03 UTC, KatyaGotskina commented
Не могу дать свой аппрув поскольку:
1) просила написать аннотацию к company по типу tuple[str, dict[str, float]]
2) просила лучше назвать тестовые данные. В жизни отделы компании не называются 1,2 и 3

2023-10-07 12:07 UTC, nazaroviktor2 commented
Поправил замечание @KatyaGotskina и я тоже апрувну)

2023-10-07 12:13 UTC, KatyaGotskina commented on test_hw1.py
> +        None,
Лучше написать 2 разных теста где ты передаешь ключевой аргумент и где нет. У тебя возникает эта ошибка, поскольку в parametrize мы должны передавать фиксированное количество переменных

2023-10-07 12:15 UTC, KatyaGotskina commented
Не сдавайся на пути к хорошей истории коммитов. Сейчас пока на грани от dreadful commits

2023-10-07 12:19 UTC, I-AM-LAMER commented
надеюсь что все проблемы пофикшены

2023-10-07 16:55 UTC, KatyaGotskina commented
У тебя остался открытым вопрос с тестами, а еще ты не написал в объявлении функции аннотацию к company

2023-10-07 17:34 UTC, I-AM-LAMER commented
что не так с тестами, и аннотацию я написал, если я правильно понял - tuple[str, dict[str, float]

2023-10-07 17:53 UTC, annashutova commented
про замечание к тестам написано здесь: https://github.com/siriusdevs/homeworks_23/pull/13#discussion_r1349513277
а это `tuple[str, dict[str, float]` нужно добавить в typehint (где указываются параметры функции), а не только в докстринг

2023-10-08 17:54 UTC, I-AM-LAMER commented
я не могу добавить, у меня слишком сложная строка получается

2023-10-08 18:01 UTC, nazaroviktor2 commented
> я не могу добавить, у меня слишком сложная строка получается

Значит  ее нужно разбить
```
def get_salaries(
    *company: tuple[str, dict[str, float]],
    dept_except: Optional[str] = None,
) -> tuple[list, float]:

```

2023-10-11 06:37 UTC, KatyaGotskina commented on test_hw1.py
> +test_data_with_none = (
все константы в коде лучше называть через капс, по типу: TEST_DATA_WITH_NONE

2023-10-11 06:38 UTC, KatyaGotskina commented
Очень приятно видеть такие аннотации к переменным! Осталось лишь написать константы через капс

2023-10-11 06:43 UTC, I-AM-LAMER commented
@annashutova 
@nazaroviktor2

2023-10-11 06:44 UTC, annashutova approved these changes
good job)

2023-10-11 07:26 UTC, siriusdevs approved these changes

2023-10-11 07:28 UTC, merged