Sannikov
siriusdevs/homeworks_23 pull request #131
Opened 2023-12-22 12:19 UTC by Breit1

2023-12-24 09:27 UTC, kirillsev1 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/e4b8c1f4-1d76-48f3-be8c-d89f2d2a8733)
workflows не работает

2023-12-24 09:33 UTC, kirillsev1 requested changes

2023-12-24 09:33 UTC, kirillsev1 commented on test_hw1.py
> +    department2 = ('Отдел2', {'Emma': 5500, 'David': 4800, 'Olivia': 5200})
1) Докстринги
2) используй parametrize

2023-12-24 09:33 UTC, kirillsev1 commented on test_hw1.py
> +    department2 = ('Отдел2', {'Emma': 5500, 'David': 4800, 'Olivia': 5200})
С остальными тестами тоже самое

2023-12-24 09:33 UTC, kirillsev1 commented on hw1.py
> +    Вычисляет статистику по зарплатам сотрудников в компании.
Добавь typehint

2023-12-24 09:33 UTC, kirillsev1 commented on hw1.py
> +    print(sorted_salaries, percentage)  # Выводит три самые высокие зарплаты из всех отделов
В примере как минимум не должно быть принтов или кода, должны быть примеры и все

2023-12-25 21:45 UTC, nazaroviktor2 commented
Ждем галочку
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/e0449c62-8f76-4311-8f6e-5ea395f8aced)

2024-04-03 00:01 UTC, closed without merging