ARSENOVICH
siriusdevs/homeworks_23 pull request #14
Opened 2023-10-01 19:29 UTC by n0tsSzzz

2023-10-01 19:30 UTC, fedya-eremin commented
So Good!!!

2023-10-01 19:32 UTC, spl3g commented
WOW

2023-10-01 19:44 UTC, siriusdevs commented
@fedya-eremin @spl3g warning

2023-10-01 20:11 UTC, nazaroviktor2 commented on hw1.py
> +                + '{0:.2f}%'.format(sum_of_our_salary / (sum_of_all_salary * 100 or 1)),
Or 1 прикольное решение

2023-10-01 20:16 UTC, nazaroviktor2 commented on hw1.py
> +                + '{0:.2f}%'.format(sum_of_our_salary / (sum_of_all_salary or 1) * 100),
Or 1 прикольное решение

2023-10-01 20:17 UTC, nazaroviktor2 commented on hw1.py
> +                + '3: {0:.2f}; '.format(sum(list_of_values[2:3]))
Зачем тут везде срезы?

2023-10-01 20:19 UTC, n0tsSzzz commented on hw1.py
> +                + '3: {0:.2f}; '.format(sum(list_of_values[2:3]))
> Зачем тут везде срезы?

У срезов есть особенность. Если они вышли за пределы, то они не выдают ошибку

2023-10-01 20:22 UTC, nazaroviktor2 requested changes
Подумай еще раз над решением, сейчас очень большая сложность

2023-10-01 20:26 UTC, Max2288 commented on hw1.py
> +        incident = arg if arg else []
Может его сразу делать не None, а [], тогда не придётся пистаь этот if

2023-10-01 20:32 UTC, n0tsSzzz commented on hw1.py
> +        incident = arg if arg else []
> Может его сразу делать не None, а [], тогда не придётся пистаь этот if

по условию arg = None

2023-10-02 10:29 UTC, nazaroviktor2 commented on hw1.py
> +    arg: tuple[str] | None = None,
Нужно писать переменные, которые как можно точнее отражают информацию в ней. Что такое args? К тебе же приходит кортеж из отделов одной компании и работников. Почему не назвать переменную company или departments? 
Arg? Agree? Агр акса? И следую из переменной  args - кортеж отделов, получается agr - один отдел? Но у тебя agr еще один кортеж департаментов. Почему не назвать переменную более явно excluded или excluded departments?

2023-10-02 10:29 UTC, nazaroviktor2 commented on hw1.py
> +        arg: tuple[str] - exculded company.
Тут наверное опечатка excluded*

2023-10-02 10:41 UTC, nazaroviktor2 commented on hw1.py
> +                + '3: {0:.2f}; '.format(sum(list_of_values[2:3]))
Ты наверное не со всем понял задание. Тебе приходит кортежи одной компании. У компании много отделов и тебе надо посчитать не топ 3 в каждом отделе, а топ 3 во всей компании. Топ 3 по всем отделам _" Функция должна возвращать статистику: последние 3 зарплат в компании (по размеру), отношение суммы этих 3 зарплат ко всему размеру выплат в компании, в процентах"_   
Сейчас ты считаешь топ в каждом отделе, а надо во всей компании.

2023-10-02 10:44 UTC, nazaroviktor2 commented on hw1.py
> +"""Home work about company's salary."""
Homework

2023-10-02 10:47 UTC, nazaroviktor2 commented on text.txt
Я бы сразу переименовал в text1. Если ты будешь делать такие файлы дальше и кидать их в мерже, я буду очень благодарен.  Это ускоряет проверку

2023-10-02 10:48 UTC, nazaroviktor2 requested changes
Ты не много запутался в задание. Надо искать топ 3 во всей компании, а не в одном отделе

2023-10-02 15:50 UTC, nazaroviktor2 commented on hw1.py
> +        incident = excluded if excluded else []
Зачем делать эту проверку при каждой итерации цикла? Вынеси ее в начало функции

2023-10-02 15:56 UTC, nazaroviktor2 commented on hw1.py
> +    sum_of_all_salary = sum(list_of_values)
Это переменную ты используешь один раз, так ли она нужна? Может лучше просто в том месте посчитать сумму?

2023-10-02 16:01 UTC, nazaroviktor2 requested changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/b8667ffa-d943-435b-8d72-831ff2bc4861)

2023-10-02 16:04 UTC, nazaroviktor2 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/983d85b7-5835-4a61-b7ff-6e558f096685)
opps

2023-10-02 16:06 UTC, n0tsSzzz commented
)

2023-10-02 16:06 UTC, n0tsSzzz commented
често, я не очень понимаю, почему там выдает ошибку

2023-10-02 16:11 UTC, nazaroviktor2 commented
> честно, я не очень понимаю, почему там выдает ошибку

![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/8f99533f-a631-464b-b7bf-40ed051052f5)
разбей на несколько строк

2023-10-02 16:14 UTC, n0tsSzzz commented
> > честно, я не очень понимаю, почему там выдает ошибку
> 
> ![image](https://user-images.githubusercontent.com/45715124/272025239-8f99533f-a631-464b-b7bf-40ed051052f5.png) разбей на несколько строк

я так и делал, сейчас повторил и все равно выдает

2023-10-02 16:15 UTC, n0tsSzzz commented
хотя часть кода ниже, написано тоже самое, ошибки - нет

2023-10-02 16:41 UTC, nazaroviktor2 commented on hw1.py
> +    *departaments: tuple[str, dict[str, float]],
departments*

2023-10-02 16:46 UTC, siriusdevs commented on hw1.py
> +        incident = arg if arg else []
> Может его сразу делать не None, а [], тогда не придётся пистаь этот if

Мы не делаем изменяемые типы данных аргументами по умолчанию. Если есть вероятность, что ничего не передадут, пусть будет None, который будем мапить в пустую структуру.

2023-10-02 17:40 UTC, nazaroviktor2 commented on hw1.py
> +        incident = arg if arg else []
> Может его сразу делать не None, а [], тогда не придётся пистаь этот if

Так же упоминал что это плохо, вот [тут](https://github.com/siriusdevs/homeworks_23/pull/11#discussion_r1342113146)

2023-10-02 17:44 UTC, nazaroviktor2 commented
> честно, я не очень понимаю, почему там выдает ошибку

Я посмотрел и как понял с этой ошибкой есть не исправленный [баг](https://github.com/wemake-services/wemake-python-styleguide/issues/454)
@siriusdevs можно кинуть ее в игнор для этого файла?

2023-10-02 21:43 UTC, siriusdevs commented
> > честно, я не очень понимаю, почему там выдает ошибку
> 
> Я посмотрел и как понял с этой ошибкой есть не исправленный [баг](https://github.com/wemake-services/wemake-python-styleguide/issues/454) @siriusdevs можно кинуть ее в игнор для этого файла?

это же список из трех значений, может, тут просто  не переносить строки? попробуйте.

если не выйдет, даю добро на игнор именно этой ошибки, но только в тестах.

2023-10-02 21:48 UTC, siriusdevs commented
@n0tsSzzz это что за названия коммитов?. ещё раз такое увижу в PR - заставлю делать rebase всех коммитов.

@nazaroviktor2 @Max2288 нужно на такое обращать внимание в ревью.
![image](https://github.com/siriusdevs/homeworks_23/assets/102812997/ce42597d-db48-47b5-a871-0d875a27d19c)

2023-10-03 07:28 UTC, nazaroviktor2 submitted a review, later dismissed
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/dfcbd240-2bef-4cb3-a301-f97bce9030b2)

2023-10-03 07:58 UTC, KatyaGotskina requested changes

2023-10-03 07:58 UTC, KatyaGotskina commented on hw1.py
> +    incident = excluded if excluded else []
переменная либо tuple, либо list. Не хорошо. Пусть лучше всегда будет одного типа

2023-10-03 07:58 UTC, KatyaGotskina commented on hw1.py
> +    our_salary = sorted(salaries)[:3]
Что такое our_salary? Ты знаешь наши зарплаты? Лучше назвать по-другому

2023-10-03 10:07 UTC, KatyaGotskina approved these changes
Теперь все гуд, молодец :D

2023-10-03 14:18 UTC, nazaroviktor2 approved these changes
👍

2023-10-04 09:26 UTC, merged