Nehoroshev HW3
siriusdevs/homeworks_23 pull request #142
Opened 2023-12-22 15:18 UTC by fghh64

2023-12-22 15:43 UTC, siriusdevs requested changes

2023-12-22 15:43 UTC, siriusdevs commented on hw3.py
> +        self._car_park.remove(car)
Если машины нет у владельца, будет valueerror

2023-12-22 15:43 UTC, siriusdevs commented on hw3.py
> +        self._cars.remove(car)
если такой машины нет в шоуруме, будет ValueError

2023-12-22 15:43 UTC, siriusdevs commented on hw3.py
> +            self.car_showroom.remove_car(self.car_for_sale)
и этот ValueError по стеку всплывёт здесь

2023-12-22 17:38 UTC, fghh64 commented on hw3.py
> +            self.car_showroom.remove_car(self.car_for_sale)
я немного не понял суть задания. можете пожалуйста сказать что надо исправить

2023-12-22 18:42 UTC, fghh64 commented on hw3.py
> +            self.car_showroom.remove_car(self.car_for_sale)
вы имеете ввиду убрать этот if т.к. ошибка может будет вызываться по функции remove

2023-12-22 18:49 UTC, fghh64 commented on hw3.py
> +            self.car_showroom.remove_car(self.car_for_sale)
![изображение](https://github.com/siriusdevs/homeworks_23/assets/113694919/6a261c85-d38d-42fb-9c49-31cf1c5001b9)

2023-12-22 18:49 UTC, fghh64 commented on hw3.py
> +            self.car_showroom.remove_car(self.car_for_sale)
вот так

2023-12-25 13:49 UTC, fghh64 commented
@kirillsev1 
@nazaroviktor2 
поставьте галочки тенигин тинигин уже проверил работу

2023-12-25 13:50 UTC, fghh64 commented
сегодня на его паре был

2023-12-25 21:39 UTC, nazaroviktor2 approved these changes

2023-12-25 21:39 UTC, nazaroviktor2 commented on hw3.py
> +    """Class for an owner."""
Почему классы разные, а докстринги одинаковые?

2023-12-26 07:55 UTC, siriusdevs approved these changes

2023-12-26 07:55 UTC, merged