Korenyakin A hw3
siriusdevs/homeworks_23 pull request #146
Opened 2023-12-23 14:42 UTC by Raitman17

2023-12-24 11:19 UTC, kirillsev1 requested changes
В принципе все хорошо, исправь проверки и поменяй названия методов get, add, remove, потом поставлю

2023-12-24 11:19 UTC, kirillsev1 commented on hw3/member.py
> +        self.max_count_projects = max_count_projects
Проверки на типы данных и int > 0

2023-12-24 11:19 UTC, kirillsev1 commented on hw3/member.py
> +        if new_value < 0:
<= 0, иначе может быть 0 задач

2023-12-24 11:19 UTC, kirillsev1 commented on hw3/member.py
> +        self._max_count_projects = new_value
Аналогично <= 0

2023-12-24 11:19 UTC, kirillsev1 commented on hw3/project.py
> +        Args:
get зарезервированная функция

2023-12-24 15:21 UTC, kirillsev1 approved these changes

2023-12-27 10:49 UTC, siriusdevs approved these changes

2023-12-27 10:49 UTC, merged