Tatarnikov hw3
siriusdevs/homeworks_23 pull request #147
Opened 2023-12-23 18:52 UTC by I-AM-LAMER

2023-12-24 11:37 UTC, kirillsev1 requested changes

2023-12-24 11:37 UTC, kirillsev1 commented on hw3/airline.py
> +    """
1) Думаю, не правильно наследовать авиакомпанию от пассажира, полета и билета. Потому что из-за этого у авиакомпании появляются методы и свойства билетов, пассажиров и полетов, что не правильно 
2) Так указывается наследование от классов, не аргументы которые класс принимает

2023-12-24 11:37 UTC, kirillsev1 commented on hw3/airline.py
> +    ) -> None:
Не хватает названия авиакомпании

2023-12-24 11:37 UTC, kirillsev1 commented on hw3/flight.py
> +        self.flight_num = flight_num
Проверка int на тип и > 0

2023-12-24 17:11 UTC, I-AM-LAMER commented on hw3/flight.py
> +        self.flight_num = flight_num
она же есть

2023-12-25 05:30 UTC, I-AM-LAMER commented
@kirillsev1

2023-12-27 05:59 UTC, I-AM-LAMER commented
@kirillsev1 мне бы ревью ппжпжпжп

2023-12-27 10:25 UTC, siriusdevs approved these changes

2023-12-27 10:25 UTC, siriusdevs commented on hw3/passenger.py
> +        if not new_id.isnumeric():
should use `isdigit()`

2023-12-27 10:25 UTC, merged