Argun HW2
siriusdevs/homeworks_23 pull request #149
Opened 2023-12-24 10:24 UTC by anonimys2020

![image](https://github.com/siriusdevs/homeworks_23/assets/59397551/25b405a9-bca5-4163-8e8c-44e7e141e31f)

2023-12-24 10:30 UTC, kirillsev1 requested changes

2023-12-24 10:30 UTC, kirillsev1 commented on hw2/hw2.py
> +    return {key: (count / total_users) * 100 for key, count in data_dict.items()}
ZeroDivisionError

2023-12-24 11:38 UTC, kirillsev1 submitted a review, later dismissed

2023-12-26 07:19 UTC, siriusdevs requested changes

2023-12-26 07:19 UTC, siriusdevs commented on hw2/hw2.py
> +    status_switch = {
здесь должен быть цикл. 
если у вас периодов станет 100, вы будете руками расписывать 100 случаев. и т.д.

2023-12-26 07:19 UTC, siriusdevs commented on hw2/hw2.py
> +    last_login_date = datetime.strptime(user.get('last_login', ''), '%Y-%m-%d')
тут, несмотря на то, что использовали get, дальше будет ошибка формата даты

2023-12-26 07:19 UTC, siriusdevs commented on hw2/test_hw2.py
> +
не хватает тестов на пустой файл, пустой json, неправильный json (например, если там нет тех же login_data в данных пользвователя)

2023-12-26 08:06 UTC, anonimys2020 commented on hw2/hw2.py
> +    status_switch = {
Эта функция проверяет конкретного пользователя, а не всех. В функции process_data я проверяю всех пользователей циклом.

2023-12-26 08:11 UTC, anonimys2020 commented on hw2/hw2.py
> +    last_login_date = datetime.strptime(user.get('last_login', ''), '%Y-%m-%d')
Исправил.

2024-02-05 15:04 UTC, siriusdevs approved these changes

2024-02-05 15:04 UTC, merged