Argun HW3
siriusdevs/homeworks_23 pull request #150
Opened 2023-12-24 10:25 UTC by anonimys2020

![image](https://github.com/siriusdevs/homeworks_23/assets/59397551/479809c8-cd99-4ec3-b839-37d729b196de)

2023-12-24 10:37 UTC, kirillsev1 requested changes

2023-12-24 10:37 UTC, kirillsev1 commented on hw3/hw3.py
> +        self.books.append(book)
Методы дублируют self.add_book() и self.remove_book()

2023-12-24 10:37 UTC, kirillsev1 commented on hw2/hw2.py
> +    return {key: (count / total_users) * 100 for key, count in data_dict.items()}
ZeroDivisionError

2023-12-24 11:53 UTC, kirillsev1 requested changes
Исправь логику работы библиотеки и все

2023-12-24 11:53 UTC, kirillsev1 commented on hw3/hw3.py
> +        library.return_book(self, book)
Сделай так, чтобы читатель обращался не к библиотеке, а к библиотекарю, библиотекарь обращался к библиотеки и передавал книгу пользователю

2023-12-24 11:53 UTC, kirillsev1 commented on hw3/hw3.py
> +            Accepts a returned book from a reader.
Иными словами библиотекарь должен получить книгу из библиотеки, удалить из ее списка книг и отдать пользователю

У тебя в аннотации даже прописаны эти методы, но в классе их нет

2023-12-24 13:50 UTC, anonimys2020 commented
Как я понял, нужно сделать так:
Reader(book) -> Librarian(library, book) -> Library.remove_book(book)
Читатель обращается к библиотекарю, чтобы ему выдали книгу. Библиотекарь вызывает метод remove_book(book) у библиотеки.

Reader(book) -> Librarian(library, book) -> Library.add_book(book)
Читатель обращается к библиотекарю, чтобы сдать книгу. Библиотекарь вызывает метод add_book(book) у библиотеки. Тут аналогичная проблема. т.к. мы не знаем, с какой именно библиотекой мы работаем, мы не можем вызвать эти два метода. А сам читатель не должен нам передавать объект библиотеки.

Я решил эту проблему добавив аттрибут library, при инициализации объекта Librarian.

2023-12-24 15:17 UTC, kirillsev1 requested changes
Хорошо, что понял о чем я говорил, последняя правка

2023-12-24 15:17 UTC, kirillsev1 commented on hw3/hw3.py
> +        """Allow a reader to borrow a book from the library.
Сеттер пустой

2023-12-24 16:27 UTC, kirillsev1 approved these changes

2023-12-26 07:25 UTC, siriusdevs requested changes
нарушен SOLID

+ нужно отсюда убрать вторую дз, чтобы она не мерджилась автоматически вместе с третьей

2023-12-26 07:25 UTC, siriusdevs commented on hw3/hw3.py
> +        librarian.lend_book(self, book)
методы читателя не должны управлять библиотекерем

2023-12-26 07:25 UTC, siriusdevs commented on hw3/hw3.py
> +        reader.borrowed_books.append(book)
читатель получает библиотекаря, а библиотекарь получает читателя
:1st_place_medal:

2023-12-26 08:35 UTC, anonimys2020 commented on hw3/hw3.py
> +        librarian.lend_book(self, book)
А как тогда сделать? Librarian же по сути представлен адаптером, связывающим библиотеку и читателя

2024-02-05 15:05 UTC, siriusdevs submitted a review, later dismissed

2024-02-05 15:06 UTC, siriusdevs commented
to be merged, resolve conflict

2024-02-06 07:41 UTC, merged