Otroschenko HW2
siriusdevs/homeworks_23 pull request #152
Opened 2023-12-24 16:52 UTC by AntohaOt

2023-12-25 22:36 UTC, nazaroviktor2 requested changes

2023-12-25 22:36 UTC, nazaroviktor2 commented on HW2/test_hw2.py
> +    ),
Это должно быть файле. Тесты должны проверять, что новый файл, которые создаем функция procces data равен файлу, который уже есть на диске

2023-12-26 07:16 UTC, AntohaOt commented
@nazaroviktor2 Исправил

2023-12-26 17:55 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/daece7a4-50ed-402c-92a4-2e626ba5dd84)

2024-02-16 07:37 UTC, siriusdevs approved these changes

2024-02-16 07:37 UTC, merged