HW1
siriusdevs/homeworks_23 pull request #154
Opened 2023-12-24 19:23 UTC by 0m0ra

2023-12-25 21:43 UTC, nazaroviktor2 requested changes
Нет галочки на репозитории

2023-12-25 21:43 UTC, nazaroviktor2 commented on hw1/hw1.py
> +def salary_statistics(company_dict, min_salary=None):
Добавь аннотации

2023-12-25 21:43 UTC, nazaroviktor2 commented on hw1/hw1.py
> +        min_salary: int optional - the minimum threshold for salaries. Defaults to None.
Только int? Float быть не может?

2023-12-25 21:43 UTC, nazaroviktor2 commented on hw1/hw1.py
> +
```suggestion
    for workers in company_dict.values():
        all_salaries.extend(workers.values())

```

2023-12-25 21:43 UTC, nazaroviktor2 commented on hw1/hw1.py
> +    for i in range(3):
лучше идти по длиннее массива

2023-12-25 21:43 UTC, nazaroviktor2 commented on hw1/test_hw1.py
> +                                                                  })))
Тут явно что то не так

2023-12-25 21:43 UTC, nazaroviktor2 commented on hw1/hw1.py
> +    ratio = round(sum(top_salaries) / sum(all_salaries) * 100, 2)
Ошибка деление на 0.

2023-12-25 22:21 UTC, nazaroviktor2 requested changes

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(input_path, 'r') as read_file:
Если файл не найден?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    ages = [user['age'] for user in data.values()]
Если нет этого ключа?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        year = user['registered'].split('-')[0]
Если нет этого ключа? Если разделитель точка?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw2/hw2.py
> +            'middle_age': sum(ages) // len(ages),
Деление на 0

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw2/hw2.py
> +            'mediana': max(ages, key=lambda k: ages.count(k))
медиана считается не так. Это средний элемент в отсортированном списке

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        write_file.write(json.dumps(years))
У тебя получился не верный json. Надо за одну запись сделать

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw2/test_hw2.py
> +        process_data(input_path, output_path)
Не понятен прикол тестов. Что они тестируют? У тебя должен быть файл с входными параметрами и с выходными. Ты вызываешь функцию process_data со входными параметрами и запись файла должна идти в третий файл. Потом ты проверяешь, что третий файл равен выходному файлу

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +            price: int - the price of the car.
Цена может быть только целым числом?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        self._price = new_price
Не хватает проверок

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        self._year_of_vehicle = new_year_of_vehicle
Где проверки?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +    def __init__(self, model: str, year_of_vehicle: int, price: int, passengers: int) -> None:
Цена только целое число?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        Car.__init__(self, model, year_of_vehicle, price)
??? 
тут должен быть super

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        self._passengers = new_passengers
Проверки?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +                 price: int, lifting_capacity: int) -> None:
Цена и грузоподьемность только целые числа?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        Car.__init__(self, model, year_of_vehicle, price)
super

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        self._lifting_capacity = new_lifting_capacity
проверки

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +    def __init__(self, cars: list((Car, PassengerCar, Truck)) = None) -> None:
Не верная аннотация. Она пишется в [] скобочках 
+ хватит только Car так, как остальные наследники

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +            self._cars = [*cars]
?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +    def add(self, car: (Car, PassengerCar, Truck)) -> None:
Тоже самое

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +            self._cars.remove(car)
если такое машины нет в списке?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        return self._cars
? сетер возвращает значение?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/test_hw3.py
> +
Где тесты на создание классов?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/test_hw3.py
> +    assert car_park.add(car) == expected_value
В чем прикол теста? Что он проверяет?

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw3/test_hw3.py
> +    assert car_park.remove(car) == expected_value
В чем прикол теста? Он же вообще не работает. Прежде чем удалить надо добавить

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw2/hw2.py
> +def process_data(input_path, output_path):
Эта функции должна обрабатывать все возможные ошибки в ходе выполнения программы. То есть при ее вызове пользователь не должен увидеть traceback в консоли. При ошибки можно возвращать сообщение об ошибки (return ) или писать сообщение в файл

2023-12-25 22:21 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(output_path, 'w') as write_file:
Если конечный путь не найден ? см os.makedirs()

2024-02-14 18:25 UTC, kirillsev1 requested changes

2024-02-14 18:25 UTC, kirillsev1 commented on hw3/test_hw3.py
> +    return CarPark()
Напиши докстирнги к функциям и к тем, которые ниже. Короткие хотя бы

2024-02-15 11:58 UTC, merged