Ivanov a
siriusdevs/homeworks_23 pull request #159
Opened 2023-12-25 11:36 UTC by hape30

2023-12-25 21:06 UTC, hape30 commented
@siriusdevs 
@nazaroviktor2 
посмотрите пожалуйста!

2023-12-26 06:32 UTC, siriusdevs requested changes
+ разделить на три PR с тремя домашними

2023-12-26 06:32 UTC, siriusdevs commented on hw1/hw1.py
> +def calculate_salary(
если зарплаты у всех 0, функция в топ-3 зарплат должна вернуть 0, 0, 0. Но она не возвращает. Почему?

2023-12-26 06:32 UTC, siriusdevs commented on hw2/hw2.py
> +            '<2 days': sum(day < 2 for day in result_data[Constants.online_days[0]])
во всех местах, где вы делите на значение, которое выше прибавляли, оно изначально было равно 0. если оно не прибавится, тут останется 0. и вы получите деление на 0. оно вызовет ошибку, программа упадет с ошибкой ZeroDivisionError. 
А раз ваши тесты проходят, значит, вы это не покрываете тестами.

2023-12-26 06:32 UTC, siriusdevs commented on hw2/hw2.py
> +"""Файл с ДЗ 2."""
раз тесты не закрывают плохие случаи, значит где-то здесь ещё и ошибка с тем, что если в json пользователя нет нужных данных, мы их не найдём, не посчитаем,  и не уведомим пользователя или упадем с ошибкой

2023-12-26 06:32 UTC, siriusdevs commented on hw3/hw3.py
> +        self._dishes.remove(dish)
если блюда нет в ресторане, вы вы всё равно вызываете remove и будет ValueError, потому что перед удалением вы не проверили, есть он или нет

2023-12-26 06:32 UTC, siriusdevs commented on hw3/test_hw3.py
> +        self.dish.remove_product(new_product)
соответственно ошибка всплывет и в этих методах тоже

2023-12-26 06:32 UTC, siriusdevs commented on hw3/test_hw3.py
> +        self.menu_manager.remove_dish(PIZZA)
тест удаление несуществующего блюда также не проверяет, поэтому тесты и проходят.

2024-02-13 18:12 UTC, closed without merging