Demyanenko
siriusdevs/homeworks_23 pull request #16
Opened 2023-10-03 20:58 UTC by slavikyd

2023-10-04 09:33 UTC, kirillsev1 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/b595f82f-35d9-4f2a-846c-cb40c168e8a3)
Исправь workflows

2023-10-04 10:01 UTC, slavikyd commented
> ![image](https://user-images.githubusercontent.com/112825746/272529579-b595f82f-35d9-4f2a-846c-cb40c168e8a3.png) Исправь workflows

Он не проходит как раз из за бага с WPS317
<img width="336" alt="image" src="https://github.com/siriusdevs/homeworks_23/assets/47947352/38afef05-baad-4b7c-af02-814805f7f334">

2023-10-04 10:05 UTC, kirillsev1 commented
Хорошо, это решай с siriusdevs. Пока что исправь остальное

2023-10-04 11:45 UTC, siriusdevs commented
@slavikyd разрешаю добавить WPS317 для тестов в ignore

2023-10-06 10:22 UTC, slavikyd commented
@kirillsev1, день добрый, исправил все что нашел

2023-10-06 12:46 UTC, kirillsev1 commented
Еще не все исправлено. Теперь у тебя есть проверка на zero division, но еще надо исправить входные данные(сделать их как в условии), и исправить тесты

2023-10-06 14:03 UTC, kirillsev1 commented
Смотри у тебя написано так:
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/e7004f15-d4b0-4cf0-88a4-b3a3b78bcb82)
Твоя функция принимает словарь, и еще два аргумента(department, limit).

А по заданию должна принимать словарь, и один аргумент - limit

2023-10-07 11:16 UTC, nazaroviktor2 commented on hw1.py
> +from typing import Tuple
С версии python 3.9 Dict, Tuple можно не импортировать из typing. https://peps.python.org/pep-0585/
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/8d40a548-0398-430f-a6ba-09f9d73415a8)

2023-10-07 11:21 UTC, nazaroviktor2 commented on hw1.py
> +def get_salary_stats(data_salaries: dict, department: str, limit: int = None) -> Tuple:
что такое department? В задание нет такого входного параметра, есть только словарь и limit

2023-10-07 11:22 UTC, nazaroviktor2 commented on test_hw1.py
> +test_data = {
Все константы лучше писать капсом

2023-10-07 11:23 UTC, nazaroviktor2 commented on hw1.py
> +    if limit is not None:
можно просто` if limit`

2023-10-07 11:23 UTC, nazaroviktor2 commented on hw1.py
> +        salaries_list = [elem for elem in salaries_list if elem <= limit]
elem?

2023-10-07 11:24 UTC, nazaroviktor2 commented on hw1.py
> +    for elem in salaries_list:
elem?

2023-10-07 11:28 UTC, nazaroviktor2 requested changes
Пожалуйста, прочитай задание еще раз. Тебе приходит слова 
```
{
    "Название отдела":  {
        "Имя сотрудника":  зарплата
        }
 }
```

2023-10-07 19:37 UTC, slavikyd commented on hw1.py
> +    for elem in salaries_list:
fixed in last commit

2023-10-07 19:37 UTC, slavikyd commented on hw1.py
> +        salaries_list = [elem for elem in salaries_list if elem <= limit]
fixed in last commit

2023-10-07 19:38 UTC, slavikyd commented on hw1.py
> +    if limit is not None:
ориентировался на flake и случайно намудрил, уже исправил

2023-10-07 19:38 UTC, slavikyd commented on test_hw1.py
> +test_data = {
fixed

2023-10-07 19:38 UTC, slavikyd commented on hw1.py
> +def get_salary_stats(data_salaries: dict, department: str, limit: int = None) -> Tuple:
уже исправлено

2023-10-07 19:39 UTC, slavikyd commented on hw1.py
> +from typing import Tuple
не увдиел что в docstring написал с большой и думал, что сижу на старой версии питона, исправлено

2023-10-08 11:12 UTC, nazaroviktor2 commented on hw1.py
> +def get_salary_stats(data_salaries: dict, limit: int = None) -> tuple:
почему название data_salaries? Тебе же приходят отделы одной компании - company,  departments.

2023-10-08 11:12 UTC, nazaroviktor2 commented on hw1.py
> +def get_salary_stats(data_salaries: dict, limit: int = None) -> tuple:
еще dict чего? Я бы дополнил аннотацию `dict[str, dict]`

2023-10-08 11:16 UTC, nazaroviktor2 commented on hw1.py
> +    for department, _ in data_salaries.items():
Если тебе нужны значения можно просто идти по ключам data_salaries.keys()

2023-10-08 11:18 UTC, nazaroviktor2 commented on hw1.py
> +        salaries_list = data_raw.values()
А это что? Зачем?

2023-10-08 11:59 UTC, nazaroviktor2 commented on hw1.py
> +            salaries.append(salar)
Зачем идти 2 раза по одним и тем же данным?

2023-10-08 11:59 UTC, nazaroviktor2 requested changes
Очень не понятно

2023-10-08 19:27 UTC, slavikyd commented on hw1.py
> +def get_salary_stats(data_salaries: dict, limit: int = None) -> tuple:
renamed it

2023-10-08 19:28 UTC, slavikyd commented on hw1.py
> +def get_salary_stats(data_salaries: dict, limit: int = None) -> tuple:
Added in the last commit

2023-10-08 19:28 UTC, slavikyd commented on hw1.py
> +    for department, _ in data_salaries.items():
fixed it in last commit

2023-10-08 19:29 UTC, nazaroviktor2 commented on hw1.py
> +            raise ZeroDivisionError('It seems like there is no salary at all, check the data')
почему просто не возвращать `return  salaries[:3], 100`? У меня может быть 3 сотрудника, которым я не плачу

2023-10-08 19:29 UTC, slavikyd commented on hw1.py
> +        salaries_list = data_raw.values()
that was not removed after first rework of code, I just forgot about this thing

2023-10-08 19:31 UTC, slavikyd commented on hw1.py
> +            salaries.append(salar)
This was my bicycle for solving the issue with the fact that on each new iteration salaries_list was reassigned, fixed it now to look more pretty

2023-10-08 19:32 UTC, nazaroviktor2 commented on hw1.py
> +        salaries = sorted([round(salary, 2) for salary in salaries], reverse=True)
Зачем ты при каждой итерации сортируешь? Более эффективно  сначала сохранить все заплаты и потом один раз отсортировать, чем сортировать при каждой итерации. Сложность очень высокая O(n^2 log(n))

2023-10-08 19:37 UTC, nazaroviktor2 commented on hw1.py
> +        salaries_list = company_salaries_data[department].values()
Если тебе нужны значения зп у сотрудников то почему не сделать так?

```
for employees in company_salaries_data.keys(): 
    salaries_list = employees.values()

```

2023-10-08 19:39 UTC, nazaroviktor2 commented on test_hw1.py
> +test_data = {
константы лучше писать капсом

2023-10-08 19:39 UTC, nazaroviktor2 requested changes
Еще не много доработать

2023-10-08 19:40 UTC, slavikyd commented on hw1.py
> +        salaries_list = company_salaries_data[department].values()
Так я же иду по отделам а не по отлельным рабочим. Имена рабочих ни в условии ни в коде роли не играют, разве есть смысл называть отдел работниками? Да и фактически получится тоже самое же...

2023-10-08 19:41 UTC, slavikyd commented on test_hw1.py
> +test_data = {
забыл убрать, оно там в целом лишнее, уже чиню

2023-10-08 19:47 UTC, nazaroviktor2 commented on hw1.py
> +        salaries_list = company_salaries_data[department].values()
Да тоже самое, но букв меньше и сразу понятно, что ты получаешь. То ты идешь по ключам, чтобы получить значения))) Зачем? можно сразу получать значения

2023-10-08 20:05 UTC, slavikyd commented on hw1.py
> +        salaries_list = company_salaries_data[department].values()
<img width="308" alt="image" src="https://github.com/siriusdevs/homeworks_23/assets/47947352/bc9ce359-e252-4146-a83b-69986705449d">

Ну просто я так уже пробовал, ничего кроме вот этого не получается

2023-10-08 20:10 UTC, nazaroviktor2 commented on hw1.py
> +        salaries_list = company_salaries_data[department].values()
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/3317c7be-a341-4c58-bd0b-2f848f883aae)

2023-10-08 20:11 UTC, nazaroviktor2 commented on hw1.py
> +        salaries_list = company_salaries_data[department].values()
> Если тебе нужны значения зп у сотрудников то почему не сделать так?
> 
> ```
> for employees in company_salaries_data.values(): 
>     salaries_list = employees.values()
> ```

тут была ошибка, случайно написал keys вместо values

2023-10-08 20:32 UTC, slavikyd commented on hw1.py
> +            raise ZeroDivisionError('It seems like there is no salary at all, check the data')
Done

2023-10-08 20:32 UTC, slavikyd commented on hw1.py
> +        salaries = sorted([round(salary, 2) for salary in salaries], reverse=True)
Вытащил из под цикла, теперь сортируется только перед return

2023-10-08 20:33 UTC, slavikyd commented on hw1.py
> +        salaries_list = company_salaries_data[department].values()
Сделано

2023-10-08 20:44 UTC, nazaroviktor2 commented on hw1.py
> +    for departments in company_salaries_data.values():
Мы получаем работников одного департамента. Лучше назвать employees

2023-10-08 20:44 UTC, nazaroviktor2 commented on test_hw1.py
> +test_data = {
Константы лучше писать капсом

2023-10-08 20:44 UTC, nazaroviktor2 commented on test_hw1.py
> +test_data_value = (
Это тоже константа

2023-10-08 20:45 UTC, nazaroviktor2 commented on test_hw1.py
> +)
Тоже

2023-10-08 20:46 UTC, nazaroviktor2 submitted a review, later dismissed
Молодец 
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/d877528a-9367-409d-8266-2f9013043ff7)

2023-10-08 20:51 UTC, kirillsev1 approved these changes

2023-10-08 20:56 UTC, nazaroviktor2 commented on test_hw1.py
> +    assert get_salary_stats(test_data, department) == expected
Название нормальное, но лучше departments или company. А сами тесты да, странные

2023-10-09 07:42 UTC, slavikyd commented on test_hw1.py
> +test_data = {
Что странно, flake ругается если test_data капсом написать, выдает WPS407, с остальными такого нет, сейчас добавлю измененное

2023-10-09 07:48 UTC, slavikyd commented on hw1.py
> +        salaries.append(salary)
Исправлено

2023-10-09 07:49 UTC, slavikyd commented on hw1.py
> +    """
Исправлено

2023-10-09 07:51 UTC, slavikyd commented on hw1.py
> +    for departments in company_salaries_data.values():
Поменял

2023-10-09 08:25 UTC, nazaroviktor2 approved these changes
👍

2023-10-10 21:44 UTC, radugaboost commented
хорошая работа, молодец 🙂

2023-10-10 21:46 UTC, radugaboost approved these changes
👍

2023-10-11 11:43 UTC, siriusdevs approved these changes

2023-10-11 11:44 UTC, merged