Tyapkova HW3
siriusdevs/homeworks_23 pull request #160
Opened 2023-12-25 12:03 UTC by viktoriatyapkova

2023-12-25 12:11 UTC, viktoriatyapkova commented
@siriusdevs 
@kirillsev1 
@nazaroviktor2

2023-12-25 22:27 UTC, nazaroviktor2 requested changes

2023-12-25 22:27 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        return f'{self.__class__.__name__} with price: {self.price}'
Тут нет это атрибута. Как это должно работать если я создам экземпляр класса DishMethods?

2023-12-25 22:27 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        return f'{self.__class__.__name__} recipient: {self.client} \
Тоже самое что с классом DishMethods. Как это должно работать?

2023-12-25 22:27 UTC, nazaroviktor2 commented on hw3/hw3.py
> +class RestaurantMethods:
Тоже самое как DishMethods. У тебя зависимости должны работать наоборот

2023-12-27 22:07 UTC, nazaroviktor2 approved these changes
hm3

2024-02-05 14:59 UTC, siriusdevs approved these changes

2024-02-05 14:59 UTC, merged