Tyurin
siriusdevs/homeworks_23 pull request #17
Opened 2023-10-03 21:17 UTC by rTiRe

2023-10-05 20:30 UTC, KatyaGotskina requested changes

2023-10-05 20:30 UTC, KatyaGotskina commented on hw1.py
> +def get_top_salaries(*args: Tuple[str, list], departments: Tuple[str] = None) -> tuple:
Лучше args назвать более информативно, если это - данные про отделы - пусть будет *departments или как тебе больше нравится. 
Аналогично про второй аргумент, если приходят только нужные отделы, пусть переменная лучше отражает суть, а то можно запутаться

2023-10-05 20:30 UTC, KatyaGotskina commented on hw1.py
> +        tuple: A tuple containing two elements:
Не надо такого повторения, ты уже обозначил, что это кортеж

2023-10-05 20:30 UTC, KatyaGotskina commented on hw1.py
> +        args = filter(lambda arg: arg, args)
Не думаю, что нужна такая серьезная проверка, пользователь должен еще постараться ввести настолько некорректные данные :) 
Данная фильтрация выполняется за O(n) и прибавляет время к периоду выполнения программы.
Так что решай сам, оставлять ее или нет

2023-10-05 20:30 UTC, KatyaGotskina commented on hw1.py
> +        args = tuple(args)
можно объект фильтра сразу обернуть в tuple

2023-10-05 20:30 UTC, KatyaGotskina commented on hw1.py
> +        top_salaries.extend(salaries)
По-моему 

for salaries in args:
        top_salaries.extend(salaries[1])

делает то же самое, разве нет?

2023-10-05 20:30 UTC, KatyaGotskina commented on hw1.py
> +        return 'Sorry, salary cannot be less than zero.'
Лучше создать ошибку и возвращать ее

2023-10-05 20:31 UTC, KatyaGotskina commented on hw1.py
> +        args = tuple(args)
название переменной "args" - не очень хорошее решение

2023-10-05 20:33 UTC, rTiRe commented on hw1.py
> +        args = tuple(args)
Тогда flake8 ругается на Jones Complexity

2023-10-05 20:33 UTC, KatyaGotskina requested changes

2023-10-05 20:33 UTC, KatyaGotskina commented on hw1.py
> +    top_salaries = []
Почему переменная называется "top_salaries", если ты туда добавляешь вообще все зарплаты?

2023-10-05 20:34 UTC, KatyaGotskina commented on hw1.py
> +    top_salaries = []
И top с конца или с начала  - не понятно. Я бы подумала, что ты про самые большие зарплаты

2023-10-05 20:42 UTC, KatyaGotskina requested changes

2023-10-05 20:42 UTC, KatyaGotskina commented on hw1.py
> +    top_salaries.sort(reverse=True)
Тебе же по заданию нужны самые маленькие зарплаты :О

2023-10-05 20:51 UTC, rTiRe commented on hw1.py
> +        args = filter(lambda arg: arg, args)
Не совсем понял. Я проверяю что кортеж с отделами не пустой. Если он будет пустой, то фильтр выкинет TypeError

2023-10-05 21:04 UTC, rTiRe commented on hw1.py
> +        top_salaries.extend(salaries)
![image](https://github.com/siriusdevs/homeworks_23/assets/61313696/1c14f064-1925-4051-b78d-2d3ebcff5537)
Не совсем. Приходится сначала доставать список зарплат с кортежа. Если бы можно было во включении распаковывать - было бы легче.

2023-10-05 21:06 UTC, KatyaGotskina commented on hw1.py
> +        args = filter(lambda arg: arg, args)
Чтобы проверить, что кортеж не пустой, достаточно if not args return (error).
Ты проверяешь на вообще все случаи, по типу следующих:

get_top_salaries('Develop', [1000, 200, 500]), (), ())
get_top_salaries(), ('Marketing', [400, 600, 300]), ())
get_top_salaries((), ('Marketing', [400, 600, 300]), ('Sales', [500, 700, 100]), ())

Проверка происходит за n итераций

2023-10-05 21:13 UTC, KatyaGotskina commented on hw1.py
> +        top_salaries.extend(salaries)
Циклом for salaries in args иду по кортежам. salaries[1] является списком зарплат, я его сразу добавляю в общий список top_salaries. Чем я не достаю список заплат?

2023-10-05 21:14 UTC, rTiRe commented on hw1.py
> +        top_salaries.extend(salaries)
Все, я про if забыл, извиняюсь

2023-10-05 21:22 UTC, rTiRe commented on hw1.py
> +        args = filter(lambda arg: arg, args)
Я проверяю не args, а кортеж departments, который по умолчанию None.
Мне мне нужно возвращать ошибку, если этот кортеж пустой.
По сути я делаю то же самое что и

if len(departments) > 0

2023-10-05 21:24 UTC, rTiRe commented on hw1.py
> +        return 'Sorry, salary cannot be less than zero.'
Если делать через raise Exception(), то flake8 ругается - исключение не прописано.
Писать отдельный класс не охота

2023-10-05 21:31 UTC, KatyaGotskina commented on hw1.py
> +        return 'Sorry, salary cannot be less than zero.'
Надо написать отдельный класс для ошибки :)
Добро пожаловать в наш клуб

2023-10-05 21:32 UTC, KatyaGotskina commented on hw1.py
> +        args = filter(lambda arg: arg, args)
У тебя же фильтруются args, причем тут departments

2023-10-05 21:35 UTC, rTiRe commented on hw1.py
> +        args = filter(lambda arg: arg, args)
Если departments не None, то в args оставляем только кортежи, в которых есть названия отделов из departments

2023-10-05 21:38 UTC, KatyaGotskina commented on hw1.py
> +        args = filter(lambda arg: arg, args)
Эта беседа идет исключительно о строчке args = filter(lambda arg: arg, args)

2023-10-05 21:39 UTC, KatyaGotskina commented on hw1.py
> +        args = filter(lambda arg: arg, args)
Эта беседа идет исключительно о строчке args = filter(lambda arg: arg, args)

2023-10-05 21:50 UTC, rTiRe commented on hw1.py
> +        args = filter(lambda arg: arg, args)
А. Понял.
Эта строка убирает пустые кортежи. Если их оставить, то второй фильтр выкинет ошибку.
Старался взять во внимание все случаи ввода. Если пустой кортеж точно не будут передавать, то да - этот фильтр лишний.

2023-10-06 22:46 UTC, Max2288 commented on test_hw1.py
> +def test_get_top_salaries_without_departments(args: tuple, expected: tuple):
может стоит назвать переменную не args? ты же ниже пишешь её описание, значит можно явно указать что приходит в тест, обычно args - это аргументы, которые могут придти, а могут и нет

2023-10-06 22:47 UTC, Max2288 commented on test_hw1.py
> +def test_get_top_salaries_with_departments(args: tuple, deps: Tuple[str], expected: tuple):
аналогично тому, что выше и можно использовать tuple[str], если python > 3.9

2023-10-07 12:21 UTC, KatyaGotskina commented on hw1.py
> +from typing import Tuple
Аналогично в файле с тестами

2023-10-09 15:25 UTC, KatyaGotskina requested changes

2023-10-09 15:25 UTC, KatyaGotskina commented on hw1.py
> +        if len(department) > 1:
Зачем это? Лучше уж вызывать ошибку, если решил обрабатывать настолько некорректные данные, чем их игнорировать

2023-10-09 15:25 UTC, KatyaGotskina commented on hw1.py
> +        raise Exception('Sorry, salary cannot be less than zero.')
Что насчет https://github.com/siriusdevs/homeworks_23/pull/17#discussion_r1348003749? 
не надо менять конфиг, надо создать класс кастомной ошибки

2023-10-09 15:29 UTC, rTiRe commented on hw1.py
> +        raise Exception('Sorry, salary cannot be less than zero.')
Мы ООП еще не проходили. Альберт Андреевич разрешил сделать так.

2023-10-09 15:32 UTC, rTiRe commented on hw1.py
> +        if len(department) > 1:
Я игнорирую пустые кортежи. Зачем вызывать ошибку если просто не передали отдел? Этот код фильтрует отделы. Сначала убирает пустые кортежи, потом оставляет только отделы, необходимые для дальнейшей обработки.

2023-10-09 15:39 UTC, KatyaGotskina commented on hw1.py
> +        if len(department) > 1:
Так, код убирает пустые кортежи с помощью filter(lambda arg: arg, departments). 
А if len(department) > 1 что делает?

2023-10-09 15:40 UTC, KatyaGotskina commented on hw1.py
> +        raise Exception('Sorry, salary cannot be less than zero.')
Хорошо

2023-10-09 15:43 UTC, KatyaGotskina requested changes

2023-10-09 15:43 UTC, KatyaGotskina commented on hw1.py
> +    sorted_salaries.sort()
Зачем их сортировать, если они уже "sorted_salaries"? :D

2023-10-09 15:44 UTC, rTiRe commented on hw1.py
> +        if len(department) > 1:
Проверяет, передан ли список зарплат в отделе. Если убрать этот if, то `sorted_salaries.extend(department[1])` на следующей строчке может ругаться на то, что элемента под указанным индексом нет

2023-10-09 15:47 UTC, KatyaGotskina commented on hw1.py
> +        if len(department) > 1:
Правильно, то есть ты игнорируешь кортежи с названием отделов, но без зарплат. А если человек ошибся и забыл дописать зарплаты? А отдел существует и надо его учесть? Надо вернуть ошибку пользователю, что он не правильно ввел данные

2023-10-09 15:48 UTC, KatyaGotskina commented
И не закрывай наши обсуждения самостоятельно пожалуйста :(

2023-10-09 15:53 UTC, KatyaGotskina commented on hw1.py
> +            percent = float(0)
В каком случае sum(sorted_salaries) = 0, но sorted_salaries возвращает True? Ничего не понимаю

2023-10-09 16:24 UTC, rTiRe commented on hw1.py
> +            percent = float(0)
Если передана одна или несколько ЗП = 0, тогда `sum(sorted_salaries) = 0`. `if sorted_salaries` то же самое, что `if len(sorted_salaries) > 0`. Если переданы нули, то `len(sorted_salaries) > 0` - ЗП есть и процентное отношение не может быть 0%, поэтому возвращаем 100%

2023-10-09 16:28 UTC, rTiRe commented on hw1.py
> +    sorted_salaries.sort()
логично. Поправил

2023-10-09 16:31 UTC, rTiRe commented on hw1.py
> +        if len(department) > 1:
Он считает кортежи с пустым list зарплат, но не считает кортежи без листа зарплат.
Хорошо, буду обрабатывать как ошибку.

2023-10-09 16:58 UTC, KatyaGotskina commented on hw1.py
> +            percent = float(0)
Спорный момент, но допустим

2023-10-09 16:59 UTC, KatyaGotskina commented on hw1.py
> +            percent = float(0)
Можно написать percent = float(100) if sorted_salaries else float(0)

2023-10-15 19:27 UTC, KatyaGotskina requested changes
Исправь эти недочеты и я дам аппрув

2023-10-15 19:27 UTC, KatyaGotskina commented on hw1.py
> +        Exception: occurs if there are salaries less than zero.
Ты три раза вызываешь ошибку, но в описании есть только один случай

2023-10-15 19:27 UTC, KatyaGotskina commented on hw1.py
> +            raise Exception(f'Salary list not found for department in index {department_index}')
Почему бы не написать просто` f'Salary list not found for department in index {department[0]}'`?

2023-10-15 19:27 UTC, KatyaGotskina commented on test_hw1.py
> +test_data_without_departments = (
Все константы в коде лучше писать капсом. Это касается всех констант в файле тестов, не только этой

2023-10-15 19:29 UTC, rTiRe commented on hw1.py
> +            raise Exception(f'Salary list not found for department in index {department_index}')
В ошибке говорится не про индекс отдела, а про индекс списка (отдел, зарплаты)

2023-10-15 19:37 UTC, KatyaGotskina commented on hw1.py
> +            raise Exception(f'Salary list not found for department in index {department_index}')
Ну так зачем? Можно просто писать про отдел

2023-10-15 19:41 UTC, rTiRe commented on hw1.py
> +            raise Exception(f'Salary list not found for department in index {department_index}')
Чтобы было понятно в каком именно месте не указан список зарплат.

2023-10-15 19:47 UTC, KatyaGotskina commented on hw1.py
> +            raise Exception(f'Salary list not found for department in index {department_index}')
Я бы предпочла получить информацию об отделе, иначе мне надо считать количество ключей с начала словаря.
Мне кажется это менее удобным

2023-10-15 20:12 UTC, KatyaGotskina commented on hw1.py
> +            raise Exception(f'Salary list not found for department in index {department[0]}')
Просто `f'Salary list not found for department {department[0]}'`

2023-10-15 20:14 UTC, KatyaGotskina commented on test_hw1.py
> +     ([100, 500, 700], 100.0),
Не заморачивайся с этим

2023-10-15 20:16 UTC, KatyaGotskina commented on test_hw1.py
> +)
Блин, оч больно и ничего не понятно

2023-10-15 20:32 UTC, rTiRe commented on test_hw1.py
> +)
Есть такое

2023-10-15 20:47 UTC, KatyaGotskina commented on test_hw1.py
> +)
Оформи еще с переносом скобок на новые строки и правильными табами

2023-10-16 06:11 UTC, KatyaGotskina approved these changes
Супер

2023-10-16 10:35 UTC, kirillsev1 approved these changes

2023-10-17 13:21 UTC, siriusdevs approved these changes

2023-10-17 13:24 UTC, merged