Litvinov
siriusdevs/homeworks_23 pull request #18
Opened 2023-10-04 17:05 UTC by EgorikA4

Альберт Андреевич разрешил написать в setup.cfg `max-line-complexity=18`.

2023-10-05 20:59 UTC, KatyaGotskina requested changes

2023-10-05 20:59 UTC, KatyaGotskina commented on hw1.py
> +from typing import List, Tuple
Как сказал бы @nazaroviktor2 : "С версии python 3.9 Dict, Tuple можно не импортировать из typing. https://peps.python.org/pep-0585/"

2023-10-05 20:59 UTC, KatyaGotskina commented on hw1.py
> +        )
Поменяй название переменных, очень сложно читать код с elem-ами, depts, args и так далее. 
Переменные должны отражать суть их содержимого и твоих действий, чтобы тебе и другим было легче понимать код

2023-10-05 20:59 UTC, KatyaGotskina commented on hw1.py
> +def dept_stat(*args: Tuple[str, List[float]], cur_dept: Tuple[str] = None) -> Tuple[List, List]:
dept_stat? :( 
Не очень хорошее название для функции

2023-10-05 20:59 UTC, KatyaGotskina commented on hw1.py
> +        raise ZeroDivisionError('Oooops, division by zero.')
что значит 'Oooops, division by zero.' для пользователя? Он никакие нули не отправлял, сидит в шоке и не понимает, что произошло

2023-10-05 21:02 UTC, siriusdevs commented on hw1.py
> +        raise ZeroDivisionError('Oooops, division by zero.')
Вклинюсь: делать raise ZeroDivisionError, если обработали появление ZeroDivisionError - какая-то лёгкая форма сумасшествия.

2023-10-07 14:52 UTC, annashutova requested changes

2023-10-07 14:52 UTC, annashutova commented on hw1.py
> +from typing import List
как уже упоминала @KatyaGotskina, List не обязательно импортировать

2023-10-07 14:52 UTC, annashutova commented on hw1.py
> +        )
смотри, ты используешь `filtered_departments_by_optional_arg`, чтобы в итоге получить `avg_salary_by_departments`, почему бы тебе сразу не находить средние зарплаты по отделам.
ты можешь идти по `departments`, проверять есть ли отдел в `specific_departments` и считать среднюю зарплату.
такой подход может в разы уменьшить кол-во итераций, особенно, если входных данных будет много

2023-10-07 14:52 UTC, annashutova commented on hw1.py
> +    return (sorted_departments_by_avg_salary[:3], sorted_departments_by_avg_salary[-3:])
может быть такой момент, что нам придет всего 2 отдела, тогда функция вернет 2 одинаковый списка, это будет не совсем правильно, в данном случае один из списков лучше вернуть пустым (обрати внимание, что списки будут неполные, если отделов < 6).
на такие случаи также стоит написать тесты

2023-10-07 14:52 UTC, annashutova commented on test_hw1.py
> +departments_names = [
все константы в коде лучше называть через капс, по типу: DEPARTMENTS_NAMES

2023-10-07 14:52 UTC, annashutova commented on hw1.py
> +    return (sorted_departments_by_avg_salary[:3], sorted_departments_by_avg_salary[-3:])
и в задании просится вернуть просто названия отделов, без их средних зарплат

> Функция должна возвращать статистику: топ-3 самых высокооплачиваемых отдела в компании и топ-3 самых низкооплачиваемых

2023-10-09 13:25 UTC, siriusdevs commented on hw1.py
> +    return (sorted_departments_by_avg_salary[:3], sorted_departments_by_avg_salary[-3:])
насчёт названий отделов всё верно.
насчёт топов - должны возвращаться одинаковые списки, если мало отделов. потому что топ-3 с конца и топ-3 с начала всё равно являются топами. даже если они повторяются

т.е. задание с 3 отделами вернёт два списка с теми же отделами

2023-10-10 06:13 UTC, KatyaGotskina requested changes

2023-10-10 06:13 UTC, KatyaGotskina commented on hw1.py
> +        return 'You have entered empty list of department salaries.'
Лучше вызывать ошибку, а не возвращать строку.
Мне сказали, что Альберт Андреевич разрешил вам использовать raise Exception('Some msg.'), поскольку вы не проходили ООП. Соответствующую ошибку flake8 можно занести в конфиг

2023-10-10 12:12 UTC, KatyaGotskina submitted a review, later dismissed
Хорошая работа !

2023-10-10 12:12 UTC, KatyaGotskina commented on hw1.py
> +        ]
здесь else не обязателен

2023-10-10 12:12 UTC, KatyaGotskina commented on hw1.py
> +    return (sorted_depts_by_avg_salary[:3], sorted_depts_by_avg_salary[-3:])
Возвращая кортеж, его можно не оборачивать в скобки

2023-10-10 16:20 UTC, KatyaGotskina approved these changes
^^

2023-10-10 21:16 UTC, annashutova requested changes
осталось совсем чуть-чуть

2023-10-10 21:16 UTC, annashutova commented on test_hw1.py
> +test_data1 = (
а как же остальные константы?

2023-10-11 10:40 UTC, KatyaGotskina commented on test_hw1.py
> +)
А почему эта `EXPECTED_DATA1` не такого же вида как следующая?
```
EXPECTED_DATA1 = (
    [
        DEPARTMENTS_NAMES[4],
        DEPARTMENTS_NAMES[3]]
)
```
```
        DEPARTMENTS_NAMES[5],
    ]

2023-10-11 10:45 UTC, KatyaGotskina commented on test_hw1.py
> +)
кстати эта константа называется `EXPECTED_DATA1`, и следующая константа тоже. Почему тогда EXPECTED_DATA именно 1?

2023-10-11 12:03 UTC, KatyaGotskina approved these changes
Cупер :)

2023-10-12 15:19 UTC, annashutova approved these changes
good job)

2023-10-13 10:55 UTC, siriusdevs approved these changes

2023-10-13 10:55 UTC, merged