Nikiforov
siriusdevs/homeworks_23 pull request #19
Opened 2023-10-04 19:27 UTC by Dimmension

2023-10-05 21:22 UTC, kirillsev1 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/906ac512-9051-483a-9dfa-4c6aac561afa)

![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/7ddde531-ea62-478f-8a5c-8fafe99501ed)

Надо исправить и написать тесты

2023-10-06 22:40 UTC, Max2288 commented on hw1.py
> +            if salary_limit is None:
можно эти 2 if совместить в 1

2023-10-07 11:49 UTC, nazaroviktor2 commented on hw1.py
> +def lowest_salaries(*args, salary_limit: float = None) -> tuple:
почему args? Тебе же приходят отделы одной компании. Назови переменную company или departments

2023-10-07 11:51 UTC, nazaroviktor2 commented on hw1.py
> +        for _, salary in staff.items():
если тебе нужны только значения словаря то используй метод .values()

2023-10-07 11:53 UTC, nazaroviktor2 commented on hw1.py
> +            total_payments += salary
limit значит что все зарплаты учитывать ну нужно. То есть если limit 0 то сумма тоже будет 0. Эту строчку нужно переместить ниже в проверку

2023-10-07 11:54 UTC, nazaroviktor2 commented on hw1.py
> +    ratio_lowest = sum(sorted(salaries)[:3]) / total_payments
когда ты первый раз сделал срез, в переменную записалось 3 значения. Не нужно делать второй раз срез

2023-10-07 11:55 UTC, nazaroviktor2 commented on hw1.py
> +    return (*salaries, round(ratio_lowest, 2))
ты не округляешь зарплаты

2023-10-07 11:56 UTC, nazaroviktor2 commented on test_hw1.py
> +test_data = [
константы лучше писать капсом

2023-10-07 11:57 UTC, nazaroviktor2 requested changes
Молодец, но нужно немного поправить

2023-10-08 21:24 UTC, Dimmension commented
Ща погоди, не проверяй этот коммит, увидел новые комментарии когда запушил

2023-10-14 14:38 UTC, nazaroviktor2 commented on hw1.py
> +# Все числа в выводе функции округлять до второго знака после запятой.
Это просто лайк

2023-10-14 14:41 UTC, nazaroviktor2 commented on hw1.py
> +            total_payments += salary
Смотри, у тебя есть параметр лимит - числовой предел, выше которого зарплаты учитывать не нужно. Но в этой строчке ты учитываешь это заплату в сумму всех. Тебе надо перенести эту строчку в проверку

2023-10-14 14:44 UTC, nazaroviktor2 commented on hw1.py
> +    return *lowest_salaries, f'{ratio_lowest_salaries}%'
Зачем тут распаковка? У тебя же функция возвращает  tuple[list[float], str]

2023-10-14 14:44 UTC, nazaroviktor2 requested changes
Надо поправить

2023-10-15 11:04 UTC, nazaroviktor2 commented
Посмотри вот [этот](https://github.com/siriusdevs/homeworks_23/pull/19#discussion_r1359430862) коммент

2023-10-15 15:47 UTC, Dimmension commented
поправил @nazaroviktor2

2023-10-15 15:51 UTC, nazaroviktor2 commented on hw1.py
> +            if salary_limit is None or salary < salary_limit:
тут наверное <=

2023-10-15 15:52 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/c24ad280-1070-47c6-9fbb-e882cf87bb57)

2023-10-15 15:55 UTC, Dimmension commented
тебя тегать можно?

2023-10-16 10:37 UTC, kirillsev1 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/5979b97d-7f9b-45d9-8d96-625c4cb3d522)
Надо линтер исправить

2023-10-16 10:40 UTC, kirillsev1 requested changes

2023-10-16 12:56 UTC, kirillsev1 approved these changes

2023-10-16 13:42 UTC, nazaroviktor2 commented on hw1.py
> +            if salary_limit is None or salary < salary_limit:
@Dimmension 
"Этот аргумент - числовой предел, выше которого зарплаты учитывать не нужно." -> <=

2023-10-16 13:44 UTC, nazaroviktor2 commented on hw1.py
> +        for salary in department[1].values():
можно написать вот так 
```
    for _, employees in company:
        for salary in employees.values():
```

2023-10-16 13:45 UTC, nazaroviktor2 requested changes
пару замечаний

2023-10-16 16:43 UTC, nazaroviktor2 approved these changes
Молодец

2023-10-18 10:53 UTC, kirillsev1 approved these changes

2023-10-18 11:40 UTC, merged