First hw done
siriusdevs/homeworks_23 pull request #2
Opened 2023-09-29 16:33 UTC by spl3g

2023-09-29 16:48 UTC, Max2288 commented on hw_one.py
> +def salary_stats(company: Dict[str, Dict[str, float]], ceiling: float = None) -> Tuple:
Какой версией питона пользуешься, с 3.10 можно использовать просто tuple, не импортирвоать из typing

2023-09-29 16:55 UTC, Max2288 commented
Название файлов неверное, необоходимо hw1 и тд

2023-09-29 17:01 UTC, spl3g commented
Если называть по шаблону `hw_<#>.py` (как написано в readme), то флейк жалуется:
```shell
hw_1.py:0:1: WPS114 Found underscored number name pattern: hw_1
```

2023-09-29 17:06 UTC, Max2288 commented on hw_one.py
> +    return (top, round(sum(top) / all_sal * 100, 2))
А что будет, если all_sal 0?

2023-09-29 17:06 UTC, Max2288 commented on test_hw_one.py
> +from typing import Dict, List, Tuple
List, Tuple - аналогично тому, что писал выше про питон 3.10

2023-09-29 17:07 UTC, Max2288 commented on test_hw_one.py
> +the_company = (
Название тестовых переменных, которые делаешь не изменяемыми, например для parametrize лучше делать константами например THE_COMPANY_TEST_DATA

2023-09-29 17:13 UTC, Max2288 commented on hw_one.py
> +        Tuple[list[float], float] - top 3 salaries and the ratio
Почему в докстринге указано, что возвращается Tuple[list[float], float], а в тайпхинте просто Tuple?

2023-09-29 17:17 UTC, siriusdevs commented
> Если называть по шаблону `hw_<#>.py` (как написано в readme), то флейк жалуется:
> 
> ```shell
> hw_1.py:0:1: WPS114 Found underscored number name pattern: hw_1
> ```

делайте hw1.py, просто без андерскора. это я в ридми ошибся, сейчас исправлю.

2023-09-29 17:17 UTC, Max2288 commented
> Если называть по шаблону `hw_<#>.py` (как написано в readme), то флейк жалуется:
> 
> ```shell
> hw_1.py:0:1: WPS114 Found underscored number name pattern: hw_1
> ```

должно быть просто hw, без андерскора, это в ридми ошибка сейчас исправят

2023-09-29 17:28 UTC, nazaroviktor2 commented on hw_one.py
> +    top = sal[:3]
Смотри в задаче надо вывести только топ 3 зарплаты.  Ты идешь по всем компаниям, по всем людям и сохраняешь их в массив, потом метод sort снова пойдет по всему этому массиву, чтобы его отсортировать, а потом еще раз ты вызываешь сумму для массива, которая снова пойдет по всему массиву. Получается достаточно высокая сложность для этой задачи. Можно считать сумму всех заплат сразу в цикле, это не ухудшит читаемость. Но если прям хорошо написать, то можно считать  и топ 3  сразу в цикле.

2023-10-01 06:56 UTC, nazaroviktor2 requested changes

2023-10-01 12:05 UTC, nazaroviktor2 commented on hw1.py
> +        str - if your company is shady.
Забыл обновить докстринги

2023-10-01 12:07 UTC, nazaroviktor2 commented on hw1.py
> +    return top
return top, 100
Вывод должен быть единообразным

2023-10-01 12:11 UTC, nazaroviktor2 submitted a review, later dismissed
Осталось только поправить достринги и все будет ок, молодец

2023-10-01 20:15 UTC, Max2288 commented on hw1.py
> +) -> tuple[list[float], float] | str:
Как возвращает строку, если он её не возвращает никогда?

2023-10-01 20:16 UTC, Max2288 commented on test_hw1.py
> +    expected: tuple[list, float] | str,
Аналогично

2023-10-02 18:22 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/ea5b939c-a847-4843-9176-7ec4b0d40c33)

2023-10-03 14:11 UTC, annashutova approved these changes
молодец, хорошо справился с заданием

2023-10-03 14:11 UTC, annashutova commented on hw1.py
> +    top = all_salaries[:3]
молодец, что подметил вероятность того, что результирующий топ может быть меньше 3, в данном случае это было делать не обязательно, если индексы среза выходят за пределы списка, ошибки никакой не возникнет и он просто вернет весь список, что есть
это просто на будущее, чтобы ты знал))
![image](https://github.com/siriusdevs/homeworks_23/assets/113082839/420e67b7-690e-491b-8579-14200339479b)

2023-10-06 07:35 UTC, merged