Zagora
siriusdevs/homeworks_23 pull request #24
Opened 2023-10-06 10:24 UTC by nnnhurt

2023-10-06 22:35 UTC, Max2288 commented on main.py
> +        average_salary = sum(employees[employee].values()) / len(employee)
а если len = 0?

2023-10-06 22:49 UTC, Max2288 commented
у тебя неверно называются файлы, должно быть hw1 и тп, в  ридми всё указано

2023-10-07 12:55 UTC, nazaroviktor2 commented on test_hw1.py
> +test_cases = (
константы лучше писать капсом

2023-10-07 12:58 UTC, nazaroviktor2 commented on setup.cfg
> +        # allowed error
multi-line parameters

2023-10-07 13:00 UTC, nazaroviktor2 commented on hw1.py
> +        employees: dict[str, int] - dict of department names and values.
приходит такой формат
` {"Название отдела: {"Имя сотрудника": зарплата  } ` 
dict[str,dict[

2023-10-07 13:03 UTC, nazaroviktor2 commented on hw1.py
> +        all_salary = sum(employees[employee].values())
чтобы не писать` employees[employee] ` можно идти по значениям `for employee in departments.value()`

2023-10-07 13:04 UTC, nazaroviktor2 commented on hw1.py
> +        if min_salary is None or min_salary <= average_salary:
проверка должна быть выше. Перед подсчетом суммы всех зп. Так в сумму могут попасть зп которые не нужны учитывать

2023-10-07 13:05 UTC, nazaroviktor2 commented on hw1.py
> +    return min_max_department[:3], min_max_department[-3:]
нет округления

2023-10-07 13:05 UTC, nazaroviktor2 requested changes
Поправь названия, очень тяжело читать

2023-10-07 14:21 UTC, nnnhurt commented on hw1.py
> +    return min_max_department[:3], min_max_department[-3:]
мне нужно выводить названия отделов. в тексте, в задании было ошибочно добавлено это условие, это обсуждалось с Альбертом Андреевичем.

2023-10-08 10:43 UTC, nazaroviktor2 commented on hw1.py
> +            dept_salaries = [salary for salary in dept_salaries.values() if salary > min_salary]
Тут наверное >= 
Но это не точно

2023-10-08 10:48 UTC, nnnhurt commented on hw1.py
> +            dept_salaries = [salary for salary in dept_salaries.values() if salary > min_salary]
прошу прощения, когда изменяла там, забфла упомянуть, исправлю

2023-10-08 10:50 UTC, nazaroviktor2 commented on hw1.py
> +def company_departament(departments: dict, min_salary: float | None = None) -> tuple[list]:
я бы еще дополнил аннотацию `departments: dict[str, dict] `

2023-10-08 10:50 UTC, nazaroviktor2 approved these changes
Молодец 
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/fdca10e7-d5e9-47cb-8631-ca75b8e8c0ca)

2023-10-08 11:04 UTC, nazaroviktor2 submitted a review, later dismissed
Хорошая работа, так держать ! 
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/cd894deb-7094-4c93-b8db-23bf0e47e535)

2023-10-09 11:25 UTC, KatyaGotskina requested changes

2023-10-09 11:25 UTC, KatyaGotskina commented on hw1.py
> +        if min_salary:
Если min_salary типа NoneType, то dept_salaries - словарь, в ином случае dept_salaries список.
sum у словаря вызвать нельзя (в данном случае), поэтому программа падает с ошибкой

2023-10-09 11:25 UTC, KatyaGotskina commented on test_hw1.py
> +)
Много данных, но мало тестов. Не рассмотрены случаи, когда min_salary = None

2023-10-09 11:31 UTC, KatyaGotskina requested changes

2023-10-09 11:31 UTC, KatyaGotskina commented on hw1.py
> +    return min_max_department[:3], min_max_department[-3:]
Передала в функцию min_salary, которая была больше любой из зарплат. Мне неожиданно вернулись какие то данные :О

2023-10-10 06:30 UTC, nnnhurt commented on test_hw1.py
> +)
к сожалению, по заданию дано, что ответ должен состоять конкретно из 6 отделов, спрашивала у Альберта Андреевича, поэтому  много данных и мало тестов. Мне позволили оставить так. Но ситуацию с min_salary = None добавлю.

2023-10-10 06:48 UTC, KatyaGotskina commented on test_hw1.py
> +)
Посмотри обсуждение с https://github.com/siriusdevs/homeworks_23/pull/18#discussion_r1350307304. 
В функцию может придти меньше 6 отделов, по крайней мере, твои одногруппники делают решение с учетом этого.
То есть входные данные могут быть самыми разнообразными

2023-10-10 16:46 UTC, nnnhurt commented on hw1.py
> +    return min_max_department[:3], min_max_department[-3:]
Какие-то данные - это ожидаемый результат. А если конкретно, нам подается кортеж и выдается кортеж. Скорее всего некие данные, которые тебе выдались - это о том, что ожидаемый ответ не сошелся с выданным, как раз таки, потому что ты ввела min_salary больше, тем самым изменила ожидаемый результат, который не сопоставился с заданным ожидаемым результатом.

2023-10-13 10:30 UTC, KatyaGotskina requested changes

2023-10-13 10:30 UTC, KatyaGotskina commented on hw1.py
> +        list[str] - array for highest and lowest salaries.
У тебя ведь возвращается кортеж со списками, а не список

2023-10-13 10:30 UTC, KatyaGotskina commented on hw1.py
> +    return min_max_department[:3], min_max_department[-3:]
`company_departament({'first_departament' : {}})` возвращает `(['first_departament'], ['first_departament'])`, хотя это должно являться ошибкой, никаких зарплат в этой компании нет. Либо возвращай пользователю ошибку ввода данных, либо не учитывай департаменты без сотрудников

2023-10-13 10:30 UTC, KatyaGotskina commented on test_hw1.py
> +                'Dima': 90560.53,
Где тесты без использования аргумента min_salary?

2023-10-14 15:17 UTC, nazaroviktor2 submitted a review, later dismissed

2023-10-15 19:36 UTC, KatyaGotskina requested changes

2023-10-15 19:36 UTC, KatyaGotskina commented on hw1.py
> +        tuple[list] - array for highest and lowest salaries.
**tuple**[list] - **array** for highest and lowest salaries.
Будь повнимательнее, тогда мр-ы будут приниматься быстрее

2023-10-15 19:36 UTC, KatyaGotskina commented on test_hw1.py
> +        {}, None, ([], []),
None передавать плохая практика, так делать не надо. Можно написать отдельные тесты без использования min_salary c валидными остальными данными

2023-10-15 19:36 UTC, KatyaGotskina commented on test_hw1.py
> +        min_salary: float | None = None.
Не понятно, можно ведь просто скопировать из прошлого описания, а то ты вообще объяснения не даешь

2023-10-16 07:19 UTC, nnnhurt commented on hw1.py
> +        tuple[list] - array for highest and lowest salaries.
а в чем ошибка, я не понимаю. и причем здесь мр-ы.

2023-10-16 07:29 UTC, KatyaGotskina commented on hw1.py
> +        tuple[list] - array for highest and lowest salaries.
Ты изменила **list** на **tuple**, при этом описание не поменяла: у тебя `tuple[list]` - **массив** с самой высокой и самой низкой зарплатами, а должен быть кортеж  с самой высокой и самой низкой зарплатами.

Когда ты закрывала https://github.com/siriusdevs/homeworks_23/pull/24#discussion_r1358078823, можно было поменять сразу все, тогда бы мне не пришлось задерживать ревью и писать это 2 раза

2023-10-16 20:35 UTC, KatyaGotskina approved these changes

2023-10-17 09:56 UTC, nazaroviktor2 commented on hw1.py
> +def company_departament(departments: [str, dict], min_salary: float | None = None) -> tuple[list]:
`departments: dict[str, dict]`
`-> tuple[list, list]:`

2023-10-17 09:58 UTC, nazaroviktor2 commented on hw1.py
> +            dept_salaries = list(dept_salaries.values())
.values() и так возвращает list, не нужно еще раз оборачивать

2023-10-17 09:59 UTC, nazaroviktor2 requested changes
пару замечаний

2023-10-17 13:29 UTC, siriusdevs commented on hw1.py
> +            dept_salaries = list(dept_salaries.values())
@nazaroviktor2 
values() не возвращает list, values() возвращает <class dict_values>. так что всё правильно, возвращайте аппрув :)

2023-10-17 14:59 UTC, nazaroviktor2 commented on hw1.py
> +    for department, dept_salaries in departments.items():
Почему переменная называется dept_salaries? В ней же хранятся сотрудники. Почему не назвать employees?

2023-10-17 15:08 UTC, nazaroviktor2 commented on hw1.py
> +    Extract minimum and maxsimun three salaries.
*maxsimum

2023-10-17 15:15 UTC, nazaroviktor2 commented on hw1.py
> +    return min_max_department[:3], min_max_department[-3:]
Ты выводишь топ низкооплачиваемых с самого низкого оплачиваемого. Почему ты не выводишь топ самых высоко оплачиваемых с самого высоко оплачиваемого отедла?

2023-10-17 15:21 UTC, nnnhurt commented on hw1.py
> +            continue
потому что Екатерина сделала замечание по этому поводу и попросила добавить данную проверку.

2023-10-18 07:09 UTC, nazaroviktor2 commented on hw1.py
> +            employees = [salary for salary in employees.values() if salary >= min_salary]
`for salary in employees` если это заплаты, почему тут переменная называется employees?

2023-10-18 07:09 UTC, nazaroviktor2 commented on hw1.py
> +    departments: [str, dict],
` departments: dict[str, dict],`

2023-10-18 07:11 UTC, nazaroviktor2 requested changes
Еще пару моментов

2023-10-18 07:27 UTC, nazaroviktor2 approved these changes
Молодец!

2023-10-19 13:40 UTC, merged