Telegin
siriusdevs/homeworks_23 pull request #29
Opened 2023-10-08 17:21 UTC by TeleginSergey

1st try

2023-10-08 18:21 UTC, nazaroviktor2 commented on hw1.py
> +def best_wage(departments: list, exclude_deps: tuple = None) -> list[float | int, str]:
Не хватает полной аннотации. list[tuple]   tuple [str...]

2023-10-08 18:27 UTC, nazaroviktor2 commented on hw1.py
> +    for dep in departments:
почему dep? department

2023-10-08 18:27 UTC, nazaroviktor2 commented on hw1.py
> +        for _, salary in dep[1].items():
если тебе не нужны ключи то есть метод .values()

2023-10-08 18:28 UTC, nazaroviktor2 commented on hw1.py
> +            if exclude_deps is None or dep[0] not in exclude_deps:
На будущие. так как это у тебя exclude_deps это typle то if dep not in exclude_deps: - каждый раз будет выполнятся за O(n). Но если бы exclude_deps - set то это проверка занимала бы O(1) - разница очень большая. Поэтому ты можешь в перед циклом сделать set(ignored_depts), что очень сильно ускорит твою программу

2023-10-08 18:41 UTC, nazaroviktor2 commented on hw1.py
> +            total_payments += [salary]
а если этот отдел не нужно считать? Это строку надо перенести к проверке

2023-10-08 18:44 UTC, nazaroviktor2 commented on hw1.py
> +        return ['Недостаточно не исключенных отделов для использования функции']
Зачем это? почему просто не возвращать список из 0, 1, 2 элементов?

2023-10-08 18:45 UTC, annashutova requested changes

2023-10-08 18:45 UTC, annashutova commented on hw1.py
> +def best_wage(departments: list, exclude_deps: tuple = None) -> list[float | int, str]:
в задании написано:
> Напишите функцию, которая принимает любое количество позиционных аргументов

у тебя же функция принимает только один позиционный аргумент

2023-10-08 18:45 UTC, annashutova commented on hw1.py
> +                permitted_wages += [salary]
так конечно тоже можно, но для добавления в список есть специальный метод `append`

2023-10-08 18:45 UTC, annashutova commented on hw1.py
> +        return ['Недостаточно данных для использования функции']
возвращать список с одной строкой в данном случае не лучшая идея, лучше будет сделать raise ошибки с данным сообщением

2023-10-08 18:46 UTC, nazaroviktor2 commented on hw1.py
> +    return permitted_wages
Плохое поведение. Лучше возвращай ` return permitted_wages,  percent_best_salary ` так ты всегда будешь знать, что второй элемент это проценты

2023-10-08 18:46 UTC, nazaroviktor2 commented on test_hw1.py
> +test_data = (
константы лучше писать капсом

2023-10-08 18:48 UTC, nazaroviktor2 commented on hw1.py
> +        return ['Недостаточно данных для использования функции']
Плохое поведение. Тут надо либо raise костюмной ошибки или возвращать `return [], 100`

2023-10-08 18:49 UTC, nazaroviktor2 requested changes
Молодец, но надо немного поправить

2023-10-10 20:44 UTC, TeleginSergey commented on hw1.py
> +            total_payments += [salary]
Сначала я так и написал, однако я подумал, что нужно посчитать процент ко всему размеру выплат компании. Следовательно, как я понял, ко всей сумме и исключенных и не исключенных отделов

2023-10-10 22:46 UTC, TeleginSergey commented on hw1.py
> +            if exclude_deps is None or dep[0] not in exclude_deps:
Согласен, однако если exclude_deps будет состоять из одной строки, то set() разберет его на буквы и в разрешенные отделы(permitted_wages) добавиться тот самый единственный в exlude_deps отдел.

2023-10-11 20:23 UTC, closed without merging