Коренякин А.
siriusdevs/homeworks_23 pull request #30
Opened 2023-10-09 10:49 UTC by Raitman17

2023-10-10 12:38 UTC, KatyaGotskina requested changes

2023-10-10 12:38 UTC, KatyaGotskina commented on hm1.py
> +            исключить из статистики. По умолчанию None.
Хотелось бы увидеть тип данных, которые содержит exclude_department в аннотации переменной

2023-10-10 12:38 UTC, KatyaGotskina commented on hm1.py
> +            а зарплаты значение(float).
По такому описанию получается, что department - это словарь вида {'some_last_name' : 1000}, 
а не {'name_of_dep' : {'some_last_name' : 1000}}

2023-10-10 12:38 UTC, KatyaGotskina commented on hm1.py
> +        и топ-3 самых низкооплачиваемых.
Ты же возвращаешь не список, а кортеж, содержащий два списка

2023-10-10 12:38 UTC, KatyaGotskina commented on hm1.py
> +            if len_dep > 0:
В отделе компании может не быть сотрудников? 
Или это ошибка неверных данных со стороны пользователя, и ему стоит сообщить об этом? 
Лучше используй raise Exception('Some msg')

2023-10-10 12:38 UTC, KatyaGotskina commented on hm1.py
> +    average_salaries = sorted(average_salaries, key=lambda depart: depart[1])
Почему не average_salaries.sort(...)?

2023-10-12 07:11 UTC, Raitman17 commented on hm1.py
> +            if len_dep > 0:
С raise Exception ругался flake8

2023-10-13 10:01 UTC, KatyaGotskina commented on hm1.py
> +            if len_dep > 0:
Альберт Андреевич разрешил вам заносить эту ошибку в конфиг

2023-10-13 10:10 UTC, KatyaGotskina requested changes

2023-10-13 10:10 UTC, KatyaGotskina commented on hm1.py
> +    return (top_dep, worst_dep)
Возвращая кортеж, его можно не оборачивать в скобки

2023-10-13 10:10 UTC, KatyaGotskina commented on test_hm1.py
> +test_data = (
Все константы в коде лучше писать капсом. Это касается всех констант в тестах

2023-10-13 10:10 UTC, KatyaGotskina commented on test_hm1.py
> +            },
Мне кажется, не стоит exclude_department передавать со всеми остальными **kwargs 
Что скажешь @nazaroviktor2 @annashutova?

2023-10-13 10:45 UTC, annashutova requested changes

2023-10-13 10:45 UTC, annashutova commented on test_hm1.py
> +            },
Думаю, так можно сделать, учитывая то, что иначе для случаев, когда параметр `exclude_department` отсутствует, пришлось бы писать отдельные тесты. А так, ту все комплексно проверяется

2023-10-13 10:45 UTC, annashutova commented on test_hm1.py
> +    assert salary_statistics(**args) == expected
учитывая то, что ты args распаковываешь как словарь, лучше передаваемые параметры назвать kwargs.
`args` принято называть позиционные аргументы, `kwargs` - ключевые, и у тебя тут как раз ключевые передаются

2023-10-13 10:45 UTC, annashutova commented on hm1.py
> +                raise ZeroDivisionError(f'В отделе {dep} нету сотрудников!')
эту проверку лучше вынести за предыдущее условие, так можно избежать такой вложенности

2023-10-14 10:00 UTC, KatyaGotskina requested changes
Еще чуть-чуть поправить

2023-10-15 19:41 UTC, KatyaGotskina commented on hm1.py
> +        Exception: выдает ошибку, когда в отделе нет сотрудников.
В общем то понятно, что код выдает ошибку, если ты описываешь Raises Exception

2023-10-16 13:08 UTC, KatyaGotskina approved these changes

2023-10-18 19:11 UTC, annashutova approved these changes

2023-10-19 07:30 UTC, merged