Completed task
siriusdevs/homeworks_23 pull request #31
Opened 2023-10-10 11:45 UTC by Dmitry-228

2023-10-10 14:46 UTC, KatyaGotskina requested changes

2023-10-10 14:46 UTC, KatyaGotskina commented on hw1.py
> +        excluded_departments: tuple[str] or None is default.
Как приятно видеть такие аннотации к переменным, спасибо тебе ^^
Насчет названия переменной как args посмотри https://github.com/siriusdevs/homeworks_23/pull/13#discussion_r1342583467

2023-10-10 14:46 UTC, KatyaGotskina commented on hw1.py
> +        all_salaries.extend(salaries.values())
Зачем создавать отдельную переменную `department_salaries` и выполнять лишний цикл, если проверку `if excluded_departments is None or department not in excluded_departments` можно проводить внутри основного цикла? 
Типо 
```
for department, salary in args:
    if excluded_departments is None or department not in excluded_departments:
        all_salaries.extend(list(salary.values()))
```

2023-10-10 14:46 UTC, KatyaGotskina commented on hw1.py
> +        all_salaries.extend(salaries.values())
Зачем создавать отдельную переменную `department_salaries` и выполнять лишний цикл, если проверку `if excluded_departments is None or department not in excluded_departments` можно проводить внутри основного цикла? 
Типо 
```
for department, salary in args:
    if excluded_departments is None or department not in excluded_departments:
        all_salaries.extend(list(salary.values()))
```

2023-10-10 14:46 UTC, KatyaGotskina commented on hw1.py
> +    ratio = round((sum(sorted_salaries) / sum(all_salaries)) * 100, 2)
А если `sum(all_salaries)` равна 0?

2023-10-10 14:46 UTC, KatyaGotskina commented on test_hw1.py
> +        ([60000.0, 58000.0, 55000.0], 100.0),
Посмотри https://github.com/siriusdevs/homeworks_23/pull/13#discussion_r1349513277

2023-10-10 14:46 UTC, KatyaGotskina commented on test_hw1.py
> +test_company_data = (
Посмотри https://github.com/siriusdevs/homeworks_23/pull/18#discussion_r1349530641

2023-10-10 14:46 UTC, KatyaGotskina commented on test_hw1.py
> +test_company_data = (
Посмотри https://github.com/siriusdevs/homeworks_23/pull/18#discussion_r1349530641

2023-10-10 14:49 UTC, Dmitry-228 commented on hw1.py
> +        all_salaries.extend(salaries.values())
Спасибо за совет

2023-10-10 15:03 UTC, Dmitry-228 commented on test_hw1.py
> +        ([60000.0, 58000.0, 55000.0], 100.0),
Так у меня есть тесты где я передаю не "None" или я неправильно понял, что надо добавить?

2023-10-10 15:47 UTC, KatyaGotskina commented on hw1.py
> +    return list(sorted_salaries), 100
Почему 100%? А если `sorted_salaries` / `all_salaries` пустые списки?

2023-10-10 17:24 UTC, KatyaGotskina commented on hw1.py
> +        ratio = round((sum(sorted_salaries) / sum(all_salaries)) * 100, 2)
`sum(all_salaries)` выполняется за O(n), лучше вынести ее в отдельную переменную, чтобы было не так много итераций (n вместо n * 3, поскольку сумма посчитается всего один раз)

2023-10-14 15:26 UTC, nazaroviktor2 commented on hw1.py
> +        if excluded_departments is None or department not in excluded_departments:
На будущие. так как это у тебя excluded_departments это кортеж то if  department not in excluded_departments: каждый раз будет выполнятся за O(n). Но если бы excluded_departments - set то это проверка занимала бы O(1) - разница очень большая. Поэтому ты можешь в перед циклом сделать set(excluded_departments), что очень сильно ускорит твою программу

2023-10-14 15:30 UTC, nazaroviktor2 commented on hw1.py
> +            all_salaries.extend(list(salary.values()))
нужно ли тут приведение к списку? .values() - возвращает список
Потом можно просто 
` all_salaries += salary.values()`

2023-10-14 15:30 UTC, nazaroviktor2 requested changes
нужно не большие изменения

2023-10-18 11:08 UTC, kirillsev1 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/566c6019-abfc-4255-a9af-4c028f72ea98)

workflows не работает

2023-10-23 10:24 UTC, KatyaGotskina commented
Что поменялось относительно https://github.com/siriusdevs/homeworks_23/pull/31#discussion_r1352786360? 
Большая просьба еще раз просматривать незакрытые обсуждения перед повторным запросом ревью или их хоть как то их комментировать. Все исправленные пункты мы с ребятами закрываем

2023-10-30 12:15 UTC, KatyaGotskina commented
Ты добавил еще один тест-кейс для данных без `excluded_departments`, теперь из первого тест-кейса с использованием `excluded_departments` нужно убрать `None` и `[]`, поскольку он предназначен для тестирования данных с использованием ненулевого фильтра

2023-10-30 12:17 UTC, KatyaGotskina requested changes

2023-10-30 12:17 UTC, KatyaGotskina commented on test_hw1.py
> +        ([0, 0, 0], 0),
Говорю про этот момент: строки 12, 19 и 26

2023-10-30 12:18 UTC, KatyaGotskina commented
Поменяешь этот момент, и к тебе вопросов больше нет :)

2023-10-31 07:55 UTC, KatyaGotskina approved these changes

2023-10-31 11:33 UTC, nazaroviktor2 requested changes

2023-10-31 11:33 UTC, nazaroviktor2 commented on hw1.py
> +    excluded_departments: tuple[str] | None,
tuple[str] - эта не правильная аннотация. Сейчас у тебя написано, что есть кортеж из одной строки
Правильная аннотация `tuple[str, ...]` троеточие значит, что все элементы будут одинаковые

2023-10-31 11:34 UTC, nazaroviktor2 commented on hw1.py
> +    excluded_departments: tuple[str] | None,
excluded_departments: tuple[str]=None,

2023-10-31 11:45 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/9588f5cb-f36f-49a7-b7b5-2641af92e9d7)

2023-10-31 11:46 UTC, KatyaGotskina approved these changes

2023-11-01 11:47 UTC, siriusdevs approved these changes

2023-11-01 11:49 UTC, merged