Nudga
siriusdevs/homeworks_23 pull request #33
Opened 2023-10-11 14:17 UTC by Rubsun

2023-10-14 15:32 UTC, nazaroviktor2 commented on hw1.py
> +from typing import Optional, Tuple
С версии python 3.9 Dict, Tuple можно не импортировать из typing. https://peps.python.org/pep-0585/

2023-10-14 15:33 UTC, nazaroviktor2 commented on test_hw1.py
> +test = (
Константы лучше писать капсом

2023-10-14 15:36 UTC, nazaroviktor2 commented on hw1.py
> +def sort_dep(*args: Tuple[str, int], limit: Optional[int] = None) -> Tuple[str]:
Почему args? Нужно писать переменные, которые как можно точнее отражают информацию в ней. К тебе же приходит кортеж из отделов одной компании. Почему не назвать переменную company или departments?

2023-10-14 15:37 UTC, nazaroviktor2 commented on hw1.py
> +def sort_dep(*args: Tuple[str, int], limit: Optional[int] = None) -> Tuple[str]:
почему limit int ? Почему не float

2023-10-14 15:38 UTC, nazaroviktor2 commented on hw1.py
> +        Return Tuple[str]
тут обычно пишет что именно возвращается. Топ -3 высоко и низко оплачиваемых отдела

2023-10-14 15:42 UTC, nazaroviktor2 commented on hw1.py
> +    ]
А если я отделу ничего не плачу, разве это не самый низко оплачиваемый отдел?

2023-10-14 15:48 UTC, nazaroviktor2 commented on test_hw1.py
> +                (['dep5', 'dep7', 'dep4'], ['dep3', 'dep6', 'dep1'])
'dep3', 'dep6', 'dep1' почему порядок такой? Мне кажется тут первым должен идти dep1 так как он самый низкооплачиваемый

2023-10-14 15:48 UTC, nazaroviktor2 requested changes
Нужно не много поменять

2023-10-14 17:42 UTC, Rubsun commented on hw1.py
> +    ]
По моему мнению, если вы полностью не оплачиваете отдел , то он не считается оплачиваемым, и его можно не учитывать ¯\_(ツ)_/¯ .

2023-10-14 18:04 UTC, nazaroviktor2 commented on hw1.py
> +    ]
Ну ладно. Тогда можно вынести эту проверка в фильтр выше

2023-10-14 20:17 UTC, nazaroviktor2 commented on hw1.py
> +def sort_dep(*args: Tuple[str, int], limit: Optional[int] = None) -> Tuple[str]:
departments это tuple[str, list[int|float]]

2023-10-14 20:19 UTC, nazaroviktor2 commented on hw1.py
> +def sort_dep(*args: Tuple[str, int], limit: Optional[int] = None) -> Tuple[str]:
Когда ты пишешь `-> tuple[str]` значит возвращается кортеж из одной строки. Правильно будет написать
 `-> tuple[str, str]`

2023-10-14 20:20 UTC, nazaroviktor2 requested changes
еще пару замечаний

2023-10-15 12:09 UTC, nazaroviktor2 commented on hw1.py
> +        for dept, _ in filtered_dep[-1:-4:-1]
`filtered_dep[:-4:-1]`

2023-10-15 12:09 UTC, nazaroviktor2 commented on hw1.py
> +def sort_dep(*departments: tuple[str, list[int|float]] , limit: Optional[float] = None) -> tuple[str, str]:
` -> tuple[list[str], list[str]]:`

2023-10-15 12:11 UTC, nazaroviktor2 commented on hw1.py
> +        return (), ()
Тут возвращаешь кортеж из двух кортежей, а ниже кортеж из двух списков. Тут тоже возвращай пустые списки

2023-10-15 12:28 UTC, nazaroviktor2 commented on hw1.py
> +            if any(salary >= limit for salary in salaries)
20 и 22 строчка же делают одно и тоже?

2023-10-15 12:32 UTC, nazaroviktor2 requested changes
когда пустой список ошибка
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/74a2d64f-ae09-4a40-b1d9-7f8f59da56cb)

2023-10-16 11:34 UTC, nazaroviktor2 commented on hw1.py
> +        for department, _ in filtered_dep[:-4:-1]
у тебя же правильно было
[-1:-4:-1]

2023-10-16 11:34 UTC, nazaroviktor2 commented on hw1.py
> +) -> tuple[str, str]:
tuple[list[str], list[str]]

2023-10-16 11:36 UTC, nazaroviktor2 requested changes
еще чуть чуть

2023-10-16 12:23 UTC, nazaroviktor2 commented on hw1.py
> +        Return tuple[str, str] - Top 3 high-paying and low-paying departments.
Здесь не поменял

2023-10-16 12:23 UTC, nazaroviktor2 requested changes
final fix?)

2023-10-16 13:29 UTC, nazaroviktor2 commented on hw1.py
> +def sort_dep(
sort_dep ? Функция же не сортирует, а ищет высоко и низко оплачиваемые отделы

2023-10-16 13:29 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/cb83c08e-5d7b-41c4-a566-82c5e198bb47)

2023-10-16 13:40 UTC, nazaroviktor2 approved these changes

2023-10-18 14:14 UTC, kirillsev1 commented on hw1.py
> +        Return tuple[str, str] - Top 3 high-paying and low-paying departments.
Внутри returns не надо писать еще раз return

2023-10-18 17:30 UTC, nazaroviktor2 approved these changes

2023-10-19 09:14 UTC, merged