Telegin
siriusdevs/homeworks_23 pull request #37
Opened 2023-10-14 17:17 UTC by TeleginSergey

3st try. Учел предыдущие ошибки, исправил flake8. Правда не очень хотел, так как, по моему мнению, выглядит менее читабельно.

2023-10-14 20:55 UTC, nazaroviktor2 commented on hw1.py
> +        return ([], 0)
А зачем рейзить ошибку, чтобы тут же ее обработать? Можно же сразу делать return

2023-10-14 20:58 UTC, nazaroviktor2 commented on hw1.py
> +    for department in departments:
можно сделать 
`for department, salaries in departments:`

2023-10-14 21:01 UTC, nazaroviktor2 commented on hw1.py
> +            total_salary += salary
" кортеж названий отделов, которые нужно исключить из статистики "
если отдел нужно исключить из статистики, то почему ты его включаешь ?

2023-10-14 21:10 UTC, nazaroviktor2 commented on hw1.py
> +            if exclude_deps is None or department[0] not in exclude_deps:
Про set я писал, ты не проверяя ответил 
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/4f5b12bb-ee90-4372-a8d1-0cb3904211a6)

У меня было много времени и стало интересно, как это python проверяет, что пришел массив из одного элемента, а еще и проверяет на строку. Какая то не явная логика и я решил проверить так ли это на само деле 
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/5125b8c9-6d70-434b-909c-4777131085e1)

оказалось что нет ))))

2023-10-14 21:10 UTC, nazaroviktor2 requested changes
Надо поправить

2023-10-14 21:11 UTC, nazaroviktor2 commented
Пожалуйста, не закрывай мержи. В чем смысл?

2023-10-15 11:54 UTC, Rubsun commented on hw1.py
> +            if exclude_deps is None or department[0] not in exclude_deps:
![konor](https://github.com/siriusdevs/homeworks_23/assets/74344870/4ab2b5fa-8ddd-42d0-9eb0-e19208cb2e84)

2023-10-15 12:40 UTC, TeleginSergey commented on hw1.py
> +            if exclude_deps is None or department[0] not in exclude_deps:
а у меня exclude_deps передается как кортеж, а не список, поэтому и разделяется на буквы(если 1 строка внутри). Если же список, то да, он разделяет по элементам.

2023-10-15 12:43 UTC, TeleginSergey commented on hw1.py
> +            total_salary += salary
Ну просто не вижу смысла тогда вообще их иметь в функции, так как пользователь их может и самостоятельно убрать. А вот если их считать, то функция будет как по мне более полезной. Также в задании написано отношение в процентах к общим выплатам компании, соответственно, исключенные отделы также следует считать.

2023-10-15 12:49 UTC, TeleginSergey commented on hw1.py
> +    for department in departments:
Не совсем понял, у меня в функции departments - это кортеж из всех позиционных аргументов. Аргументы в виде tuple[str, dict]

2023-10-15 13:07 UTC, nazaroviktor2 commented on hw1.py
> +            if exclude_deps is None or department[0] not in exclude_deps:
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/904f0602-9fe1-4168-b7a8-f94f9bdc87de)

2023-10-15 13:13 UTC, nazaroviktor2 commented on hw1.py
> +            total_salary += salary
Кого их иметь в функции ?

2023-10-15 13:14 UTC, nazaroviktor2 commented on hw1.py
> +            total_salary += salary
@siriusdevs, подскажите, что значить "...кортеж названий отделов, которые нужно исключить из статистики "?

2023-10-15 13:18 UTC, nazaroviktor2 commented on hw1.py
> +    for department in departments:
чуть ошибся тогда
```
for department, employees in departments:
    for salary in employees.values():
```
Стало более понятно, разве нет?

2023-10-15 19:17 UTC, TeleginSergey commented on hw1.py
> +    for department in departments:
А обязательно? Просто моим способом менее читабельно, но более эффективно, так как всего 2 переменные. Можно оставлю?

2023-10-15 19:33 UTC, TeleginSergey commented
> Пожалуйста, не закрывай мержи. В чем смысл?

Чтобы по-быстрее ответили (про re-request review знаю)

2023-10-16 11:28 UTC, nazaroviktor2 commented
> > Пожалуйста, не закрывай мержи. В чем смысл?
> 
> Чтобы по-быстрее ответили (про re-request review знаю)

Не думаю что это ускоряет процесс. Скорее наоборот. Я вижу, что у тебя новый мерж, а у кого то уже 3 дня весит, то я буду сначала страрый проверять, хоть твой первый мерж был раньше него

2023-10-16 16:23 UTC, nazaroviktor2 requested changes

2023-10-16 16:23 UTC, nazaroviktor2 commented on hw1.py
> +    percent_best_salary = round(sum(permitted_wages) / total_payments * 100, 2)
Что будет если total_payments = 0?

2023-10-16 16:26 UTC, nazaroviktor2 commented on hw1.py
> +    exclude_deps = set(exclude_deps)
Что будет если exclude_deps = None? Добавь тесты на это

2023-10-16 16:29 UTC, nazaroviktor2 commented on hw1.py
> +) -> tuple[list[int | float], int]:
Процент разве не float?

2023-10-16 16:33 UTC, nazaroviktor2 requested changes
Надо не много поменять

2023-10-16 19:59 UTC, TeleginSergey commented on hw1.py
> +
Прочитай, пожалуйста, комментарий к мерджу, когда будешь еще раз проверять.

2023-10-17 09:40 UTC, nazaroviktor2 commented on hw1.py
> +    exclude_deps: tuple[str] = None,
tuple[str] - это значит, что у тебя приходит кортеж из одной строки, но это же не так. Правильная аннотация `tuple[str, ...]`

2023-10-17 09:45 UTC, nazaroviktor2 commented on hw1.py
> +) -> tuple[list[int | float], ]:
? -> `-> tuple[list[int | float], list[int | float]]:`

2023-10-17 09:47 UTC, nazaroviktor2 commented on hw1.py
> +) -> tuple[list[int | float], ]:
```suggestion
) -> tuple[list[int | float],  float]:
```

2023-10-17 09:49 UTC, nazaroviktor2 commented on hw1.py
> +    exclude_deps = set(exclude_deps)
```suggestion
    exclude_deps = set(exclude_deps) if exclude_deps else ()
```

2023-10-17 09:50 UTC, nazaroviktor2 requested changes
еще чуть чуть

2023-10-17 12:41 UTC, nazaroviktor2 submitted a review, later dismissed
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/f8856f14-4383-434a-b2dc-2e03a6f795c7)

2023-10-18 11:21 UTC, kirillsev1 commented on test_hw1.py
> +    assert best_wage(*departments, exclude_deps=exclude_data) == expected
Разбей тесты на несколько тесткейсов так, чтобы тесты логически отделялись друг от друга. Не стоит писать вообще все в один тес 1 - это не читабельно, 2 - как минимум надо разделять тесты на плохие, те которые могут не сработать и на те, где проверяется правильность выполнения функционала

2023-10-18 13:52 UTC, kirillsev1 requested changes

2023-10-27 08:37 UTC, kirillsev1 approved these changes

2023-10-30 19:30 UTC, nazaroviktor2 commented
У тебя конфликт в ветке

2023-10-31 15:18 UTC, nazaroviktor2 approved these changes

2023-11-03 13:32 UTC, siriusdevs submitted a review, later dismissed

2023-11-03 13:33 UTC, merged