Kolkareva
siriusdevs/homeworks_23 pull request #38
Opened 2023-10-22 10:11 UTC by Rin2396

2023-10-22 19:59 UTC, siriusdevs commented
Вы с ума сойдёте загружать, перезагружать и редактировать файлы через github. Учитесь загружать через push.

2023-10-23 10:58 UTC, KatyaGotskina requested changes

2023-10-23 10:58 UTC, KatyaGotskina commented on hw1.py
> +from typing import List, Tuple
Как сказал бы @nazaroviktor2 : "С версии python 3.9 Dict, Tuple, List можно не импортировать из typing. https://peps.python.org/pep-0585/"

2023-10-23 10:58 UTC, KatyaGotskina commented on hw1.py
> +                if salary <= lim:
Можно написать в одну строку `if lim is not None and salary <= lim`

2023-10-23 10:58 UTC, KatyaGotskina commented on hw1.py
> +        lim: float numerical limit which default is None.
По описанию не понятна функция переменной lim

2023-10-23 10:58 UTC, KatyaGotskina commented on hw1.py
> +        float: percentage of top 3 salaries to all salaries.
Наверное возвращается кортеж, состоящий из кортежа и float значения?

2023-10-23 10:58 UTC, KatyaGotskina commented on hw1.py
> +def calculate_salary(*departments: Tuple[str, List[float]], lim: float = None):
Где аннотация к возвращаемому объекту?
Я имею ввиду () -> tuple[...]

2023-10-23 10:58 UTC, KatyaGotskina commented on test_hw1.py
> +        None, ([95943, 94947.7, 93378], 40.51),
Посмотри https://github.com/siriusdevs/homeworks_23/pull/13#discussion_r1349513277 и https://github.com/siriusdevs/homeworks_23/pull/31#discussion_r1352786360

2023-10-23 21:33 UTC, annashutova requested changes

2023-10-23 21:33 UTC, annashutova commented on hw1.py
> +        for salary in department_salaries:
к сожалению, такой вариант не пройдет по flake, максимальная длина строки == 99, а здесь 114

2023-10-23 21:33 UTC, annashutova commented on hw1.py
> +                if salary <= lim:
@Rin2396, ты можешь заметить, что ты в любом случае выполняешь `salaries.append(round(salary, 2))`, следовательно у тебя не совсем корректно написано условие и его можно объединить в одно, подумай, как это можно сделать, если что, обращайся))

2023-10-23 21:33 UTC, annashutova commented on test_hw1.py
> +test_salaries = (
все **константы** в коде (что в основном, что в тестах) лучше писать капсом: TEST_SALARIES

2023-10-24 05:43 UTC, KatyaGotskina commented on hw1.py
> +        for salary in department_salaries:
Можно использовать менее длинные названия 🙂

2023-10-26 15:43 UTC, nazaroviktor2 commented on hw1.py
> +        for salary in department_salaries:
> к сожалению, такой вариант не пройдет по flake, максимальная длина строки == 99, а здесь 114

можно строки переносить)

2023-10-26 15:45 UTC, nazaroviktor2 commented on hw1.py
> +    return (all_salaries[:3], round(percent, 2))
Можно не оборачивать в скобки

2023-10-26 15:48 UTC, KatyaGotskina commented on hw1.py
> +    percent = (sum(all_salaries[:3]) / sum(all_salaries)) * 100
`sum(all_salaries)` можно было оставить записанной в переменную, потому что в данной программе она будет использоваться дважды. :) 
На данный момент для суммирования элементов all_salaries цикл выполняется 2 раза

2023-10-26 15:51 UTC, nazaroviktor2 commented on test_hw1.py
> +        ], ([95943, 94947.7, 93378], 40.51),
так лучше не писать

2023-10-30 19:36 UTC, nazaroviktor2 commented
Не исправлено
https://github.com/siriusdevs/homeworks_23/pull/38#discussion_r1373389302
https://github.com/siriusdevs/homeworks_23/pull/38#discussion_r1373385175

2023-11-06 11:45 UTC, nazaroviktor2 commented on hw1.py
> +    return (all_salaries[:3], round(percent, 2))
Вот это не исправлено

2023-11-14 11:22 UTC, nazaroviktor2 requested changes

2023-12-02 10:48 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/8110c160-59e5-473f-a9eb-2d663e79c8c8)

2023-12-04 08:17 UTC, nazaroviktor2 requested changes
Мне кажется не нужно было добавлять вторую домашку в этот мерж. На вторую домашку нет текстов, файла примера. Основная функции второй домашки (process_data) должна обрабатывать все ошибки( при вызове не должно быть ничего красного в консоли )

2023-12-04 08:17 UTC, nazaroviktor2 commented on hw2.py
> +    online = datetime.now() - datetime.strptime(user_info.get('last_login'), '%Y-%m-%d')
Если передали дату не в том формате?

2023-12-04 08:18 UTC, nazaroviktor2 commented
Первая домашка approve, вторая нет.
Я бы отменил тот коммит, где ты добавила вторую домашку
@siriusdevs

2023-12-15 20:19 UTC, Rin2396 commented
@nazaroviktor2 проверьте, пожалуйста, еще раз. Я убрала коммит с 2 дз.

2023-12-15 21:02 UTC, nazaroviktor2 submitted a review, later dismissed
Молодец, чуть чуть поправь

2023-12-15 21:02 UTC, nazaroviktor2 commented on hw1.py
> +def top_salary(*deps: tuple[str, list[float]], lim: float = None) -> tuple[tuple, float]:
поправь как в докстиргах 
`tuple[list, float]:` - у тебя возвращается список, а не кортеж

2023-12-15 21:02 UTC, nazaroviktor2 commented on hw1.py
> +                if salary <= lim:
`if lim is None or salary <= lim:`

2023-12-15 21:37 UTC, Rin2396 commented on hw1.py
> +                if salary <= lim:
![image](https://github.com/siriusdevs/homeworks_23/assets/114080477/852711a3-915f-434a-b535-67bb6c421373)
если я пишу так, у меня cognitive complexity не проходит

2023-12-15 21:42 UTC, Rin2396 commented on hw1.py
> +def top_salary(*deps: tuple[str, list[float]], lim: float = None) -> tuple[tuple, float]:
поправила)

2023-12-16 06:04 UTC, nazaroviktor2 approved these changes
Молодец!

2023-12-16 09:28 UTC, merged