Grigoryan
siriusdevs/homeworks_23 pull request #42
Opened 2023-10-22 21:05 UTC by Artem09076

2023-10-23 11:24 UTC, KatyaGotskina requested changes
Пока смотрю на твое решение, потом проверю тесты

2023-10-23 11:24 UTC, KatyaGotskina commented on hw2.py
> +"""This module include function process_data."""
Что? Вообще не понятно, что содержит в себе файл

2023-10-23 11:24 UTC, KatyaGotskina commented on hw2.py
> +        raise FileNotFoundError('Is not a file path')
Разве тут возвращается bool?

2023-10-23 11:24 UTC, KatyaGotskina commented on hw2.py
> +    with open(input_filepath, 'r') as file1:
Что за названия file1 и file2 -__-

2023-10-23 11:24 UTC, KatyaGotskina commented on hw2.py
> +        Returns a dictionary with statistics.
Не надо Returns: Returns

2023-10-23 11:24 UTC, KatyaGotskina commented on hw2.py
> +                    email.append(user[key].split('@')[1])
Какие то лишние сложности с подсчетом статистики в отдельной функции, тебе приходится в `dict_path` опять идти циклом по всем данным `set_names`. Не легче ли в данной проверке заносить данные в какую-нибудь структуру, а затем рассчитывать средние значения?

2023-10-23 11:24 UTC, KatyaGotskina commented on hw2.py
> +                    email.append(user[key].split('@')[1])
Может такое быть, что в email не будет '@'?

2023-10-28 08:52 UTC, Max2288 commented on hw2.py
> +        raise FileNotFoundError('Is not a file path')
Почему функция называется is_file, а проверяет файл на существование ?

2023-10-28 08:52 UTC, Max2288 commented on hw2.py
> +mail = 'email'
Константы следует писать так  - EMAIL

2023-10-28 08:55 UTC, Max2288 commented on hw2.py
> +            count_dct[registr][register]/regist_len
если register_len = 0?

2023-10-28 08:56 UTC, Max2288 commented on hw2.py
> +        res_dict[mail][email] = round((count_dct[mail][email]/email_len)*100, 2)
Аналогично

2023-11-13 07:57 UTC, Artem09076 commented
@Max228, @KatyaGotskina

2023-11-17 10:23 UTC, Artem09076 commented
@nazaroviktor2

2023-11-17 10:37 UTC, nazaroviktor2 commented
> @nazaroviktor2

?

2023-11-17 10:40 UTC, Artem09076 commented
> > @nazaroviktor2
> 
> ?

Мои проверяющие на три недели подзабили на меня, можете одного заменить? Или так нельзя?

2023-11-17 11:32 UTC, nazaroviktor2 requested changes

2023-11-17 11:32 UTC, nazaroviktor2 commented on hw2.py
> +        os.chdir(pwd)
```suggestion
    if not os.path.isfile(out_path):
        out_dir = os.path.dirname(out_path)
        if not os.path.exists(out_dir):
            try:
                os.makedirs(out_dir)
            except OSError as e:
                raise OSError(f"Error creating directory {out_dir}: {e}")

```

2023-11-17 11:32 UTC, nazaroviktor2 commented on hw2.py
> +    file_found(input_filepath, output_filepath)
Ваши основные функции не должны обрабатывать все ошибки, то есть при вызове функции я не должен видеть ничего красного

2023-11-17 11:32 UTC, nazaroviktor2 commented on test_hw2.py
> +     ),
Лучше не писать полный путь до файла. Если я захочу скачать твой проект и запустить тесты, у меня пути будут другие

2023-11-17 11:32 UTC, nazaroviktor2 commented on hw2.py
> +                reg_date = to_datetime(user.get(REGISTER), user.get(
Тут у тебя тоже ошибка может вернутся

2023-11-17 11:35 UTC, Artem09076 commented on test_hw2.py
> +     ),
Какая разница если они ошибочные?

2023-11-17 11:40 UTC, Artem09076 commented on hw2.py
> +        os.chdir(pwd)
Зачем мне так исправлять если я должен обрабатывать все ошибки?

2023-11-17 12:42 UTC, nazaroviktor2 commented on test_hw2.py
> +     ),
> Какая разница если они ошибочные?

Ааа я понял, прошу прошения. Мне почему то показалось, что у всех файлов полный путь

2023-11-17 12:48 UTC, nazaroviktor2 commented on hw2.py
> +        os.chdir(pwd)
Смотри в своей функции make_path  ты используешь os.mkdir -она создаст только одну папку.  makedirs - рекурсивно создаетcn все промежуточные каталоги, если они не существуют.

Забыл добавить exist_ok, поправил

2023-11-17 12:49 UTC, nazaroviktor2 commented on hw2.py
> +        os.chdir(pwd)
Функция make_path по факту не нужна. И в ней происходит, что то страшное

2023-11-17 20:16 UTC, nazaroviktor2 requested changes

2023-11-17 20:16 UTC, nazaroviktor2 commented on hw2.py
> +def process_data(input_filepath: str, output_filepath: str) -> NoReturn:
На самом, деле я не понимаю зачем вы все пишите NoReturn, если в данном случаю правильно использовать None
https://peps.python.org/pep-0484/#the-noreturn-type

2023-11-17 20:16 UTC, nazaroviktor2 commented on hw2.py
> +def load_input_file(input_filepath, output_filepath) -> Any:
Аннотация?

2023-11-17 20:16 UTC, nazaroviktor2 commented on hw2.py
> +    with open(input_filepath, 'r') as input_file:
Если permission denied?

2023-11-17 20:16 UTC, nazaroviktor2 commented on hw2.py
> +        return
Может текст тоже какой то возвращать? 
У тебя сейчас пишется в логи только, если что то пошло не так (как я увидел), а если все хорошо мы пользователю ничего не говорим?

2023-11-17 20:53 UTC, Artem09076 commented on hw2.py
> +        return
Если мы будем возвращать сообщение об ошибке тогда необходимость в тестовых файлах с ошибками проподает.

2023-11-18 17:48 UTC, nazaroviktor2 commented on hw2.py
> +        return
Ну по такой логике, после добавления логера необходимость в тестовых файлах с ошибками пропала.

2023-11-18 17:51 UTC, nazaroviktor2 approved these changes

2023-11-18 17:52 UTC, nazaroviktor2 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/ef524ced-c58c-4a29-9bcf-a37728788fc8)

2023-11-30 16:43 UTC, siriusdevs approved these changes
:tada:

2023-11-30 16:43 UTC, siriusdevs commented on hw2/input/11.json
> +    "riddle": "Что смешнее - студент, отправляющий мне анекдоты, или его 0 сданных домашних заданий?",
:laughing:

2023-11-30 17:13 UTC, Artem09076 commented on hw2/input/11.json
> +    "riddle": "Что смешнее - студент, отправляющий мне анекдоты, или его 0 сданных домашних заданий?",
Не переживайте, скоро это закончится

2023-12-02 07:36 UTC, merged