Zorina A.
siriusdevs/homeworks_23 pull request #44
Opened 2023-10-23 14:26 UTC by nastyazz

2023-10-26 17:18 UTC, nazaroviktor2 commented on setup.cfg
> +        WPS304,
Изменение setup.cfg по согласованию с @siriusdevs

2023-10-26 17:19 UTC, nazaroviktor2 commented on test_hw1.py
> +from typing import Tuple
С python 3.9 можно не импортировать Tuple, просто пиши tuple

2023-10-26 17:21 UTC, nazaroviktor2 commented on hw1.py
> +def statistic_salary(*args, limit: Optional[int] = None) -> tuple:
Название переменных должны, как  можно точнее показывать, что в них лежит. Тебе приходит кортеж отделов компании. Назови переменную company или departments

2023-10-26 17:22 UTC, nazaroviktor2 commented on hw1.py
> +def statistic_salary(*args, limit: Optional[int] = None) -> tuple:
Не хватает аннотации для args и tuple. tuple из чего?

2023-10-26 17:24 UTC, nazaroviktor2 commented on hw1.py
> +    if not args[0]:
Если args будет = [], то тут будет ошибка. 
Нужна проверка `len(args)`

2023-10-26 17:26 UTC, nazaroviktor2 commented on hw1.py
> +        for salaries in data_salary[1].values():
```suggestion
    for _, employees in departments:
        for salary in employees.values():
```

2023-10-26 17:29 UTC, nazaroviktor2 commented on hw1.py
> +    stat_salary.append(round(sum(salary) / len_salary, 2))
если len_salary = 0 будет ошибка

2023-10-26 17:34 UTC, nazaroviktor2 commented on hw1.py
> +             ))
Не читабельно

2023-10-26 17:34 UTC, nazaroviktor2 requested changes
Молодец, но есть замечания

2023-10-26 18:11 UTC, nazaroviktor2 commented on hw1.py
> +            if limit is None or limit >= salaries:
у тебя в задание написано 
"...  числовой предел, выше которого зарплаты учитывать не нужно"
Значит <=

2023-10-26 18:35 UTC, nastyazz commented on hw1.py
> +             ))
У меня по-другому не получается, так как flake8 ругается((

2023-10-26 18:35 UTC, nastyazz commented on hw1.py
> +    return tuple(stat_salary)
поняла

2023-10-26 19:28 UTC, nastyazz commented on setup.cfg
> +        WPS304,
Я setup.cfg взяла из 2 дз, так как у меня выходила ошибка, которая там игнорируется

2023-10-26 19:39 UTC, siriusdevs commented
Ваше решение и тесты подозрительно похожи на решение и тесты вашей сестры. Даже ошибка фильтрации зарплат относительно предела связана с заданием сестры. Возможно, вы решали вместе. А возможно, кто-то из вас списал. На первый раз вам выносится предупреждение. В следующий раз в подобной ситуации будет выдано новое задание и работа будет напрасной. Разбираться, кто списал, я не буду - просто выдам новое задание обеим. Надеюсь, что ошибаюсь.

2023-10-27 10:24 UTC, nastyazz commented on hw1.py
> +            if limit is None or limit >= salaries:
Так всё правильно. Мы не учитываем те, которые выше.

2023-10-30 20:41 UTC, nazaroviktor2 requested changes

2023-10-30 20:41 UTC, nazaroviktor2 commented on setup.cfg
> +max-line-complexity=18
А это не исправилось? На какую строку ругается?

2023-10-30 20:41 UTC, nazaroviktor2 commented on setup.cfg
> +        WPS304,
setup.cfg Альберт Андреевич одобрил?

2023-10-30 20:41 UTC, nazaroviktor2 commented on hw1.py
> +    stat_salary = []
почему сразу set не создать?

2023-10-30 20:41 UTC, nazaroviktor2 commented on hw1.py
> +    if not args[0]:
@nastyazz это не исправила

2023-10-30 20:41 UTC, nazaroviktor2 commented on hw1.py
> +    if not args[0]:
Вообще эту проверку можно удалить

2023-10-30 20:41 UTC, nazaroviktor2 commented on hw1.py
> +        return (0, 0, 0)
Избыточная проверка, у тебя и так если пустой массив то на 30 будет проверка.

2023-10-31 05:45 UTC, nastyazz commented on hw1.py
> +    stat_salary = []
Зачем создавать set?

2023-10-31 06:42 UTC, nastyazz commented on hw1.py
> +        return (0, 0, 0)
Если я уберу это, то у меня не проходят тесты. Также эта проверка на пустой ли массив более важна, нежели то, что вы посоветовали сделать на длину списка. Если изначально картеж не пустой, то длина списка не может быть 0.

2023-10-31 06:44 UTC, nastyazz commented on setup.cfg
> +        WPS304,
Это setup.cfg Альберта Андреевича. Я просто взяла и скопировала его.

2023-10-31 06:45 UTC, nastyazz commented on setup.cfg
> +max-line-complexity=18
Это setup.cfg Альберта Андреевича. Я просто взяла и скопировала его.

2023-11-06 11:39 UTC, nazaroviktor2 commented on hw1.py
> +        return (0, 0, 0)
а куда делать проверка на 30 строчке?

2023-11-06 11:39 UTC, nazaroviktor2 commented on hw1.py
> +    stat_salary = []
прощу прощения, перепутал. tuple

2023-11-06 11:41 UTC, nazaroviktor2 requested changes

2023-11-06 11:41 UTC, nazaroviktor2 commented on hw1.py
> +    stat_salary.append(round(sum(salaries) / len_salaries, 2))
Если len_salaries = 0 то будет ошибка

2023-11-06 14:38 UTC, nastyazz commented on hw1.py
> +    stat_salary = []
кортеж это ведь неизменяемый тип данных, я не могу в него что-то добавить..

2023-11-06 14:50 UTC, nazaroviktor2 commented on hw1.py
> +        return (0, 0, 0)
тут можно не оборачивать в скобочки
`return 0, 0, 0`

2023-11-06 15:07 UTC, nazaroviktor2 requested changes
https://github.com/siriusdevs/homeworks_23/pull/44/files#r1383467242
вот это поправь и все вроде

2023-11-11 12:38 UTC, nazaroviktor2 requested changes

2023-11-11 12:38 UTC, nazaroviktor2 commented on hw1.py
> +        return (0, 0, 0)
Я ничего не понимаю. 
У тебя проверка, есть ли первый отдел. Зачем тебе эта проверка? Если тебе передадут компанию без отделов, то у тебя будет ошибка. 
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/f44882bc-4aff-4ae2-829b-12ae74426455)

2023-11-11 12:38 UTC, nazaroviktor2 commented on hw1.py
> +        return (0, 0, 0)
Если убрать эту проверку, то твой код работает верно 
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/28b5af0f-3fe6-46d2-885e-dd49b411682e)

2023-11-11 15:09 UTC, nastyazz commented on hw1.py
> +        return (0, 0, 0)
Хорошо. Я оставила эту проверку, но убрала индексацию, эта проверка теперь на деление на ноль, тк в тестах не проходил без этого 1 тест, добавила распаковку и поправила тесты.

2023-11-11 15:25 UTC, nazaroviktor2 commented on hw1.py
> +        return (0, 0, 0)
Убери эту проверку и перенеси проверку с 32 строчки (`  if len_salaries == 0:
        return 0, 0, 0`) сразу после for и проверь тесты еще раз

2023-11-11 15:29 UTC, nastyazz commented on hw1.py
> +        return (0, 0, 0)
не проходит ни один тест

2023-11-11 15:32 UTC, nastyazz commented on hw1.py
> +        return (0, 0, 0)
сейчас тут кое-что поменяла, прошло 3 теста, 1 не проходит по причине деления на ноль

2023-11-11 15:34 UTC, nazaroviktor2 commented on hw1.py
> +        return (0, 0, 0)
> не проходит ни один тест
🧐
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/156ff12a-2a32-4b8f-b8ea-f1e43e00314c)

2023-11-11 15:45 UTC, nazaroviktor2 approved these changes
![Uploading image.png…]()

2023-11-11 15:46 UTC, nazaroviktor2 commented
@Max2288 @kirillsev1 @radugaboost @KatyaGotskina @annashutova

2023-12-02 07:24 UTC, merged