zorina_e
siriusdevs/homeworks_23 pull request #45
Opened 2023-10-24 11:30 UTC by drain678

2023-10-26 17:41 UTC, nazaroviktor2 commented on test_hw1.py
> +from typing import Tuple
С python 3.9 можно не импортировать Tuple, просто пиши tuple

2023-10-26 17:43 UTC, nazaroviktor2 commented on hw1.py
> +        for _, salary in department[1].items():
```suggestion
    for _, employees in departments:
        for salary in employees.values():
```

2023-10-26 17:44 UTC, nazaroviktor2 commented on hw1.py
> +        median_elements += sorted(all_sls)[count_salaries // 2]
Можно лучше один раз выше отсортировать и сохранить ?

2023-10-26 17:45 UTC, nazaroviktor2 requested changes
Молодец, но нужно не много поменять

2023-10-26 18:29 UTC, drain678 commented on hw1.py
> +        median_elements += sorted(all_sls)[count_salaries // 2]
У меня если добавить еще одну переменную, то flake8 не проходит, из-за того, что больше восьми переменных становится

2023-10-26 18:36 UTC, drain678 commented on hw1.py
> +        median_elements += sorted(all_sls)[count_salaries // 2]
Хотя, я сейчас исправила код в цикле, как ты мне показал, и появилось место для еще одной переменной. Сейчас тогда переделаю

2023-10-26 19:39 UTC, siriusdevs commented
Ваше решение и тесты подозрительно похожи на решение и тесты вашей сестры. Даже ошибка фильтрации зарплат относительно предела у вашей сестры связана с вашим заданием. Возможно, вы решали вместе. А возможно, кто-то из вас списал. На первый раз вам выносится предупреждение. В следующий раз в подобной ситуации будет выдано новое задание и работа будет напрасной. Разбираться, кто списал, я не буду - просто выдам новое задание обеим. Надеюсь, что ошибаюсь.

2023-10-30 19:26 UTC, nazaroviktor2 commented on hw1.py
> +        median_elements += sorted(all_sls)[count_salaries // 2]
тебе не нужна новая переменная
`all_sls.sort()`

2023-11-06 11:50 UTC, nazaroviktor2 requested changes

2023-11-06 11:50 UTC, nazaroviktor2 commented on hw1.py
> +        return (0, 0, 0)
Тут можно не оборачивать в скобочки

2023-11-07 14:01 UTC, drain678 commented on hw1.py
> +        return (0, 0, 0)
Хорошо, исправлю

2023-11-11 12:39 UTC, nazaroviktor2 requested changes

2023-11-11 12:39 UTC, nazaroviktor2 commented on hw1.py
> +        median_elements += sorted(all_sls)[count_salaries // 2]
@drain678 это не исправила

2023-11-11 15:20 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/3f679ded-5b9a-4114-b1f4-54c44413da66)

2023-11-11 15:22 UTC, nazaroviktor2 commented
@Max2288 @kirillsev1 @radugaboost @KatyaGotskina @annashutova

2023-11-14 11:21 UTC, radugaboost approved these changes
good job :)

2023-11-15 09:16 UTC, siriusdevs approved these changes

2023-11-15 09:17 UTC, merged