Demyanenko
siriusdevs/homeworks_23 pull request #46
Opened 2023-10-24 12:07 UTC by slavikyd

Sorry for too much of commits, was having troubles with identations in pylint

2023-10-26 17:49 UTC, nazaroviktor2 commented on hw2/hw2.py
> +def stats_by_age(ages: list) -> dict:
list чего? dict из чего?

2023-10-26 17:52 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    total = sum(age_gaps)
если age_gaps = 0?

2023-10-26 17:53 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(in_path) as input_data:
если файл не найден?

2023-10-26 17:54 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        output[key] = round(output[key] / total * 100, 2)
если total = 0?

2023-10-26 17:55 UTC, nazaroviktor2 requested changes
Надо поправить аннотации, добавить комментарии, навести порядок в папках (тесты в одну папку, функции в другую)

2023-10-26 18:49 UTC, slavikyd commented on hw2/hw2.py
> +    with open(in_path) as input_data:
Там один JSONDecodeError на любые проблемы с файлом которые возникают

2023-10-26 18:50 UTC, slavikyd commented on hw2/hw2.py
> +    total = sum(age_gaps)
Исправил. Там в случае если 0 нужно было просто исходный словарь возвращать и все, так до ZeroDivisionError даже не дойдет

2023-10-26 18:52 UTC, slavikyd commented on hw2/hw2.py
> +        output[key] = round(output[key] / total * 100, 2)
По идее нужно как то по хитрому это обрабатывать, но мне ничего лучше чем возвращать словарь с замечанием, что значений нет, в голову не пришло

2023-10-26 19:16 UTC, slavikyd commented
> Надо поправить аннотации, добавить комментарии, навести порядок в папках (тесты в одну папку, функции в другую)

Не знаю почему, но с папками у pytest прям беда беда. Может я что-то не так делаю, но он совсем не видит модуль если он в другой папке. Пока что просто вынес тестовые файлы в отдельную папку.

P.S.: параллельно у меня опять почему-то сломался pylint из-за отступов, но вроде все починилось

2023-10-28 08:43 UTC, Max2288 commented on hw2/hw2.py
> +    if age_gaps == 0:
Тут всегда будет false , ты проверяешь равен ли список 0

2023-10-28 08:44 UTC, Max2288 commented on hw2/hw2.py
> +        round(age_gaps[0] / total * 100, 2),
если total = 0?

2023-10-28 13:21 UTC, slavikyd commented on hw2/hw2.py
> +        round(age_gaps[0] / total * 100, 2),
Изначально недосмотрел, сразу хотел total на равенство нулю проверять. Но там странно получается, ибо если возраст в Json'е отсутствует, будет keyerror, а если все будет в нулях, попадает под условие задания, что первая категория возрастов это все кто младше 18 (странно конечно пользователь которому 0 лет, но по сути же подходит). У меня была дыра в match case, ибо все значения меньше 18 (даже отрицательные) отлетали в первую категорию, но сейчас я поправил чтобы такого не было.

2023-10-30 20:45 UTC, nazaroviktor2 commented on hw2/hw2.py
> +            output.update({element: 1})
`output[element] = 1`

2023-10-30 20:55 UTC, nazaroviktor2 requested changes

2023-10-30 20:55 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(in_path) as input_data:
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/64bf38ff-ea30-48a1-9ef0-bca3f983ccd8)

2023-10-30 20:55 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        ages.append(user_data['age'])
если данные не валидные и нет age?

2023-10-30 20:55 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        reg_years.append(user_data['registered'][:4])
если нет поля registered

2023-10-30 20:55 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(out_path, 'w') as json_file:
если в пути будут указаны папки которые не созданы?

2023-10-30 20:55 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    age_gaps = [0, 0, 0, 0, 0]
нельзя сразу в output хранить?

2023-10-30 20:55 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    total = sum(age_gaps)
Норм исправил. 
Ну если, что можно  a/max(total, 1)

2023-10-30 20:55 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        output[key] = round(output[key] / total * 100, 2)
тоже можно total = max(1, len(sum(output.values()))

2023-11-06 11:55 UTC, nazaroviktor2 requested changes

2023-11-06 11:55 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        user_stats = json.load(input_data)
ты два раза файл читаешь

2023-11-06 12:01 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    """Output writer muodule.
module*

2023-11-12 14:19 UTC, nazaroviktor2 requested changes

2023-11-12 14:19 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        if 'age' not in user_data.keys() or 'registered' not in user_data.keys():
```suggestion
    age = user_data.get("age", None) # второй аргумент значения, если ключ не найден, по умолчанию None
    registered = user_data.get("registered")
        if not (age and registered):
```

2023-11-12 14:19 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        if 'age' not in user_data.keys() or 'registered' not in user_data.keys():
возможно даже проверка не нужна будет

2023-11-12 14:19 UTC, nazaroviktor2 commented on hw2/hw2.py
> +            raise ValueError('Not valid file provided, missing age or registered data')
обсудили с @siriusdevs и пришли к тому, что ваши основные функции должны обрабатывать все ошибки. То есть при вызове основной функции я не должен видеть ничего красного в консоли.

2023-11-14 08:41 UTC, slavikyd commented on hw2/hw2.py
> +        if 'age' not in user_data.keys() or 'registered' not in user_data.keys():
я чуток по другому сделал, но не до конца уверен насколько оно вменяемо. Если опять перемудрил то подгоню под это

2023-11-14 11:15 UTC, nazaroviktor2 requested changes

2023-11-14 11:15 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        if 'age' not in user_data.keys() or 'registered' not in user_data.keys():
`        if not (user_data.get("age") and user_data.get("registered")):`
мне кажется даже так по проще выглядит

2023-11-14 13:16 UTC, slavikyd commented on hw2/hw2.py
> +            reg_years = [None for _ in range(len(user_data))]
Ну до этого вместо None все падало в ошибку... Просто какой смысл в статистике если у нас где-то среди элементов будет None ответ поломается же

2023-11-14 14:28 UTC, nazaroviktor2 commented on hw2/hw2.py
> +            reg_years = [None for _ in range(len(user_data))]
> Ну до этого вместо None все падало в ошибку... Просто какой смысл в статистике если у нас где-то среди элементов будет None ответ поломается же

Возможно. Можно еще просто не учитывать если не передали поле. 
Представь тебе надо предоставить статистику о среднем возрасте пользователей социальной сети. У каких то пользователей не будет заполнена графа возраст. Ты же не скажешь - я не могу это сделать, у нас есть пользователи без возраста. 
Ты скорее всего просто их не учтешь или сделаешь отдельную колонку с количеством пользователей без возраста

2023-11-14 20:14 UTC, slavikyd commented on hw2/hw2.py
> +            reg_years = [None for _ in range(len(user_data))]
Собственно к этому я и пришел, по сути сейчас появилась доп группа для людей у которых нету возраста или если год регистрации не указан вместо него прилетает 'NaN'

2023-11-14 20:15 UTC, slavikyd commented on hw2/hw2.py
> +    except FileNotFoundError:
Он очень сильно ругается на больше чем одну ошибку в except, поэтому пришлось в три разных выносить. Хотя возможно есть смысл просто свою ошибку собрать

2023-11-17 11:02 UTC, nazaroviktor2 requested changes

2023-11-19 08:09 UTC, slavikyd commented on hw2/hw2.py
> +        ) -> None:
Без таба флейк падает по E125

2023-11-19 08:17 UTC, slavikyd commented on hw2/hw2.py
> +        ages.append(user_data['age'])
Я пока убрал break и вместо второго if сделал elif, так вроде должно тоже работать

2023-11-19 09:08 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        ) -> None:
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/715f09a0-5cfc-4cf3-a47e-c92a6880c24d)

2023-11-19 09:19 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/4599758f-1eea-49cc-a3af-18a052f962cf)

2023-11-19 09:19 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        os.mkdir(op.dirname(file_path))
mkdir создать только одну папку. Лучше используй makedirs https://docs-python.ru/standart-library/modul-os-python/funktsija-makedirs-modulja-os/

2023-11-30 16:50 UTC, siriusdevs requested changes

2023-11-30 16:50 UTC, siriusdevs commented on hw2/test_hw2.py
First test, second test, third test, fourth test :disappointed:

2023-12-15 09:15 UTC, merged