Komarov
siriusdevs/homeworks_23 pull request #47
Opened 2023-10-24 13:48 UTC by k0marov

2023-10-26 16:17 UTC, Max2288 approved these changes

2023-10-26 16:50 UTC, nazaroviktor2 commented on hw1.py
> +"""
Спасибо ❤️

2023-10-26 16:52 UTC, nazaroviktor2 commented on setup.cfg
> +        WPS30
serup.cfg можно менять только с разрешения @siriusdevs

2023-10-26 16:54 UTC, nazaroviktor2 commented on hw1.py
> +    return sum(nums) / len(nums)
если nums пусто список будет ошибка

2023-10-26 16:54 UTC, nazaroviktor2 commented on hw1.py
> +        nums[center]
если nums = [] будет ошика

2023-10-26 16:56 UTC, k0marov commented on hw1.py
> +    return sum(nums) / len(nums)
Так и задумано для этой приватной функции. На пустоту списка проверка происходит в get_salary_stats()

2023-10-26 16:56 UTC, k0marov commented on hw1.py
> +        nums[center]
Так и задумано для этой приватной функции. На пустоту списка проверка происходит в get_salary_stats()

2023-10-26 17:06 UTC, nazaroviktor2 requested changes
Хорошая работа, молодец. Надо пару мест поправить

2023-10-26 17:06 UTC, k0marov commented on setup.cfg
> +        WPS30
Запрашиваю разрешение @siriusdevs на добавление игнора линта "magic numbers" для файлов с тестами.

2023-10-26 17:10 UTC, nazaroviktor2 commented on hw1.py
> +    return sum(nums) / len(nums)
Окей. Но на будущие лучше делать не зависимые функции, чтобы их потом можно было бы пере использовать

2023-10-26 17:10 UTC, nazaroviktor2 commented on hw1.py
> +        nums[center]
Окей

2023-11-01 19:43 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/88b78d23-f390-4ae9-8d8b-6061287ceb25)

2023-11-05 10:21 UTC, k0marov commented
@Max2288

2023-11-06 10:28 UTC, Max2288 approved these changes

2023-11-06 11:39 UTC, siriusdevs approved these changes

2023-11-06 11:41 UTC, merged