Added first homework
siriusdevs/homeworks_23 pull request #48
Opened 2023-10-26 09:48 UTC by viktoriatyapkova

2023-10-27 09:38 UTC, kirillsev1 commented on hw1.py
> +                raise Exception('Нет данных по введенному лимиту!')
Exception сработает если хотя бы в одной итерации filt окажется пустым, но ведь может быть такое, когда в одном отделе зп будут превышать limit, а во втором не будут превышать и получится, что программа остановила свое выполнение, хотя не должна была

2023-10-27 09:45 UTC, kirillsev1 commented on hw1.py
> +        f'Топ низкооплачиваемых отделов: {low_paid_res}'
Лучше возвращай просто списки. По докстрингам будет понятно, за что отвечает первый аргумент, а за что второй. Строки потом будет неудобно разбирать, если задача ориентирована на получение статистики

2023-10-27 09:47 UTC, kirillsev1 commented on hw1.py
> +        dict: the first - 3 highly paid, the second - 3 low-paid departments.
Сейчас ты возвращаешь не dict, tuple. Потому что если пишешь return arg1, arg2 - на деле возвращается кортеж, т.е. tuple

2023-10-27 09:50 UTC, kirillsev1 requested changes
Надо немного подправить

2023-10-28 08:40 UTC, Max2288 commented on hw1.py
> +        new[depts] = round(sum(salary) / len(salary), 2)
А если len = 0?

2023-11-30 16:52 UTC, siriusdevs requested changes

2023-12-06 21:22 UTC, siriusdevs requested changes

2023-12-06 21:22 UTC, siriusdevs commented on __pycache__/hw1.cpython-310.pyc
у вас что, нет файла gitignore? я не должен на github видеть pycache!

2023-12-20 02:09 UTC, siriusdevs commented
Пожалуйста, пока уберите вторую домашнюю из этого PR. Можете для второй домашней создать отдельную ветку в своём форке и сделать отдельный PR, если хотите. 
Готов поставить здесь approve, но по первой домашней. Один PR - одна домашняя.

2023-12-20 09:09 UTC, siriusdevs approved these changes

2023-12-20 09:09 UTC, merged