Romodanov hw2
siriusdevs/homeworks_23 pull request #49
Opened 2023-10-27 13:26 UTC by darvenommm

2023-10-28 08:32 UTC, Max2288 commented on hw2/create_stats.py
> +        key: (count / users_count * 100) for (key, count) in stats.items()
Что будет если users_count = 0?

2023-10-28 08:57 UTC, darvenommm commented on hw2/create_stats.py
> +        key: (count / users_count * 100) for (key, count) in stats.items()
user_count будет равен нулю только тогда, когда нам будет передан пустой словарь, а в таком случае в нашем цикле будет ноль итераций, то есть деления на нуль не состоится

2023-10-28 09:00 UTC, darvenommm commented on hw2/create_stats.py
> +        key: (count / users_count * 100) for (key, count) in stats.items()
Конечно, можно добавить много условий, которые будут обрабатывать все возможные ошибки, но для хелпера, который всегда будет получать корректные значение из основной функции, думаю, это будет излишни

2023-11-01 17:15 UTC, nazaroviktor2 requested changes

2023-11-01 17:15 UTC, nazaroviktor2 commented on hw2/main.py
> +    with open(users_path) as users_file:
Если путь не найден?

2023-11-01 17:15 UTC, nazaroviktor2 commented on hw2/main.py
> +        email_domain = str(user['email']).split('@')[-1]  # str because email can be int
Если нет ключа email?

2023-11-01 17:15 UTC, nazaroviktor2 commented on hw2/main.py
> +        increment_field.increment_field(users_by_year, str(user['age']))
Если нет ключа age?

2023-11-01 17:15 UTC, nazaroviktor2 commented on hw2/main.py
> +    with open(result_path, 'w') as result_file:
если путь не найден

2023-11-06 11:54 UTC, Max2288 commented on hw2/create_stats.py
> +        key: (count / users_count * 100) for (key, count) in stats.items()
в цикле будет 0 итераций, но ты все равно передашь в функцию 0, она вызовет ошибку и что с этим делать?

2023-11-21 17:14 UTC, darvenommm commented
@nazaroviktor2
@Max2288

2023-11-22 12:38 UTC, nazaroviktor2 requested changes
Еще обсудили с @siriusdevs и пришли к тому, что ваши основные функции должны обрабатывать все ошибки. То есть при вызове основной функции я не должен видеть ничего красного в консоли.

2023-11-22 12:38 UTC, nazaroviktor2 commented on hw2/main.py
> +    with open(result_path, 'w') as result_file:
Это не поправил

2023-11-22 17:14 UTC, darvenommm commented
> Еще обсудили с @siriusdevs и пришли к тому, что ваши основные функции должны обрабатывать все ошибки. То есть при вызове основной функции я не должен видеть ничего красного в консоли.

То есть мне нужно не выбрасивать ошибки, а выводить эту информацию в консоль через print, или как?

2023-11-23 20:20 UTC, darvenommm commented
Использовал sys.stdout.write для выводы информации в консоль, потому что flake8 ругается на использование print в коде.

2023-11-25 13:01 UTC, nazaroviktor2 commented
> Использовал sys.stdout.write для выводы информации в консоль, потому что flake8 ругается на применение функции print в коде.

Можно через консиль, можно логи, можно возвращать сообщение через return

2023-11-25 13:05 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/5cd79d50-1b60-4a06-8a29-a25e2d2cb07c)

2023-11-25 13:06 UTC, nazaroviktor2 commented
Можно было бы конечно создавать конечный файл через [os.makedirs](https://docs-python.ru/standart-library/modul-os-python/funktsija-makedirs-modulja-os/), но и так нормально

2023-11-25 18:17 UTC, darvenommm commented
@Max2288
Ожидаю твоего ревью

2023-11-30 16:59 UTC, siriusdevs approved these changes
:tada:

2023-12-04 11:52 UTC, merged