Dyatlova (=^‥^=)
siriusdevs/homeworks_23 pull request #50
Opened 2023-10-28 19:24 UTC by tofickbrodaga

I DID IT!!1!!1!!!1!

⣿⣿⣿⣿⣿⢙⠛⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠛⢋⠉⠘⣿⣿
⣿⣿⣿⣿⡏⠄⠄⠄⠙⠻⣿⣿⣿⣿⣿⣿⣿⣿⡿⠟⠉⠄⠄⠄⠄⠁⢸⣿
⣿⣿⣿⣿⠄⠄⠄⠄⠄⠄⠈⠙⢿⣿⣿⣿⡿⠋⠄⠄⠄⠄⠄⢀⠄⠄⢹⣿
⣿⣿⣿⣿⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⢀⠄⠄⢸⣿
⣿⣿⣿⠿⢤⣤⡔⠒⣶⣶⣶⣶⣶⡖⠒⠒⠒⠒⣶⣖⠒⣶⣦⣤⣤⣄⣸⣿
⣿⣷⡀⠄⠈⣿⣿⡄⢻⣿⣿⣿⣿⣿⡄⠄⠄⠄⢹⣿⡆⢹⣿⣿⣿⣿⣿⣿
⣿⣿⣷⠄⠄⠸⣿⣷⡈⣿⣿⡿⠹⣿⣿⡀⠄⠄⠄⢻⣿⡄⢻⣿⣿⣿⣿⣿
⣿⣿⣿⣷⣾⣷⣿⣿⣿⣿⡿⠁⠄⢻⣿⣿⣿⣿⣿⣿⣿⣷⣼⣿⣿⣿⣿⣿
⣿⣿⣿⣿⠄⣿⣿⣿⣿⡿⠁⠄⣤⠈⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠟⣿
⣿⣿⣿⠟⠄⠄⠉⠉⠉⠄⠄⡿⠛⢻⠈⠙⠟⠛⠛⠻⠿⠿⢿⠿⠿⠁⢀⣿
⣿⣿⣿⣿⡝⠐⠄⠄⠄⠄⠄⣀⠄⠄⠄⠄⠩⠐⡀⠄⠄⠈⠉⢿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⡖⠄⣀⠄⠄⠛⠻⣿⣿⠟⠛⠄⠄⠄⠄⠄⣀⣴⣿⣿⣿⣿⣿
⣿⣿⣿⣿⣿⠇⣠⠊⠈⠐⠤⢤⣀⣀⣠⠤⣀⣀⣀⠛⠉⠄⠉⠻⣿⣿⣿⣿
⣿⣿⣿⡿⢋⡰⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠈⢿⣿⣿
⣿⣿⡋⠐⢰⠁⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠄⠘⣿⣿

2023-10-31 11:43 UTC, nazaroviktor2 requested changes

2023-10-31 11:43 UTC, nazaroviktor2 commented on setup.cfg
> +
Явно половину из этих ошибок можно исправить. Попробуй это сделать, потом мы начнем проверку.
Или если @siriusdevs разрешит так изменить setup.cfg

2023-10-31 11:54 UTC, tofickbrodaga commented on setup.cfg
> +
Когда я пыталась создать дополнительный модуль, у меня на тестах выходили адские ошибки и проценты были около 1000. Зато ошибок flake8 не было))) 
Я не понимаю как решать overlap. 
У меня выходят ошибки об переменных, которые возвращаются просто. Как иначе - я не понимаю. 
А то, что есть иные варианты, да, они есть, но я не понимаю как конкретно это решать, потому что такой вариант решения я не понимаю, у меня так и я не знаю как иначе. 
Когнитивная комплексность вылезает из-за того, что в get-last-login засунуты все действия. По модулям разбить - читай первый абзац. 
Как это решать я без понятия

2023-10-31 11:56 UTC, tofickbrodaga commented on setup.cfg
> +
В глобальных ошибках - ошибки из прошлой домашки, которые были добавлены до обновления .cfg и слияние веток было одобрено. Потом конфиг обновился.

2023-10-31 14:34 UTC, nazaroviktor2 requested changes

2023-10-31 14:34 UTC, nazaroviktor2 commented on hw2.py
> +    return datafile
return переносишь на 42 строчку и ошибка решается

2023-10-31 14:38 UTC, nazaroviktor2 commented on setup.cfg
> +
WPS331 решается просто переименовав переменную https://ru.hexlet.io/topics/55596

Ты пыталась гуглить ошибки?

2023-10-31 14:41 UTC, tofickbrodaga commented on setup.cfg
> +
Естественно я пыталась гуглить ошибку, к чему такое? 
Где ты мне предлагаешь переименовать переменные, если циклы взаимосвязаны? Создать еще одну 14-ю переменную? Я не понимаю.

2023-10-31 14:44 UTC, nazaroviktor2 commented on setup.cfg
> +
Можно разбить на две функции

2023-10-31 14:45 UTC, nazaroviktor2 commented on hw2.py
> +            last_login_stats.append(last_login)
Почему эта переменная глобальная?

2023-10-31 14:46 UTC, tofickbrodaga commented on setup.cfg
> +
Оно не будет работать. Ты вообще читал что я писала?

2023-10-31 14:47 UTC, tofickbrodaga commented on hw2.py
> +            last_login_stats.append(last_login)
many local variables 13 > 8

2023-12-11 21:27 UTC, tofickbrodaga commented
@siriusdevs какой доп.вопрос и по какой дисциплине будет, если не сдать 2-ю домашку? 
Я билась над этой домашкой с репетитором, также самостоятельно около двух месяцев и все бесполезно. 
Я знаю как писать эту задачу, но по flake8, увы, не могу. Также и с тестами. Тесты еще можно сделать, но по flake-у я бессильна.

2023-12-14 15:43 UTC, closed without merging

2023-12-14 18:21 UTC, tofickbrodaga commented
Закрыто по причине:
"Лучше доп две практики, где не нужен флейк8, чем мучаться с флейк8, хотя решение тасков ты пишешь"

2023-12-14 18:26 UTC, tofickbrodaga commented
То самое чувство, когда какая-то библиотека решает отчислишься и лишишь себя нормальной жизни или нет 
🫠