Osipov
siriusdevs/homeworks_23 pull request #51
Opened 2023-10-29 14:10 UTC by lifelongCat

2023-10-31 15:09 UTC, nazaroviktor2 commented on hw1.py
> +        if used_deps is None or dep_name in used_deps:
На будущие. так как это у тебя used_deps это кортеж то if dep_name  in used_deps: каждый раз будет выполнятся за O(n). Но если бы used_deps - set то это проверка занимала бы O(1) - разница очень большая. Поэтому ты можешь в перед циклом сделать set(used_deps), что очень сильно ускорит твою программу

2023-10-31 15:11 UTC, nazaroviktor2 commented on hw1.py
> +    if not all_salaries:
когда all_salaries = [0,0,0,0,0,0,0] - будет ошибка

2023-10-31 15:11 UTC, nazaroviktor2 commented on hw1.py
> +    return sum(top_salaries) / sum(all_salaries) * 100
когда all_salaries = [0,0,0,0,0,0,0] - будет ошибка

2023-10-31 15:12 UTC, nazaroviktor2 requested changes
Молодец, хорошая работа

2023-10-31 15:18 UTC, lifelongCat commented on hw1.py
> +Salaries = list[float, ...]
у меня много раз используется эта аннотация, поэтому вынес её для простоты понимания кода

2023-10-31 15:20 UTC, nazaroviktor2 commented on hw1.py
> +Salaries = list[float, ...]
Да ты правильно сделал. Я говорю только про троеточие 
`Salaries = list[float]`

2023-10-31 15:27 UTC, lifelongCat commented on hw1.py
> +        if used_deps is None or dep_name in used_deps:
готово

2023-10-31 15:29 UTC, nazaroviktor2 commented on hw1.py
> +    used_deps_set = set(used_deps) if used_deps is not None else None
Если сделаешь так, то `dep_name in used_deps_set` будет с ошибкой. _TypeError: argument of type 'NoneType' is not iterable_

2023-10-31 15:31 UTC, lifelongCat commented on hw1.py
> +Salaries = list[float, ...]
так троеточие разве не означает, что у меня будет несколько элементов типа float в списке, а не один элемент? точно также вы писали в #31 
<img width="787" alt="image" src="https://github.com/siriusdevs/homeworks_23/assets/67689833/a5c5a0f1-0f5b-4e92-a69e-0b4ccf08aecf">

2023-10-31 15:44 UTC, nazaroviktor2 commented on hw1.py
> +Salaries = list[float, ...]
почитай
https://docs.python.org/3/library/typing.html#annotating-tuples

2023-10-31 15:48 UTC, nazaroviktor2 commented on hw1.py
> +Salaries = list[float, ...]
> так троеточие разве не означает, что у меня будет несколько элементов типа float в списке, а не один элемент? точно также вы писали в #31 <img alt="image" width="787" src="https://user-images.githubusercontent.com/67689833/279429732-a5c5a0f1-0f5b-4e92-a69e-0b4ccf08aecf.png">

Это для кортежа означает не один элемент. Для списков нельзя указывать аннотацию из нескольких элементов

2023-10-31 19:16 UTC, lifelongCat commented on hw1.py
> +    return sum(top_salaries) / sum(all_salaries) * 100
готово

2023-10-31 19:21 UTC, lifelongCat commented on hw1.py
> +Salaries = list[float, ...]
хорошо, исправил

2023-10-31 19:52 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/ac049f6d-6ddd-42fa-b7ae-83a2ca412322)

2023-11-06 11:13 UTC, lifelongCat commented
@Max2288

2023-11-06 11:14 UTC, lifelongCat commented
@KatyaGotskina
@annashutova
@Max2288 
@kirillsev1
@radugaboost

2023-11-06 11:20 UTC, nazaroviktor2 commented on hw1.py
> +    if sum(all_salaries) == 0:
можно получается теперь избавится от этой проверки

2023-11-06 11:26 UTC, lifelongCat commented on hw1.py
> +    if sum(all_salaries) == 0:
а разве не лучше подробно выводить ошибки?
всё-таки один из случаев когда вообще ничего не подали, а второй - когда зарплаты по 0, то есть их подали

2023-11-06 11:42 UTC, nazaroviktor2 commented on hw1.py
> +    if sum(all_salaries) == 0:
Почему нет, ладно

2023-11-06 11:47 UTC, Max2288 approved these changes

2023-11-07 11:38 UTC, siriusdevs approved these changes

2023-11-07 11:38 UTC, merged