Danilov_hw1
siriusdevs/homeworks_23 pull request #53
Opened 2023-10-30 21:03 UTC by ilya-danilov

2023-10-31 09:35 UTC, kirillsev1 commented on hw1.py
> +from typing import Optional, Tuple
Не надо импортировать Tuple, используй встроенный tuple

2023-10-31 09:36 UTC, kirillsev1 commented on hw1.py
> +def negative_salary_error(staff) -> Exception:
Функция не возвращает Exception. Она вызывает срабатывание ошибки, а возвращает None

2023-10-31 09:39 UTC, kirillsev1 commented on hw1.py
> +            negative_salary_error(staff)
Если у тебя хотя бы один department вызовет ошибку, то программа остановиться, хотя в остальных department все может быть нормально. Тоже самое, что и тут[https://github.com/siriusdevs/homeworks_23/pull/48]

2023-10-31 09:46 UTC, kirillsev1 commented
По заданию:
`Все числа в выводе функции округлять до второго знака после запятой.`
В коде не видел строк с округлением

2023-10-31 09:58 UTC, kirillsev1 requested changes

2023-10-31 09:58 UTC, kirillsev1 commented on hw1.py
> +    departments: dict[str, dict[str, int]],
Внимательнее с входными данными...
`...значением для названия отдела служит словарь с именами сотрудников (str) в качестве ключей и зарплатами (float) в качестве значений .`

2023-10-31 09:58 UTC, kirillsev1 commented on hw1.py
> +    average_salaries = [sorted_salary for sorted_salary, _ in average_salaries]
Можно использовать не average_salaries.items(), а keys() и values(). Так не надо будет лишний раз проходить по словарю

2023-10-31 09:58 UTC, kirillsev1 commented on test_hw1.py
> +    get_departments_rating(invalid_test_data)
В функции рейзишь ValueError, значит и тут тоже надо проверять ValueError

2023-10-31 09:58 UTC, kirillsev1 commented on hw1.py
> +            average_salaries[department] = round(sum(salaries) / lenth, 2)
На None делить нельзя, как и на 0

2023-10-31 21:15 UTC, ilya-danilov commented on hw1.py
> +            negative_salary_error(staff)
Имеется ввиду проверять зарплаты на неотрицательность, возвращать отделы удовлетворяющему этому условию и только после этого вызывать ошибку для отрицательной зарплаты или вовсе не вызывать ошибку для отрицательных зарплат в отделах и игнорировать эти отделы в возвращаемом результате?

2023-10-31 21:56 UTC, ilya-danilov commented on hw1.py
> +    average_salaries = [sorted_salary for sorted_salary, _ in average_salaries]
Но ведь в нашем случае lambda-функция принимает список кортежей из отделов и зарплат, а возвращает зарплаты, поэтому мы не можем в качестве сортируемых элементов указывать только отделы, т.к., опять же, lambda-функция не будет принимать зарплаты, а для того, чтобы она их принимала, в сортируемые элементы нужно передать эти самые зарплаты, что приведёт к тому, что мы обязаны после сортировки доставать из отсортированных отделов и зарплат только отделы.

2023-10-31 22:14 UTC, ilya-danilov commented on hw1.py
> +    departments: dict[str, dict[str, int]],
К предыдущему комментарию.
В 43 строке используется округление.

2023-11-01 09:02 UTC, siriusdevs commented on hw1.py
> +            negative_salary_error(staff)
у него ошибка связана с отрицательными зарплатами в исходных данных. 

я считаю, @ilya-danilov прав и нужно завершать с ошибкой программу. будет странно, если мы остальные отделы посчитаем правильно, а тут ... вернём что?... None? 0? почему? нет уж, пусть лучше ошибка

2023-11-01 12:59 UTC, ilya-danilov commented on hw1.py
> +    average_salaries = [sorted_salary for sorted_salary, _ in average_salaries]
Возможно путаница произошла из-за того, что у меня отсортированные элементы списка называются sorted_salaty (а не, например, sorted_departments).

2023-11-12 14:35 UTC, nazaroviktor2 requested changes
Молодец, но надо не много поправить

2023-11-12 14:35 UTC, nazaroviktor2 commented on hw1/hw1.py
> +        if not include_deps or department in include_deps:
Так как include_deps - это кортеж, то это проверка будет занимать O(n). Как насчет того, чтобы переделать include_deps в set? Тогда это проверка будет занимать O(1), в n раз быстрее)

2023-11-12 14:35 UTC, nazaroviktor2 commented on hw1/hw1.py
> +) -> tuple[list]:
Сейчас написано, что ты возвращаешь кортеж из одного списка. Правильная аннотация будет tuple[list,list]

2023-11-12 14:35 UTC, nazaroviktor2 commented on hw1/hw1.py
> +    include_deps: Optional[tuple[str]] = None,
Сейчас написано, что include_deps кортеж из одной строки. Правильная аннотация будет tuple[str, ...]

2023-12-09 12:33 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/c6c2edeb-e4ba-4a7b-aa5a-61b067c4b007)

2023-12-16 09:07 UTC, nazaroviktor2 requested changes

2023-12-16 09:07 UTC, nazaroviktor2 commented on hw1/hw1.py
> +    included_deps = set(included_deps)
```suggestion
    included_deps = set(included_deps) if included_deps is not None else set()
```

2023-12-16 09:07 UTC, nazaroviktor2 commented on hw1/hw1.py
> +    included_deps = set(included_deps)
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/5313631f-a237-47ab-bf2a-0f5a4df5d342)

2023-12-20 16:01 UTC, nazaroviktor2 approved these changes

2023-12-21 16:25 UTC, kirillsev1 approved these changes

2023-12-22 19:32 UTC, kirillsev1 approved these changes

2023-12-26 12:06 UTC, merged