Komarov hw2
siriusdevs/homeworks_23 pull request #54
Opened 2023-11-06 12:15 UTC by k0marov

@nazaroviktor2, добавил т. н. "unreal" решение :)

2023-11-07 08:34 UTC, Max2288 submitted a review, later dismissed

2023-11-08 13:40 UTC, nazaroviktor2 requested changes
Очень хорошая работа, молодец. 
Но у тебя задании написано, что должна быть основная функция "process_data". 
Еще обсудили с @siriusdevs и пришли к тому, что ваши основные функции должны обрабатывать все ошибки. То есть при вызове основной функции я не должен видеть ничего красного в консоли.
На данный момент у тебя нет обработки, если файл не найден и на некорректные данные, добавь, пожалуйста

2023-11-08 13:40 UTC, nazaroviktor2 commented on hw2/const.py
> +import typing
Зачем импортировать весь typing? Может хватит только Any from typing

2023-11-08 13:40 UTC, nazaroviktor2 commented on hw2/unreal_hw2.py
> +import pandas as pd
Тебе нужно поменять cosnt и pandas местами по pep8

https://peps.python.org/pep-0008/#imports

Импорт следует сгруппировать в следующем порядке:

1. Импорт стандартной библиотеки.
2. Соответствующий импорт третьих сторон.
3. Импорт, специфичный для локального приложения/библиотеки.

2023-11-08 13:40 UTC, nazaroviktor2 commented on hw2/unreal_hw2.py
Супер круто) Все задание в 15 строчках )

2023-11-08 13:40 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    return [user['age'] for user in users]
Если передали не корректные данные и у пользователя не будет age?

2023-12-06 21:14 UTC, siriusdevs approved these changes

2023-12-08 12:38 UTC, siriusdevs approved these changes

2023-12-08 12:38 UTC, siriusdevs commented
Komarov hw2

2023-12-08 12:38 UTC, merged