Kristev HW1
siriusdevs/homeworks_23 pull request #55
Opened 2023-11-07 06:46 UTC by KristevT

2023-11-07 08:37 UTC, Max2288 commented on hw1.py
> +    for department in departments.keys():
https://realpython.com/iterate-through-dictionary-python/
Почитай пожалуйста, как лучше итерироваться по словарям и что с этим делать

2023-11-11 12:45 UTC, nazaroviktor2 requested changes
Есть замечание не большое, а так молодец

2023-11-11 12:45 UTC, nazaroviktor2 commented on hw1.py
> +    top3_least_paid = sorted(avg_salaries.items(), key=lambda srt: srt[1])[:3]
Тут ты сортируешь два раза. Это достаточно труда затратно. Попробуй один раз отсортировать, а потом работать со срезами

2023-11-14 10:41 UTC, nazaroviktor2 submitted a review, later dismissed
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/f1d9665d-5bbd-4711-aeba-7d4b949facda)

2023-11-30 17:05 UTC, siriusdevs requested changes

2023-11-30 17:05 UTC, siriusdevs commented on hw1.py
> +                avg_salary = round(sum(salaries) / len(salaries), 2)
если выполняется else, то сумма считается два раза. или считайте её один раз и записывайте в переменную, которую будете использовать, или проверку делайте в условном выражении проверку на пустоту salaries,  а не на сумму.

2023-12-19 12:02 UTC, merged