Trofimov hw_1
siriusdevs/homeworks_23 pull request #56
Opened 2023-11-07 07:03 UTC by sementrof

2023-11-07 08:30 UTC, Max2288 commented on hw1.py
> +    salary_ratio = round(((sum(maximum_salary) / sum(main_list)) * 100), 2)
если придёт пустой departaments на вход, сумма main_list = 0 и будет ошибка

2023-11-07 08:31 UTC, Max2288 commented on hw1.py
> +        tuple
кортеж чего ?

2023-11-09 07:48 UTC, sementrof commented on hw1.py
> +    salary_ratio = round(((sum(maximum_salary) / sum(main_list)) * 100), 2)
@Max2288

2023-11-11 12:57 UTC, nazaroviktor2 requested changes

2023-11-11 12:57 UTC, nazaroviktor2 commented on .DS_Store
Что это за файл?

2023-11-11 12:57 UTC, nazaroviktor2 commented on .github/workflows/pylint.yml
> +      run: python3 test_hw1.py
Должны запускаться тесты в репозитории, а не код тестов

2023-11-11 12:57 UTC, nazaroviktor2 commented on hw1.py
> +def salary(*departments: tuple, maxs: Optional[int] = None) -> tuple:
Приходит tuple из чего? Возвращается что именно? 
Дополни аннотацию

2023-11-11 12:57 UTC, nazaroviktor2 commented on hw1.py
> +            raise ValueError('all salaries are zero')
Зачем? У тебя есть первый отдел будет получать 0 (например отдел стажеров), а другие будут, что то получать. То ты вернешь ошибку

2023-11-11 12:57 UTC, nazaroviktor2 commented on hw1.py
> +        if isinstance(department[1], dict):
Ну если ты так решил проверять. То почему ты уверен, что второй аргумент вообще будет?

2023-11-11 12:57 UTC, nazaroviktor2 commented on hw1.py
> +    for department in departments:
`for department, employees in departments:`

2023-11-11 12:57 UTC, nazaroviktor2 commented on hw1.py
> +        maxs = max(main_list)
Зачем? Если тебе нужно переменная не None, то есть константа float('inf')

2023-11-11 12:57 UTC, nazaroviktor2 commented on hw1.py
> +    side_list = [round(num, 2) for num in main_list if num <= maxs]
Мы можем вынести проверку и округления в момент добавления в main_list  ?

2023-11-17 10:56 UTC, sementrof commented on hw1.py
> +    side_list = [round(num, 2) for num in main_list if num <= maxs]
не можем, так как будет ошибка

2023-11-17 11:04 UTC, nazaroviktor2 commented on hw1.py
> +    side_list = [round(num, 2) for num in main_list if num <= maxs]
> не можем, так как будет ошибка
Какая?

2023-11-24 19:45 UTC, sementrof commented on hw1.py
> +    side_list = [round(num, 2) for num in main_list if num <= maxs]
зачем усложнять ?, на данный момент разделены на блоки

2023-11-25 12:51 UTC, nazaroviktor2 commented on hw1.py
> +    side_list = [round(num, 2) for num in main_list if num <= maxs]
Так будет ошибка или мы что то усложняем?
Что именно усложняем? Если перенести проверку то сложность наоборот меньше станет, мы избавимся от лишних итерацией по списку.
Кто разделены на блоки? На какие блоки?

2023-12-08 14:44 UTC, sementrof commented on hw1.py
> +    side_list = [round(num, 2) for num in main_list if num <= maxs]
сделал проверку и округление в момент добавления в main_list

2023-12-08 14:46 UTC, sementrof commented on hw1.py
> +    side_list = [round(num, 2) for num in main_list if num <= maxs]
@nazaroviktor2, @Max2288

2023-12-09 12:39 UTC, nazaroviktor2 requested changes
Поправь сгенерированные докстринги

2023-12-09 12:39 UTC, nazaroviktor2 commented on hw1.py
> +from typing import Optional, Tuple, Union
Tuple можно ен импортировать. просто пиши `tuple`

2023-12-09 12:39 UTC, nazaroviktor2 commented on hw1.py
> +        Tuple[list[float], Union[int, float]]: _description_
_description_   ?????

2023-12-11 08:51 UTC, sementrof commented on hw1.py
> +        Tuple[list[float], Union[int, float]]: _description_
@nazaroviktor2 всё исправил

2023-12-16 06:18 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/8aaa7602-1fcc-46ee-81ce-d1fc503d68a4)

2023-12-19 13:04 UTC, merged