Argun
siriusdevs/homeworks_23 pull request #57
Opened 2023-11-11 21:28 UTC by anonimys2020

2023-11-11 21:30 UTC, anonimys2020 reviewed
Completed Homework Assignment. Added files: hw1.py, test_hw1.py.

2023-11-12 13:27 UTC, nazaroviktor2 requested changes
Молодец, но нужно не много поправить

2023-11-12 13:27 UTC, nazaroviktor2 commented on hw1.py
> +from typing import List, Tuple
С версии python 3.9  можно не импортировать List, Tuple from typing. просто пиши list

2023-11-12 13:27 UTC, nazaroviktor2 commented on hw1.py
> +        ) -> Tuple[List[Tuple[str, float]], List[Tuple[str, float]]]:
кортеж двух списков, из кортежей строки и числа?

2023-11-12 13:27 UTC, nazaroviktor2 commented on hw1.py
> +        if department not in excluded_departments:
Так как excluded_departments - это список, то это проверка будет занимать O(n). Как насчет того, чтобы переделать  excluded_departments в set? Тогда это проверка будет занимать O(1), в n раз быстрее)

2023-11-12 13:27 UTC, nazaroviktor2 commented on hw1.py
> +            average_salary = sum(salaries) / len(salaries) if salaries else 0
если salaries = [0,0,0,0]  - будет ошибка

2023-11-12 13:27 UTC, nazaroviktor2 commented on hw1.py
> +            salaries = [salary for salary in employees.values()]
Зачем вообще нужна эта переменная? Можно же просто общаться к employees.values()

2023-11-12 13:27 UTC, nazaroviktor2 commented on hw1.py
> +    return top_3_highest, top_3_lowest
можно тогда лучше возвращать кортеж из двух словарей?

2023-12-16 06:34 UTC, nazaroviktor2 requested changes
при вызове главной функции пользователь не должен видеть ошибки в консоли. Ты можешь их обрабатывать и возвращать сообщение об ошибки( не рейзить ошибку! rerutn {"msg": "some error" } )

2023-12-16 06:34 UTC, nazaroviktor2 commented on hw1.py
> +    return (top_3_highest, top_3_lowest)
Можно не оборачивать в скобки

2023-12-16 06:34 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    online_status = {'<2 days': 0, '1 week': 0, '1 month': 0, '6 months': 0, '>6 months': 0}
Ключи лучше выносить в переменную

2023-12-16 06:34 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(input_file, 'r') as file:
Если файл не найден?

2023-12-16 06:34 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        json.dump(result, out_file, indent=2)
Если конечный путь не найден? 
см. makedirs

2023-12-16 06:34 UTC, nazaroviktor2 commented on hw2/hw2.py
> +def process_data(input_file: str, output_file: str) -> None:
при вызове главной функции пользователь не должен быть ничего красного в консоли

2023-12-20 09:10 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/e70f68b6-b907-4eae-a1c5-d19bc354e3a3)

2023-12-21 16:16 UTC, nazaroviktor2 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/1928c81f-242e-4a38-b6fd-7e0b8838a61d)

2023-12-21 16:26 UTC, kirillsev1 requested changes
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/f9e8dcfc-400d-4bed-8d25-d28646db38ce)

2023-12-21 19:23 UTC, kirillsev1 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/96af4db1-bfa1-4d78-b4ae-79d5748a413c)
Надо было под каждую дз новый пулл реквест создать

2023-12-21 19:59 UTC, kirillsev1 requested changes
Со второй все нормально, 3 исправляй

2023-12-21 19:59 UTC, kirillsev1 commented on hw3/hw3.py
> +        return self._year
Это только геттеры, нет сеттеров

2023-12-21 19:59 UTC, kirillsev1 commented on hw3/hw3.py
> +        return self._name
только геттер

2023-12-21 19:59 UTC, kirillsev1 commented on hw3/hw3.py
> +        reader.borrow_book(library, book)
Мне кажется, что библиотекарь не должен должен использовать читателя в себе, этом должна заниматься библиотека

2023-12-22 10:05 UTC, anonimys2020 commented
Не могу понять на что ругается в hw1.py. Остальное всё вроде норм.
![image](https://github.com/siriusdevs/homeworks_23/assets/59397551/92535c11-c405-4357-a0a6-daac07191d9d)

2023-12-22 10:11 UTC, Max2288 commented
> Не могу понять на что ругается в hw1.py. Остальное всё вроде норм. ![image](https://private-user-images.githubusercontent.com/59397551/292460830-92535c11-c405-4357-a0a6-daac07191d9d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNDAwMzQsIm5iZiI6MTcwMzIzOTczNCwicGF0aCI6Ii81OTM5NzU1MS8yOTI0NjA4MzAtOTI1MzVjMTEtYzQwNS00MzU3LWEwYTYtZGFhYzA3MTkxZDlkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDEwMDg1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhZjY5ZDYyZTQxZmUxNTlkYTNhM2IyMTExNDE0NmM0ZDU3NzJlYTYyYWUxNTM1Yzk4NTEwYmU0ZmMyMGUxZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.46kkACva7K4uhE93ua2l4ciBeWNcwbpQXtnZCGQhTnQ)

https://github.com/peterjc/flake8-rst-docstrings/issues/18 - посмотри тут

2023-12-22 10:21 UTC, anonimys2020 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/59397551/4b2484f6-a051-46d7-8da7-745bb931b47a)

2023-12-24 09:13 UTC, kirillsev1 requested changes
Все остальное нормально

2023-12-24 09:13 UTC, kirillsev1 commented on hw1.py
> +            average_salary = sum(employees.values()) / len(employees.values()) \
ZeroDivisionError

2023-12-24 09:13 UTC, kirillsev1 commented on hw3/hw3.py
> +
Нет методов:
`Выдать книгу читателю`
`Принять книгу от читателя`

Мне кажется стоит добавить в библиотеку библиотекаря и реализовать выдачу книги через него

2023-12-24 09:48 UTC, closed without merging