Telegin
siriusdevs/homeworks_23 pull request #58
Opened 2023-11-13 10:14 UTC by TeleginSergey

2nd homework. 1st try. Have a good day!

2023-11-14 10:32 UTC, nazaroviktor2 commented on hw1.py
ты же уже сдавал первую домашку. Что это за файл?

2023-11-14 10:35 UTC, nazaroviktor2 requested changes

2023-11-14 10:35 UTC, nazaroviktor2 commented on hw2.py
> +        raise EmptyFileError(input_path)
обсудили с @siriusdevs и пришли к тому, что ваши основные функции должны обрабатывать все ошибки. То есть при вызове основной функции я не должен видеть ничего красного в консоли.

2023-11-14 12:01 UTC, TeleginSergey commented on hw1.py
Хоршо, удалю, я думал надо оставить

2023-11-14 12:06 UTC, TeleginSergey commented on hw2.py
> +        raise EmptyFileError(input_path)
а как лучше будет обрабатывать? Например, программа не нашла файл, она должна его создать или просто закончиться и все?

2023-11-14 14:16 UTC, nazaroviktor2 commented on hw1.py
Ты мержишь в main)

2023-11-14 14:19 UTC, nazaroviktor2 commented on hw2.py
> +        raise EmptyFileError(input_path)
Если нет файла с данными, то верни какой то текст. Если нет файла для сохранения, то создай

2023-12-09 18:16 UTC, TeleginSergey commented
Не понимаю, почему файлы hw2.py, test_hw2.py  и директория test_folde лежат не в hw2.py, хотя в локалке нормально. Также не проходят тесты. Прошу о помощи.

2023-12-15 21:13 UTC, nazaroviktor2 requested changes
Молодец, но по заданию тестовые данные должны быть файлах

2023-12-15 21:13 UTC, nazaroviktor2 commented on hw1.py
Не надо удалять первую домашку, сначала ты мерж кинул в main, поэтому и написал. Сейчас удалять не надо

2023-12-15 21:13 UTC, nazaroviktor2 commented on hw2/hw2.py
> +def check_path(input_path: str, output_path: str) -> tuple[str]:
`tuple[str, str]:`

2023-12-15 21:13 UTC, nazaroviktor2 commented on hw2/test_hw2.py
> +TEST_DIFFERENT_ARGUMENTS = (
тестовые данные должны быть в файлах

2023-12-15 21:13 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        output_path = 'default_output.json'
https://docs-python.ru/standart-library/modul-os-python/funktsija-makedirs-modulja-os/

2023-12-20 14:23 UTC, closed without merging