Zorina Ekaterina
siriusdevs/homeworks_23 pull request #59
Opened 2023-11-15 09:18 UTC by drain678

2023-11-16 07:25 UTC, nazaroviktor2 requested changes
При вызове основной функции (process_data) я не должен видеть ничего красного в консоль

2023-11-16 07:25 UTC, nazaroviktor2 commented on hw2.py
> +        online_stats['great than 6 months'] += 1
Лучше все ключи выносить в константы. Чтобы потом не ошибаться

2023-11-16 07:25 UTC, nazaroviktor2 commented on hw2.py
> +        update_online_stats(online_stats, time_online, month, six_months)
Если такие ключи не найдены ? Или записаны не в том формате ?

2023-11-16 07:25 UTC, nazaroviktor2 commented on hw2.py
> +    with open(data_file, 'rt') as inp_f:
Если файл не найден?

2023-11-16 07:25 UTC, nazaroviktor2 commented on hw2.py
> +    with open(output_file, 'w') as out_f:
Если конечный путь не найден?

2023-11-17 10:33 UTC, nazaroviktor2 requested changes

2023-11-17 10:33 UTC, nazaroviktor2 commented on hw2.py
> +        'great than 6 months': 0,
Тут тоже наверное стоит переписать ключи на переменных

2023-11-17 10:33 UTC, nazaroviktor2 commented on hw2.py
> +    with open(output_file, 'w') as out_f:
Вот это не поправила

2023-11-17 10:33 UTC, nazaroviktor2 commented on hw2.py
> +        with open(data_file, 'rt') as inp_f:
Если файл не найден? Именно файл, а не строка

2023-11-17 12:39 UTC, drain678 commented on hw2.py
> +        with open(data_file, 'rt') as inp_f:
То есть надо библиотеку os использовать, чтобы это проверить?

2023-11-17 12:40 UTC, nazaroviktor2 commented on hw2.py
> +        with open(data_file, 'rt') as inp_f:
Да

2023-11-18 07:55 UTC, drain678 commented on hw2.py
> +        'great than 6 months': 0,
А может без переменных? Просто иначе у меня ошибка от flake8 вот такая: WPS210 Found too many local variables: 13 > 8 и я пока не знаю как их вместить. Или может эти переменные и сам словарь вынести за функцию и использовать global? Хотя, я вроде слышала, что так не очень хорошо делать

2023-11-18 14:13 UTC, drain678 commented on hw2.py
> +    with open(output_file, 'w') as out_f:
А разве тут не должен создаваться новый файл, если который передали, не существует?

2023-11-18 17:42 UTC, nazaroviktor2 commented on hw2.py
> +        'great than 6 months': 0,
Попробуй сделать отдельный файл, например config.py и туда вынести переменные. 
Думаю эти переменный можно делать глобальными

2023-11-18 17:43 UTC, nazaroviktor2 commented on hw2.py
> +    with open(output_file, 'w') as out_f:
> А разве тут не должен создаваться новый файл, если который передали, не существует?

Да нужно создавать, я просто этого вроде нет

2023-11-19 08:46 UTC, drain678 commented on hw2.py
> +    with open(output_file, 'w') as out_f:
Параметр 'w' это делает. Если файл с указанным именем уже существует, то он будет перезаписан. Если файла с таким именем нет, то будет создан новый файл. Так что я думаю тут ему все равно найден конечный путь или нет на самом деле., поэтому я так сделала

2023-11-19 08:47 UTC, drain678 commented on hw2.py
> +        'great than 6 months': 0,
Глобальные - нельзя. flake8 говорит: "WPS420 Found wrong keyword: global"

2023-11-19 09:01 UTC, nazaroviktor2 commented on hw2.py
> +    with open(output_file, 'w') as out_f:
Попробуй передать путь с не существующими папками и ты поймешь, что я имею ввиду.
"some1/some2/choto/1/file.json"

2023-11-19 09:04 UTC, nazaroviktor2 commented on hw2.py
> +        'great than 6 months': 0,
У тебя же в тестах есть глобальные переменные и flake не ругается. 
Вот пример у Комарова https://github.com/siriusdevs/homeworks_23/blob/506f1e350bd40d1f78dbee779ea9f9f4f0facd97/hw2/const.py

2023-11-19 09:28 UTC, drain678 commented on hw2.py
> +    with open(output_file, 'w') as out_f:
Поняла, переделаю

2023-11-22 12:19 UTC, nazaroviktor2 requested changes
Тебе надо вынести вторую домашку в отдельную папку. Так написано в задании " Вынести домашнее и его тесты в отдельную папку hw2."

2023-11-22 12:19 UTC, nazaroviktor2 commented on hw2.py
> +    with open(output_file, 'w') as out_f:
Вот это не поправила (или я не вижу где)

2023-11-23 10:12 UTC, drain678 commented on hw2.py
> +    with open(output_file, 'w') as out_f:
Я это в тестах написала, чтобы файл вывода сразу же там менялся при обнаружении, что он плох

2023-11-25 12:56 UTC, nazaroviktor2 commented on hw2.py
> +    with open(output_file, 'w') as out_f:
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/52425e16-38de-44a7-9576-7a40dc3e8f8f)

2023-11-25 12:57 UTC, nazaroviktor2 commented on hw2.py
> +    with open(output_file, 'w') as out_f:
Причем тут тесты? 
При вывозе функции, если конечный путь не создан, он должен создаваться 
https://docs-python.ru/standart-library/modul-os-python/funktsija-makedirs-modulja-os/

2023-11-25 13:00 UTC, nazaroviktor2 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/d325ecce-f180-4aae-a2fb-632c10432834)

2023-11-30 17:07 UTC, drain678 commented
> ![image](https://private-user-images.githubusercontent.com/45715124/285592513-d325ecce-f180-4aae-a2fb-632c10432834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzNjQwOTEsIm5iZiI6MTcwMTM2Mzc5MSwicGF0aCI6Ii80NTcxNTEyNC8yODU1OTI1MTMtZDMyNWVjY2UtZjE4MC00YWFlLWEyZmItNjMyYzEwNDMyODM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDE3MDMxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YjU0OGM2NDRmOTJkYjZlYTZjMDk0YzFlZGIzMTZkNjg5ZTM0ZDc0ZGNjNTUxNWM2M2YxNGVjNjdhYjU2MGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NaE-WwV5-oabQJoPV1NB9I9YR3UDnFGuuWUJdTZh4UY)

2023-11-30 17:10 UTC, drain678 commented
Что то я не туда нажала. Зотела скрин прикрепить, что у меня такой ошибки нет при вызове функции.
<img width="968" alt="Снимок экрана 2023-11-30 в 20 09 43" src="https://github.com/siriusdevs/homeworks_23/assets/114409592/22244095-4b21-4538-88b6-6c2f25859766">

2023-11-30 17:12 UTC, siriusdevs requested changes

2023-11-30 17:50 UTC, drain678 commented on hw2/hw2.py
> +        online_stats[config.GT_SIX_MONTHS] += 1
не знаю

2023-12-06 21:19 UTC, siriusdevs commented
все коммиты назывались нормально, и в конце что-то пошло не так. не сдавайтесь, делайте хорошо всегда. надеюсь, в будущем такого не увижу.

2023-12-06 21:19 UTC, siriusdevs approved these changes

2023-12-09 12:04 UTC, merged