Vasilenko
siriusdevs/homeworks_23 pull request #6
Opened 2023-09-30 11:50 UTC by akiko23

2023-09-30 20:36 UTC, annashutova requested changes

2023-09-30 20:36 UTC, annashutova commented on hw1.py
> +    yield f'{lowests_percent_of_all_salaries}%'
использование генератора, конечно, не возбранялось, но он тут не совсем уместен, вдруг нам понадобится взять только часть статистики (например зарплаты или процент), по генератору придется итерироваться, а через `return` можно просто вернуть значения, в кортеже, например.

2023-09-30 20:46 UTC, akiko23 commented on hw1.py
> +    all_salaries = list(filter(lambda salary: salary <= limit, all_salaries))
Чтобы проверить условие перед добавлением, мне нужно будет делать цикл в цикле (можно передавать и отфильтрованные зп компрехеншном, но операций будет столько же) и проверять каждую salary. Разве ассимптотика при этом не та же самая?

2023-09-30 20:51 UTC, akiko23 commented on hw1.py
> +    three_lowest_salaries = sorted(all_salaries)[:3]
Как? Вы предлагаете сразу сортировать список во время его инициализации? (впринципе можно искать каждый раз индекс при добавлении новой зп)

2023-09-30 20:55 UTC, akiko23 commented on hw1.py
> +    yield f'{lowests_percent_of_all_salaries}%'
Np, специально так сделал, т.к задачи составлены, мягко говоря, поверхностно и об этом не уточнялось

2023-09-30 20:56 UTC, annashutova commented on hw1.py
> +    all_salaries = list(filter(lambda salary: salary <= limit, all_salaries))
ну сейчас у тебя и так цикл в цикле из-за extend, так как он итерируется по списку при добавлении, а ты при проходке по списку можешь сразу фильтровать значения, и в фильтре не будет необходимости, ведь он опять будет проходиться по списку, это уже будет целый лишний цикл

2023-09-30 21:09 UTC, annashutova commented on hw1.py
> +    three_lowest_salaries = sorted(all_salaries)[:3]
при итерировании по зп можешь завести переменные для топа, и при каждой новой итерации сравнивать текущую зп с лежащими в переменных и после цикла уже положить их в список

2023-09-30 21:13 UTC, akiko23 commented on hw1.py
> +    all_salaries = list(filter(lambda salary: salary <= limit, all_salaries))
![image](https://github.com/siriusdevs/homeworks_23/assets/101889433/5355dcd9-1d13-4568-a3e4-cbfc8d50657c)
До этого, кстати, так и сделал (1-й коммит), линтер не пропустил самый лучший, оптимизированный вариант с итератором ((
hw1.py:28:5: WPS426 Found `lambda` in loop's body

2023-09-30 21:17 UTC, annashutova commented on hw1.py
> +    all_salaries = list(filter(lambda salary: salary <= limit, all_salaries))
красотой иногда приходится жертвовать))

2023-09-30 21:20 UTC, siriusdevs commented on hw1.py
> +    yield f'{lowests_percent_of_all_salaries}%'
>> Функция должна возвращать..

Написано же, возвращать. Ничего про генераторы или ещё что-то не было сказано. Только задание - вернуть несколько значений. Если возникают вопросы по заданиям, задавайте их

2023-09-30 21:20 UTC, akiko23 commented on hw1.py
> +    all_salaries = list(filter(lambda salary: salary <= limit, all_salaries))
Кстати, приятно удивлен, что в extend можно передать генераторное выражение (arr.extend(salary for salary in salaries if salary <= limit)), fixed✅

2023-09-30 21:22 UTC, akiko23 commented on hw1.py
> +    for _, employees_data in departments.items():
Fixed✅

2023-09-30 21:22 UTC, siriusdevs commented on hw1.py
> +    yield f'{lowests_percent_of_all_salaries}%'
> Np, специально так сделал, т.к задачи составлены, мягко говоря, поверхностно и об этом не уточнялось

Задание:
> Функция должна возвращать..
Написано же, возвращать. Ничего про генераторы или ещё что-то не было сказано. Только задание - вернуть несколько значений. Если возникают вопросы по заданиям, задавайте их

2023-09-30 21:36 UTC, akiko23 commented on test_hw1.py
> +test_salaries = (
Fixed✅

2023-09-30 21:40 UTC, akiko23 commented on hw1.py
> +    three_lowest_salaries = sorted(all_salaries)[:3]
Возможно, я вас недопонял. Вы предлагаете создать три переменных для топа?

2023-09-30 21:54 UTC, akiko23 commented on hw1.py
> +    yield f'{lowests_percent_of_all_salaries}%'
Fixed✅

2023-10-01 06:18 UTC, nazaroviktor2 commented on hw1.py
> +from typing import Any, Dict, Generator, Iterable, Optional
С версии python 3.9 Dict можно не импортировать из typing. https://peps.python.org/pep-0585/
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/3bb2a02b-3474-4b38-b472-2c37d595aaaf)

2023-10-01 06:19 UTC, nazaroviktor2 commented on hw1.py
> +) -> Generator[Iterable | str, Any, Any]:
Почему ты возвращаешь генератор ?

2023-10-01 06:38 UTC, nazaroviktor2 commented on hw1.py
> +            are the names of the employees and values are their salaries.
В докстрингаг не нужен перенос строки \. Если ты хочешь написать много текста к одному аргументу
```
 Args:
        departments (dict): # enter
            dict of the keyword arguments where the keys # нет \
            are the names of the departments and the values
            are the dicts of the employees where the keys
            are the names of the employees and values are their salaries.

```

Мой вариант 
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/d70027d0-168e-4196-9772-e3933a39ef11)

Текущий вариант 
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/dc8490d6-26ed-493a-8f60-0b8780f54056)

2023-10-01 06:40 UTC, akiko23 commented on hw1.py
> +) -> Generator[Iterable | str, Any, Any]:
Раньше возвращал, забыл сменить тайпхинт. Fixed✅

2023-10-01 06:41 UTC, akiko23 commented on hw1.py
> +from typing import Any, Dict, Generator, Iterable, Optional
Fixed✅

2023-10-01 06:47 UTC, nazaroviktor2 commented on hw1.py
> +        of the three lowest salaries
Почему 3 самые низкие зп?

2023-10-01 06:59 UTC, akiko23 commented on hw1.py
> +        of the three lowest salaries
Уточнял у преподавателя, сказал нужно 3 самые низкие

2023-10-01 07:05 UTC, akiko23 commented on hw1.py
> +            are the names of the employees and values are their salaries.
В вашем варианте ругается линтер: hw1.py:16:1: RST301 Unexpected indentation.
16 строка это
             dict of the keyword arguments where the keys # нет \

2023-10-01 08:22 UTC, akiko23 commented on hw1.py
> +    three_lowest_salaries = sorted(all_salaries)[:3]
Оптимизировал, в одном цикле теперь находится сразу сумма и три самые низкие зп. Fixed✅

2023-10-01 09:00 UTC, siriusdevs commented on hw1.py
> +        of the three lowest salaries
Да, последние три зарплаты в компании по размеру - это три самые низкие зп. Всё верно.

2023-10-01 09:01 UTC, annashutova requested changes

2023-10-01 09:09 UTC, akiko23 commented on hw1.py
> +        for salary in tuple(sal for sal in salaries if sal <= limit):
Fixed✅

2023-10-01 10:02 UTC, nazaroviktor2 submitted a review, later dismissed
Молодец 👍

2023-10-01 10:02 UTC, nazaroviktor2 commented on hw1.py
> +    lowest_sals[2] = salary
Ультра мега харош @akiko23 👍

2023-10-01 10:13 UTC, annashutova commented
Хорошая работа) дальше отправляем тебя в открытое плавание

2023-10-01 10:14 UTC, annashutova approved these changes
Хорошая работа) дальше отправляем тебя в открытое плавание

2023-10-01 16:58 UTC, siriusdevs approved these changes

2023-10-02 10:35 UTC, akiko23 commented
Не бейте)
Пропустил ошибку с тайпхинтами: у кейвордов нужно указывать только тайпхинт значения аргумента (логично, ведь имя/ключ в любом случае будет str)

2023-10-02 11:06 UTC, nazaroviktor2 approved these changes
Молодец, что сам заметил ошибку и исправил ее

2023-10-02 11:39 UTC, annashutova approved these changes

2023-10-04 09:13 UTC, merged