Ivanov_I HW1
siriusdevs/homeworks_23 pull request #60
Opened 2023-11-16 08:14 UTC by agent-ilyusha

2023-11-17 10:41 UTC, nazaroviktor2 commented
Почему ты свою домашку делал в main ветке?

2023-11-17 10:42 UTC, nazaroviktor2 commented
У тебя конфликты, надо их поправить

2023-11-20 20:56 UTC, agent-ilyusha commented
В своем репозитории я делал в main, но pull я делаю вроде в свою ветку. А с readme, что не так?

2023-11-20 21:02 UTC, agent-ilyusha commented
все, поправил

2023-11-22 12:23 UTC, nazaroviktor2 commented
> В своем репозитории я делал в main, но pull я делаю вроде в свою ветку. А с readme, что не так?

Мне кажется нужно было делать в своей ветке.
@siriusdevs

2023-11-22 12:46 UTC, nazaroviktor2 requested changes

2023-11-22 12:46 UTC, nazaroviktor2 commented on hw1.py
> +from typing import List, Tuple
с версии python 3.9 можно не импортировать List, Tuple from typing. Просто пиши list, tuple

2023-11-22 12:46 UTC, nazaroviktor2 commented on hw1.py
> +        ) -> Tuple[List[float], List[float]]:
Тут не должно быть пробелов. 


```
def three_max_selaries(
    list_salary: list[float],
    cap_salary: float,
) -> tuple[list[float], list[float]]:
```

2023-11-22 12:46 UTC, nazaroviktor2 commented on hw1.py
> +
```suggestion
    if salary_cap is None:
        salary_cap = float("inf")
    list_all_salaries = [salary for salary in list_all_salaries if  0 < salary <= salary_cap]
```

2023-11-22 12:46 UTC, nazaroviktor2 commented on hw1.py
> +    *args: Tuple[str, List[float]],
почему args? Тебе же приходят отделы одной компании, почему не назвать departments или company ?

2023-11-28 19:42 UTC, agent-ilyusha commented
Все исправил

2023-11-30 17:13 UTC, siriusdevs commented
По-прежнему конфликты

2023-12-01 20:29 UTC, agent-ilyusha commented
Вроде все

2023-12-02 10:59 UTC, nazaroviktor2 commented on hw1.py
> +from typing import List, Tuple
не поправил

2023-12-02 10:59 UTC, nazaroviktor2 commented on hw1.py
> +        ) -> Tuple[List[float], List[float]]:
не поправил

2023-12-02 11:00 UTC, nazaroviktor2 requested changes
Коментарии не поправил

2023-12-04 08:30 UTC, nazaroviktor2 requested changes

2023-12-04 08:30 UTC, nazaroviktor2 commented on hw1.py
> +                )
тут лишний таб, скобка должна закрываться на том же уровне на котором открылась 
```suggestion
    if salary_cap is not None:
        list_three_max_salaries, list_all_salaries = three_max_selaries(
            list_all_salaries,
            salary_cap,
        )
```

2023-12-04 08:30 UTC, nazaroviktor2 commented on hw1.py
> +    list_all_salaries = [salary for salary in list_all_salaries if salary >= 0]
```suggestion

    if salary_cap is None:
        salary_cap = float("inf")
    list_all_salaries = [salary for salary in list_all_salaries if  0 < salary <= salary_cap]
    list_all_salaries.sort(reverse=True)
    max3 = list_all_salaries[:3]
```

2023-12-04 09:45 UTC, agent-ilyusha commented on hw1.py
> +    list_all_salaries = [salary for salary in list_all_salaries if salary >= 0]
я выенс в отдельную функцию, так как flake жаловался

2023-12-09 12:44 UTC, nazaroviktor2 commented on hw1.py
> +    list_all_salaries = [salary for salary in list_all_salaries if salary >= 0]
Можно перенести на другую строчку 
```
    list_all_salaries = [
        salary for salary in list_all_salaries 
        if  0 < salary <= salary_cap
    ]

```

2023-12-16 06:37 UTC, nazaroviktor2 commented on hw1.py
> +    list_all_salaries = [salary for salary in list_all_salaries if salary >= 0]
Это не поправил @agent-ilyusha

2023-12-19 12:26 UTC, agent-ilyusha commented on hw1.py
> +    list_all_salaries = [salary for salary in list_all_salaries if salary >= 0]
так я изменил эту строчку

2023-12-20 02:13 UTC, siriusdevs commented
По-прежнему выполнено не в той ветке. И зачем тут папка .trunk?

2023-12-21 10:19 UTC, closed without merging