solved hw2 homework, sorted everything by dirs, added workflows
siriusdevs/homeworks_23 pull request #62
Opened 2023-11-20 08:58 UTC by fedya-eremin

2023-11-22 17:49 UTC, fedya-eremin commented
review me, daddy 🥺👉👈

2023-11-25 13:07 UTC, nazaroviktor2 commented
> gl

hf

2023-11-25 13:10 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(src_file, "r") as input_json:
Если файл не найден?

2023-11-25 13:19 UTC, nazaroviktor2 requested changes
Молодец, но надо не много поправить.

Еще твоя основная функция должна обрабатывать все ошибки, то есть при вызове ее ничего не должно быть красного в консоли.

2023-11-25 13:19 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(src_file, "r") as input_json:
Если файл не найден?

2023-11-25 13:19 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(dst_file, "x") as output_json:
Если конечный путь не найден?

2023-11-25 13:19 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    result_ages.update({"median_age": statistics.median(ages)})
Ключи лучше выносить в отдельные переменные, чтобы не опечататься в название

2023-11-25 13:19 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        year = users[user]["registered"]
если нет ключа registered?

2023-11-25 13:19 UTC, nazaroviktor2 commented on hw2/hw2.py
> +            years.update({year: 1})
```suggestion
        if year in years:
            years[year] += 1
        else:
            years[year] = 1
```

2023-11-25 13:19 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    result_ages.update({"average_age": sum(ages) / len(ages)})
если len(ages) = 0

2023-11-25 13:19 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        years.update({elem: (years.get(elem, 0) / count_of_years) * 100})
years[### 
```suggestion
        years[elem] = (years.get(elem, 0) / count_of_years) * 100
```

2023-11-27 10:03 UTC, fedya-eremin commented
то есть, функция должна вообще все исключения перехватывать?

2023-11-27 10:08 UTC, fedya-eremin commented on hw2/hw2.py
> +            years.update({year: 1})
флейк запрещает (wps529) :(

2023-11-27 10:09 UTC, fedya-eremin commented on hw2/hw2.py
> +            years.update({year: 1})
хотя по хорошему, выключить бы это правило

2023-11-27 10:24 UTC, fedya-eremin commented on hw2/hw2.py
> +    with open(src_file, "r") as input_json:
точнее, не в соответствии с документацией

2023-11-30 13:30 UTC, fedya-eremin commented
поправил все штуки с ошибками и добавил тестов

2023-11-30 17:17 UTC, siriusdevs approved these changes

2023-12-02 10:46 UTC, nazaroviktor2 requested changes
Почему везде используешь update со словарем? 
 Другие ребята просто общались по ключи и flake у них вроде не ругался

2023-12-02 10:46 UTC, nazaroviktor2 commented on hw2/hw2.py
> +            years.update({year: 1})
А на какой именно строчке?
Скорее всего он хочет чтобы было написано так
`if years.get(year)`
так выглядит правильнее

2023-12-02 10:46 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(dst_file, "x") as output_json:
Это не исправлено (или я не вижу)
попробуй передать dst_file = "some1/som2/suda/json.json"
руками папку не создавай

2023-12-02 10:46 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    result_ages.update({MEDIAN_AGE: statistics.median(ages)})
result_ages[MAX_AGE] =  max(ages)
и так далее
очень страшно выглядит...

2023-12-03 09:58 UTC, fedya-eremin commented
> Почему везде используешь update со словарем? Другие ребята просто общались по ключи и flake у них вроде не ругался

потому что с update мне нет необходимости проверять наличие ключа и, следовательно, обрабатывать ошибки)

2023-12-04 07:55 UTC, nazaroviktor2 submitted a review, later dismissed
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/d2b1331a-30ff-4ee4-b8d8-168b323d8fc0)

2023-12-07 11:57 UTC, fedya-eremin commented
Уже не делю 🤠

2023-12-12 12:00 UTC, siriusdevs approved these changes

2023-12-12 12:01 UTC, merged