Inozemtsev hw2
siriusdevs/homeworks_23 pull request #63
Opened 2023-11-25 14:06 UTC by bliinmaker

2023-12-02 11:10 UTC, nazaroviktor2 requested changes
Очень хорошо, молодец. Не большие замечания

2023-12-02 11:10 UTC, nazaroviktor2 commented on .DS_Store
Что это за файл?

2023-12-02 11:10 UTC, nazaroviktor2 commented on hw2/generate_stats.py
> +        res_dict[text_key] = dict_stats
Может перенести это в первый if?

2023-12-02 11:10 UTC, nazaroviktor2 commented on hw2/generate_stats.py
> +    if user_data in dict_stats.keys():
можно 
`if dict_stats.get(user_data):`

2023-12-02 11:10 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    count_users = len(file_data.keys())
len(file_data)

2023-12-02 11:10 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(output_file, 'w') as result_file:
если конечный путь не найден?
"/some1/som2/test/test.json"

https://docs-python.ru/standart-library/modul-os-python/funktsija-makedirs-modulja-os/

2023-12-09 12:49 UTC, nazaroviktor2 approved these changes
Удали файлы в остальном мне все нравится, молодец
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/5164ffaa-7504-4fa1-8623-48e67bfb3b65)

2023-12-09 12:49 UTC, nazaroviktor2 commented on .DS_Store
Его надо удалить

2023-12-09 12:49 UTC, nazaroviktor2 commented on hw2/.DS_Store
И этот файл тоже

2023-12-14 10:47 UTC, siriusdevs commented
делит на 0 :crying_cat_face:

2023-12-14 10:48 UTC, siriusdevs requested changes

2023-12-14 10:48 UTC, siriusdevs commented on hw2/generate_stats.py
> +        dict_stats[user_data] += 1 / count_users * 100
ZeroDivisionError

2023-12-15 09:10 UTC, siriusdevs approved these changes

2023-12-15 09:10 UTC, merged