Druzhinin HW1
siriusdevs/homeworks_23 pull request #64
Opened 2023-11-27 11:16 UTC by agent-yandex

2023-12-02 11:23 UTC, nazaroviktor2 requested changes
Очень хорошо, молодец. Есть небольшие замечания

2023-12-02 11:23 UTC, nazaroviktor2 commented on hw1.py
> +from typing import Tuple
С версии python3.9 можно не импортировать tuple, dict from typing

2023-12-02 11:23 UTC, nazaroviktor2 commented on hw1.py
> +    all_salaries = [salary for workers in departments.values() for salary in workers.values()]
ты можешь сюда добавить limit, чтобы лишний раз не идти по списку
`all_salary = [salary for workers in departments.values() for salary in workers.values() if salary <= limit]
`

2023-12-02 11:23 UTC, nazaroviktor2 commented on hw1.py
> +    percent = round(sum(top) / sum(all_salaries) * 100, 2)
если  sum(all_salaries) = 0?

2023-12-02 11:36 UTC, agent-yandex commented on hw1.py
> +from typing import Tuple
У меня если не импортировать flake ругается

2023-12-02 11:46 UTC, agent-yandex commented on hw1.py
> +    all_salaries = [salary for workers in departments.values() for salary in workers.values()]
А какой смысл, если в дальнейшем все равно понадобится список из всех зарплат, чтобы считать процент. Если уберу повторный проход по списку в `filter_top_salaries` нужно будет снова проходится по словарю и доставать все значения

2023-12-04 07:58 UTC, nazaroviktor2 commented on hw1.py
> +from typing import Tuple
Скинь ошибку. Я думаю ругается на, что то другое, потому что у всех остальных ребят на это не ругаетс

2023-12-16 06:39 UTC, nazaroviktor2 approved these changes
![Uploading image.png…]()

2023-12-19 12:31 UTC, merged