Zagora HW2
siriusdevs/homeworks_23 pull request #65
Opened 2023-12-01 10:43 UTC by nnnhurt

2023-12-02 11:43 UTC, nazaroviktor2 requested changes
Молодец, но есть не большие замечания

2023-12-02 11:43 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(input_file_json, 'r') as config:
если файл не найден?

2023-12-02 11:43 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(output_file_json, 'w') as output:
если конечный путь не найден? 
https://docs-python.ru/standart-library/modul-os-python/funktsija-makedirs-modulja-os/

2023-12-02 11:43 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        quantity_hosts.update({host: f'{quantity} %'})
quantity_hosts[host] = f'{quantity} %'

2023-12-02 11:43 UTC, nazaroviktor2 commented on hw2/hw2.py
> +            raise NoRequiredDataException('No lastlogins')
Наверное была правильно такое сообщение выводить 
NoRequiredDataException('No last_logins') - чтобы было более понятно какого именно ключа не хватает. 
То ты ищешь один ключ, а говоришь что нет другого

2023-12-02 11:43 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        if information[user]['last_login'].count('-') == 2:
это не совсем верная проверка для времени
я могу передать такое  "1 - dsdsdsds - d3qdadsadsadsada", "231321--32131232" - и оно пройдет проверку

2023-12-02 11:43 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        'more_half_year_online': 0,
Ключи лучше выносить в константы, чтобы в дальнейшем не ошибиться в написании и легко изменять

2023-12-02 11:43 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        new_user_lastlogin.append(datetime.date(*list(map(int, login_date.split('-')))))
очень страшно
и если передам такую строку "--2131321321321312" будет ошибка

2023-12-05 06:32 UTC, nnnhurt commented on hw2/hw2.py
> +        'more_half_year_online': 0,
можно ли сделать через перечисление StrEnum?

2023-12-09 12:55 UTC, nazaroviktor2 submitted a review, later dismissed
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/ca29c1af-29ca-459b-b923-b14418c9f087)

2023-12-12 11:59 UTC, siriusdevs commented
Деление на ноль :crying_cat_face:

2023-12-14 11:46 UTC, merged