add main & test
siriusdevs/homeworks_23 pull request #66
Opened 2023-12-04 12:24 UTC by VikaPaz

hw1

2023-12-06 09:52 UTC, kirillsev1 commented
Надо назвать правильно файлы, и написать тесты

2023-12-06 09:53 UTC, kirillsev1 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/0de2ab46-de9c-40c2-b0c5-cdd851be5692)

Надо сделать workflows

2023-12-06 10:04 UTC, kirillsev1 requested changes

2023-12-06 10:04 UTC, kirillsev1 commented on main.py
> +        sl_min (int or None): maximum salary limit.
maximum != min
min == minimum

2023-12-06 10:04 UTC, kirillsev1 commented on main.py
> +                departs[num][1][name] = sl
Что такое sl? sl - это зарплата?

2023-12-12 19:39 UTC, VikaPaz commented on main.py
> +                departs[num][1][name] = sl
Да, это salary. Сократила до sl, т.к. по flake не проходило.

2023-12-14 22:03 UTC, kirillsev1 commented
Файлы должны называться hw1.py и test_hw1.py

2023-12-14 22:04 UTC, kirillsev1 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/abb7f262-4906-4c47-8749-e812c3d30520)
workflows все еще не работают

2023-12-14 22:08 UTC, kirillsev1 requested changes
Код написан нормально, надо поменять имена файлов и сделать workflows

2023-12-15 11:48 UTC, VikaPaz commented
А что не так с названиями?

2023-12-15 12:05 UTC, VikaPaz commented
как запустить workflows? 
![изображение](https://github.com/siriusdevs/homeworks_23/assets/100610578/ebe40428-45c1-4b6e-8379-1b978bb5aa54)
я в настройках свою ветку указала, но вот не сильно помогло..

2023-12-15 12:39 UTC, kirillsev1 commented
![image](https://github.com/siriusdevs/homeworks_23/assets/112825746/1f2470cc-8b23-4c06-9afe-f994e2f0e3be)
Помогло. Теперь исправь Линтер

2023-12-20 06:14 UTC, kirillsev1 submitted a review, later dismissed

2023-12-20 11:59 UTC, siriusdevs requested changes

2023-12-20 11:59 UTC, siriusdevs commented on hw1.py
> +    return sum(list(dp[1].values())) / len(dp[1])
ZeroDivisionError

2023-12-21 14:51 UTC, kirillsev1 requested changes
Так, в 1 дз исправить ZeroDivisionError, во 2 дз поменять переменные, в 3 убрать вызовы ошибок

2023-12-21 14:51 UTC, kirillsev1 commented on hw2.py
> +hosts_count = {}
Эти переменные надо назвать по другому(LEN_MONTH), потому что это константы

2023-12-21 14:51 UTC, kirillsev1 commented on test_hw2.py
> +    assert result == data
Нужны докстринги

2023-12-21 14:51 UTC, kirillsev1 commented on test_hw1.py
> +    assert result == expected_result
Нужны докстринги

2023-12-21 14:51 UTC, kirillsev1 commented on test_hw3.py
> +    assert course.teacher == teacher
Нет докстирнгов, если так оставить, то будет очень много докстирнгов, можешь объединить тесты по сущностям, например тест для студента, там будет проверятся все, что с ним связано

2023-12-21 14:51 UTC, kirillsev1 commented on hw3.py
> +        self._course_name = new_name
Не надо рейзить ошибки. siriusdevs просил сделать чистую консоль, можешь выводить ошибки в один файл, для сбора логов

2023-12-22 15:33 UTC, siriusdevs approved these changes

2023-12-22 15:33 UTC, merged