Kuznetsova hw1
siriusdevs/homeworks_23 pull request #69
Opened 2023-12-08 19:13 UTC by pimparampimpim

2023-12-09 13:06 UTC, nazaroviktor2 requested changes
Молодец. Есть несколько замечаний

2023-12-09 13:06 UTC, nazaroviktor2 commented on hw1.py
> +                check(min_salary, float, 'min_salary')
я бы вынес эту проверку из цикла. Зачем нам каждый раз проверять, что пришел нужный формат

2023-12-09 13:06 UTC, nazaroviktor2 commented on hw1.py
> +            super_total_salary += salary
Вот это тоже надо запихнуть в проверку на min_salary. Так как в итоге ты учитываешь зарплаты выше придела в подсчете процента, а это делать ну нужно

2023-12-09 13:06 UTC, nazaroviktor2 commented on hw1.py
> +            check(salary, float, 'salary')
а если зп пришло int? Мы же можем это обработать
P.s isinstance - может принимать массив типов

2023-12-09 16:31 UTC, siriusdevs commented on test_hw1.py
> +        'Alberto Tenigini': 2000.99,
:-1:

2023-12-11 08:43 UTC, pimparampimpim commented on hw1.py
> +            check(salary, float, 'salary')
@nazaroviktor2, исправила все ошибки, проверь

2023-12-11 08:43 UTC, pimparampimpim commented on hw1.py
> +            super_total_salary += salary
в этом и есть задумка эта переменная используется для подсчета всех зарплат без каких либо ограничений вроде

2023-12-15 20:42 UTC, nazaroviktor2 commented on hw1.py
> +        check(min_salary, float, 'min_salary')
min salary тоже может быть int

2023-12-15 20:52 UTC, nazaroviktor2 requested changes
Нужно немного поправить

2023-12-15 20:52 UTC, nazaroviktor2 commented on hw1.py
> +        check(min_salary, float, 'min_salary')
min salary тоже может быть int

2023-12-15 20:52 UTC, nazaroviktor2 commented on hw1.py
> +        raise TypeError(f'{value_name} type is not {value_type.__name__}')
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/f3f6241f-0dd3-4f38-8b17-58baf83cc10a)

2023-12-15 20:52 UTC, nazaroviktor2 commented on hw1.py
> +def check(value_to_check: Any, value_type: type, value_name: str) -> None:
value_type - теперь это наверное список/ кортеж из типов. надо поменять название, аннотацию и докстринги

2023-12-15 20:52 UTC, nazaroviktor2 commented on hw1.py
> +            super_total_salary += salary
_"Этот аргумент - числовой предел, ниже которого зарплаты учитывать не нужно."_
Если зарплата ниже, то ее не надо учитывать вообще

2023-12-15 21:40 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/22e31e11-8120-4dd7-a55d-3cf737c535f7)

2023-12-15 21:40 UTC, nazaroviktor2 commented on hw1.py
> +            super_total_salary += salary
super_total_salary тоже в if

2023-12-15 21:40 UTC, nazaroviktor2 commented on hw1.py
> +            super_total_salary += salary
А еще лучше после этого for

2023-12-15 21:40 UTC, nazaroviktor2 commented on hw1.py
> +            super_total_salary += salary
```suggestion
        for name, salary in departament.items():
            check(name, str, 'name')
            check(departament_name, str, 'department_name')
            check(salary, (float, int), 'salary')
            salary = round(salary, 2)
            if min_salary is None or salary >= min_salary:
                total_salary += salary
        super_total_salary += total_salary
```

2023-12-16 09:24 UTC, siriusdevs approved these changes

2023-12-16 09:25 UTC, merged