Tarasov
siriusdevs/homeworks_23 pull request #7
Opened 2023-09-30 13:11 UTC by developer-mixa

2023-10-01 06:53 UTC, nazaroviktor2 requested changes
Где решение ?

2023-10-01 06:53 UTC, nazaroviktor2 commented
Пожалуйста, не кидайте пустые мержи

2023-10-01 08:52 UTC, developer-mixa commented
Я случайно, извиняюсь
--
Отправлено из Mail.ru для Android воскресенье, 01 октября 2023г., 09:53 +03:00 от nazaroviktor2  ***@***.*** :

>Пожалуйста, не кидайте пустые мержи
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2023-10-01 08:52 UTC, developer-mixa commented
Думал на своей ветке кинул
--
Отправлено из Mail.ru для Android воскресенье, 01 октября 2023г., 09:53 +03:00 от nazaroviktor2  ***@***.*** :

>Пожалуйста, не кидайте пустые мержи
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  @ github . com>

2023-10-01 19:52 UTC, nazaroviktor2 commented on hw1.py
> +from typing import Dict
С версии python 3.9 Dict можно не импортировать из typing. https://peps.python.org/pep-0585/
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/8455166c-6197-45cd-a3e4-652e6aedd2ea)

2023-10-02 12:38 UTC, nazaroviktor2 commented on hw1.py
> +def calculate_salary_stats(salary_limit: float = None, **kwargs: dict) -> dict[str, tuple]:
Нужно писать переменные, которые как можно точнее отражают информацию в ней. К тебе же приходят отделы одной компании. Почему не назвать переменную company или departments?

2023-10-02 12:40 UTC, nazaroviktor2 commented on hw1.py
> +        statistics[departament_name] = (top_salaries, all_to_top_salary)
Ты наверное не со всем понял задание. Тебе приходят отделы одной компании. У компании много отделов и тебе надо посчитать не топ 3 в каждом отделе, а топ 3 во всей компании. Топ 3 по всем отделам " Функция должна возвращать статистику: последние 3 зарплат в компании (по размеру), отношение суммы этих 3 зарплат ко всему размеру выплат в компании, в процентах"
Сейчас ты считаешь топ в каждом отделе, а надо во всей компании.

2023-10-02 12:41 UTC, nazaroviktor2 requested changes
Ты не много запутался в задание. Надо искать топ 3 во всей компании, а не в одном отделе

2023-10-03 12:52 UTC, annashutova requested changes
работа хорошая, но есть некоторые недочеты, учти их в следующих коммитах

2023-10-03 12:52 UTC, annashutova commented on hw1.py
> +        top_salaries = sorted(employees_salaries)[-3:][::-1]
у метода `sorted` есть один замечательный параметр `reverse`, по умолчанию он стоит в `False` и sorted делает сортировку по возрастанию, но ты можешь поставить его в True: `reverse=True`, и тогда список отсортируется по убыванию, и ты срезом сможешь взять первые 3 зарплаты и не предется ничего крутить, вертеть срезами.
про sorted можешь почитать тут: https://pythonstart.ru/osnovy/sorted-python

2023-10-03 12:52 UTC, annashutova commented on hw1.py
> +        all_to_top_salary = round(((all_top_salary / all_salary) * 100), 2)
если `all_salary` будет равняться 0, произойдет ошибка деления на 0, всегда учитывай такие моменты

2023-10-03 12:52 UTC, annashutova commented on test_hw1.py
> +vk_department = {
все константы в коде (что в основном, что в тестах) лучше называть через капс, по типу: VK_DEPARTMENT

2023-10-07 12:17 UTC, closed without merging