Krdyan
siriusdevs/homeworks_23 pull request #71
Opened 2023-12-10 08:50 UTC by MomusWinner

Запрашиваю у @siriusdevs разрешение на  изменение setup.cfg. 
WPS323 - Found % string formatting - для парсинга даты ('%Y-%m-%d').
WPS612 - Found useless overwritten method: init - для реализации абстрактного метода __init__.

2023-12-16 06:45 UTC, nazaroviktor2 requested changes
при вызове главной функции пользователь не должен видеть ошибки в консоли. Ты можешь их обрабатывать и возвращать сообщение об ошибки( не рейзить ошибку! rerutn {"msg": "some error" } )

2023-12-16 06:45 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        json.dump(output, output_file)
Если конечный путь не найден? 
см makedirs

2023-12-17 14:28 UTC, nazaroviktor2 submitted a review, later dismissed
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/b5010c2f-19f6-46b8-97fd-eafcadb3c6c1)

2023-12-18 13:35 UTC, siriusdevs commented
> Запрашиваю у @siriusdevs разрешение на изменение setup.cfg. WPS323 - Found % string formatting - для парсинга даты ('%Y-%m-%d'). WPS612 - Found useless overwritten method: init - для реализации абстрактного метода **init**.

**разрешаю добавить WPS612**

2023-12-19 16:33 UTC, nazaroviktor2 approved these changes

2023-12-20 08:01 UTC, siriusdevs approved these changes

2023-12-20 08:01 UTC, merged