Romodanov hw3
siriusdevs/homeworks_23 pull request #75
Opened 2023-12-15 08:41 UTC by darvenommm

2023-12-15 08:42 UTC, darvenommm commented
Немного изменил настройки для flake8, там где посчитал нужным

2023-12-16 08:15 UTC, nazaroviktor2 requested changes
Обычно для тестов используют такую архитектуру: 
```
/appliccation
  ./moldule1
      ../file1.py
  ./module2
      ../file_some.py
/tests
  ./appliccation
    ../moldule1
        .../test_file1.py
    ../module2
        .../test_file_some.py
```

Директория тестов повторяет директорию приложения. Так проще ориентироваться в тестах

2023-12-16 14:16 UTC, darvenommm commented
> Обычно для тестов используют такую архитектуру:
> 
> ```
> /appliccation
>   ./moldule1
>       ../file1.py
>   ./module2
>       ../file_some.py
> /tests
>   ./appliccation
>     ../moldule1
>         .../test_file1.py
>     ../module2
>         .../test_file_some.py
> ```
> 
> Директория тестов повторяет директорию приложения. Так проще ориентироваться в тестах

2023-12-16 16:35 UTC, nazaroviktor2 requested changes
Прочитай задания еще раз, мне кажется ты не много запутался. 
Когда курс добавляется к  учителю, у  объекта курса появляется учителей.
Когда курс добавляется к студенту, у объекта курса к списку студентов добавляется еще один студент

2023-12-16 16:35 UTC, nazaroviktor2 commented on hw3/courses_owner/test_courses_owner.py
Это тест не вынес в папку тестов

2023-12-16 16:35 UTC, nazaroviktor2 commented on hw3/person/test_person.py
Это тест не вынес в папку тестов

2023-12-16 16:35 UTC, nazaroviktor2 commented on hw3/person/person.py
> +        super().__init__(**kwargs)
?

2023-12-16 16:35 UTC, nazaroviktor2 commented on hw3/courses_owner/courses_owner.py
> +import course.abstract_course as abstract_course
`from course.abstract_course import AbstractCourse` ?

2023-12-16 16:35 UTC, nazaroviktor2 commented on hw3/courses_owner/courses_owner.py
> +import course.abstract_course as abstract_course
`from course.abstract_course import AbstractCourse` ?

2023-12-16 16:35 UTC, nazaroviktor2 commented on hw3/courses_owner/courses_owner.py
> +        super().__init__(**kwargs)
?

2023-12-16 16:35 UTC, nazaroviktor2 commented on hw3/student/student.py
> +    def __init__(self, name: str, surname: str, age: int) -> None:
```
Студент
Поля:
Список курсов, которые студент изучает (массив или список объектов класса "Курс")
```

2023-12-16 16:35 UTC, nazaroviktor2 commented on hw3/teacher/teacher.py
> +    def __init__(self, name: str, surname: str, age: int) -> None:
Поля:
Список курсов, которые преподаватель ведет (массив или список объектов класса "Курс")

2023-12-16 16:35 UTC, nazaroviktor2 commented on hw3/courses_owner/courses_owner.py
> +        new_course.add_course_owner(self)
Почему когда в добавляю студенты курс для изучаю, я делаю его владельцем курса?????

2023-12-16 18:42 UTC, darvenommm commented on hw3/person/person.py
> +        super().__init__(**kwargs)
super используется для множественного наследования

2023-12-16 18:42 UTC, darvenommm commented on hw3/courses_owner/courses_owner.py
> +        super().__init__(**kwargs)
super используется для множественного наследования

2023-12-16 18:44 UTC, darvenommm commented on hw3/student/student.py
> +    def __init__(self, name: str, surname: str, age: int) -> None:
То что у студента есть курсы, которые он проходит, не обязывает меня их сразу передавать при инициализации

2023-12-16 18:45 UTC, darvenommm commented on hw3/teacher/teacher.py
> +    def __init__(self, name: str, surname: str, age: int) -> None:
Аналогично как у студентов, не обязан передавать курсы при создании объекта

2023-12-16 18:48 UTC, darvenommm commented on hw3/courses_owner/courses_owner.py
> +import course.abstract_course as abstract_course
Пришлось так написать из-за кольцевой зависимости

2023-12-16 18:48 UTC, darvenommm commented on hw3/courses_owner/courses_owner.py
> +import course.abstract_course as abstract_course
Пришлось так написать из-за кольцевой зависимости

2023-12-16 18:57 UTC, darvenommm commented on hw3/courses_owner/courses_owner.py
> +        new_course.add_course_owner(self)
Тут смысл такой, что у курса может быть много участников: учителя, студенты, проверяющие или помощники по ведению курсу (последние два условны, для примера). И я их грубо обозвал владельцами курса, так как они в каком-то смысле ими владеют.

Но соглашусь название не лучшее, могу заменить на participant вместо owner.

2023-12-16 18:59 UTC, darvenommm commented on hw3/courses_owner/courses_owner.py
> +import course.abstract_course as abstract_course
CoursesOwner использует AbstractCourse и, в тот же момент, AbstractCourse использует CoursesOwner

2023-12-17 15:48 UTC, nazaroviktor2 requested changes

2023-12-17 15:48 UTC, nazaroviktor2 commented on hw3/courses_owner/courses_owner.py
> +import course.abstract_course as abstract_course
Когда происходит кольцевая зависимость, значит вероятнее всего нарушился [принцип инверсии зависимостей ](https://web-creator.ru/articles/solid_the_dependency_inversion_principle).
Почему у тебя абстрактный класс курсов, зависит от другого абстрактного класса course owner?
Может сделать у курсов переменную owner где храниться имя владельца или объект владельца ? 
CourseOwner -> CourseWithParticipant(Course) - добавить поле participant где хранить имена | обьекты владельцев

2023-12-17 15:48 UTC, nazaroviktor2 commented on hw3/courses_owner/courses_owner.py
> +        super().__init__(**kwargs)
тут снова нет наследования

2023-12-17 15:48 UTC, nazaroviktor2 commented on hw3/courses_owner/courses_owner.py
> +        new_course.add_course_owner(self)
Написал выше

2023-12-17 15:48 UTC, nazaroviktor2 commented on hw3/student/student.py
> +    def __init__(self, name: str, surname: str, age: int) -> None:
Окей

2023-12-17 16:22 UTC, nazaroviktor2 commented
Вот смотри еще у одного человека задания как у тебя https://github.com/siriusdevs/homeworks_23/pull/81
Для меня у него реализация выглядит по проще (читабельнее), а у тебя как будто нарушается [KISS](https://habr.com/ru/articles/249639/)

2023-12-18 18:16 UTC, darvenommm commented on hw3/person/person.py
> +        super().__init__(**kwargs)
Так как я могу быть уверен, что по цепочке наследования следующим классом будет именно object, а не, например, CoursesOwner (CoursesParticipant)

2023-12-18 18:19 UTC, darvenommm commented on hw3/courses_owner/courses_owner.py
> +        super().__init__(**kwargs)
Написал выше

2023-12-18 18:34 UTC, darvenommm commented on hw3/courses_owner/courses_owner.py
> +import course.abstract_course as abstract_course
Написал в самом низу

2023-12-18 18:35 UTC, darvenommm commented
> Вот смотри еще у одного человека задания как у тебя #81 Для меня у него реализация выглядит по проще (читабельнее), а у тебя как будто нарушается [KISS](https://habr.com/ru/articles/249639/)

Да моя работа, и вправду, выглядит сложнее, но этого всего лишь из-за того, что я положил одну и ту же логику добавления курсов для учителя и студента в единый класс CoursesParticipant (для принципа DRY).

А так я не пойму, чем моя работа хуже, если у него также есть циклическая зависимость Course <-> Teacher, Course <-> Student, а у меня CoursesParticipant <-> AbstractCourse.

Также не понимаю как мне создание отдельного класса CourseWithParticipant поможет в решение циклической зависимости, если Курсы могут добавлять участников, и Участники могут добавлять курсы. 
(В любом случае будут использовать друг друга для типизации и проверки типов в своих методах добавления).

2023-12-19 17:47 UTC, nazaroviktor2 commented
> Также не понимаю как мне создание отдельного класса CourseWithParticipant поможет в решение циклической зависимости, если Курсы могут добавлять участников, а Участники могут добавлять курсы. (В любом случае будут использовать друг друга для типизации и проверки типов (isinstance) в своих методах добавления).

Вроде у меня получилось сделать без циклического импорта, вот пример кода https://ya.cc/t/5LAogKkk4fSqkS
можешь проверить разбив каждый класс на файл

Тебя надо сделать абстрактный класс PersonWithCourse cо списком курсов из абстрактных курсов. У Course(AbsCourse) в аннотации указывать не Student, а PersonWithCourse

2023-12-20 12:31 UTC, darvenommm commented
@nazaroviktor2 

> Вроде у меня получилось сделать без циклического импорта, вот пример кода https://ya.cc/t/5LAogKkk4fSqkS
> можешь проверить разбив каждый класс на файл

Да, в данной реализации циклической зависимости нет, но есть много вещей, которые мне не нравятся, например, у Student и у Teacher один и тот же интерфейс для добавления и удаления курсов, который должен быть, по хорошему, перенесён в класс PersonWithCourses в виде абстрактных методов (Но сделать это не получиться, потому что появиться циклическая зависимость). 

К тому же в классе PersonWithCourses свойство courses публично, (чтобы можно было добавлять курсы в классе Course в методах add_student и set_teacher) хоть это плохо сказывается на инкапсуляции самого объекта (PersonWithCourses).

Вообще само задание, по моему мнению, сформулировано так, что без циклической зависимости нормально его написать будет невероятно сложно, поэтому не вижу проблемы просто проигнорировать это, ссылаясь на условие задачи.

2023-12-20 12:33 UTC, nazaroviktor2 commented
> 
> Да, в данной реализации циклической зависимости нет, но есть много вещей, которые мне не нравятся, например, у Student и у Teacher 

Согласен, что реализация не самое лучшее, просто быстро накидал один из вариантов. Насчёт задание возможно так и есть

2023-12-20 14:11 UTC, darvenommm commented
@nazaroviktor2 
Approval бы хотелось

2023-12-20 16:20 UTC, nazaroviktor2 commented on hw3/person/person.py
> +        super().__init__(**kwargs)
А как ты можешь быть уверен, что по цепочке наследования следующим класс будет принимать все kwargs?

2023-12-20 16:23 UTC, nazaroviktor2 commented
> @nazaroviktor2 Approval бы хотелось

Все началось с того, что мне не понравилось, что у тебя возникают циклические импорты, это исправлено?) 
Что хуже, циклический импорт, нарушение  SOLID или дублирование кода и нарушение DRY🧐? Мне кажется dry решается добавление еще одного промежуточного класса

2023-12-20 16:34 UTC, darvenommm commented
> Все началось с того, что мне не понравилось, что у тебя возникают циклические импорты, это исправлено?) Что хуже, циклический импорт, нарушение SOLID или дублирование кода и нарушение DRY🧐? Мне кажется dry решается добавление еще одного промежуточного класса

Ну, начнём с того, что Dependency inversion principle не нарушается так, как AbstractCourse и CoursesParticipant зависят не от конкретный реализаций (По типу Student, Teacher, Course), а от абстрактных классов (CoursesParticipant  и AbstractCourse соответственно). В моём коде присутствует только циклическая зависимость, что в данном случае, по моему мнению, не так страшно, хоть и не хорошо, но по другому как переписать, я не знаю (Предложенный тобой вариант не кажется мне лучше мною написанного).

А по поводу множественного наследования, не пойму, что мне нужно сделать. Я же не могу с полной уверенностью сказать какая у будет цепочка наследования у класса Student (Person -> CoursesParticipant или CouresParticipant -> Person), поэтому передаю kwargs.

2023-12-21 16:18 UTC, nazaroviktor2 commented
@kirillsev1 @KatyaGotskina @annashutova @radugaboost проверьте, пожалуйста, мерж. 
У нас возникли разногласия, так что прошу проверить вас

2023-12-21 16:47 UTC, k0marov commented
dreadful comments

2023-12-21 22:02 UTC, nazaroviktor2 approved these changes

2023-12-22 13:06 UTC, merged