Litvinov HW2
siriusdevs/homeworks_23 pull request #78
Opened 2023-12-16 20:30 UTC by EgorikA4

2023-12-17 15:58 UTC, nazaroviktor2 requested changes
Ты можешь их обрабатывать и возвращать сообщение об ошибки( не рейзить ошибку! rerutn {"msg": "some error" } )

Ты можешь декоратор, который будет `except Exception as error` и вместо рейзе это ошибки будет возвращать сообщение об ошибки `return f"Произошла ошибка {str(error)}"`

2023-12-17 15:58 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        raise InvalidFilePath(path_to_input_json)
при вызове главной функции пользователь не должен видеть ошибки в консоли.

2023-12-17 15:58 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        json.dump(users_stat, output_json)
если конечный путь не найден?
см makedirs

2023-12-19 16:27 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/7ff9595c-14ae-4983-8b80-6a5b15f55567)


Не большое замечание

2023-12-19 16:27 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        return None
В аннотации написано возвращаешь float

2023-12-19 16:41 UTC, nazaroviktor2 approved these changes

2023-12-20 07:56 UTC, siriusdevs approved these changes

2023-12-20 07:57 UTC, merged