added solution and tests for hw1
siriusdevs/homeworks_23 pull request #8
Opened 2023-09-30 14:52 UTC by fedya-eremin

- Updated .gitignore and setup.cfg to exclude venv/ directory
- Solved task and wrote tests
- Got so much fun out of it

2023-09-30 14:53 UTC, fedya-eremin commented
Pls assign me and put enhancement label

2023-10-01 07:05 UTC, nazaroviktor2 commented on hw1.py
> +from typing import Dict, Tuple
С версии python 3.9 Dict, Tuple можно не импортировать из typing. https://peps.python.org/pep-0585/
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/83fd1df7-c53f-47f4-a199-ca9a9a734e00)

2023-10-01 07:09 UTC, nazaroviktor2 commented on hw1.py
> +        kwargs: Dict[str, int] - dict of department names and their values.
dict of person names and their salareis.

_"а значение для аргумента - словарем, где **имена сотрудников** (str)
служат в качестве ключей, а зарплаты (float) - в качестве значений"_

2023-10-01 07:14 UTC, nazaroviktor2 commented on hw1.py
> +    for elem in kwargs.keys():
Чтобы идти по ключам не обязательно вызывать .keys() можно просто
`for elem in kwargs:`
Почему переменная называется elem? Ты же идешь по именам сотрудников, почему не назвать переменную name? нужно писать переменные, которые как можно точнее отражают информацию в ней

2023-10-01 07:17 UTC, nazaroviktor2 commented on hw1.py
> +    **kwargs: Dict[str, float],
Почему  kwargs ?  Это же отделы - departaments

2023-10-01 07:19 UTC, nazaroviktor2 commented on hw1.py
> +            cur_elem = kwargs[elem].values()
cur_elem это что? Здесь же ты получаешь все зарплаты в отделе - salaries

2023-10-01 07:30 UTC, nazaroviktor2 commented on test_hw1.py
> +from typing import Dict, Tuple
Тоже можно не импортировать

2023-10-01 07:32 UTC, nazaroviktor2 commented on hw1.py
> +            cur_avg = sum(cur_elem) / max(len(cur_elem), 1)
"Все числа в выводе функции округлять до второго знака после запятой"

2023-10-01 07:41 UTC, nazaroviktor2 commented on task_1
> +setup.cfg. Написать тесты. Проверка линтера и тесты должны работать в github workflows.
@siriusdevs функция должна возвращать "Функция должна возвращать статистику: топ-3
самых высокооплачиваемых отдела в компании и топ-3 самых низкооплачиваемых" - написано так, как будто надо возвращать название отделов, но дальше "Все числа в выводе функции округлять до второго знака после запятой" - какие числа? Вроде функция должна возвращать названия отделов(логично), а какие цифры тогда в выводе?

2023-10-01 07:42 UTC, nazaroviktor2 commented on setup.cfg
У тебя не venv ругался?

2023-10-01 07:43 UTC, nazaroviktor2 requested changes
Молодец, но надо не много поправить

2023-10-01 08:56 UTC, siriusdevs commented on task_1
> +setup.cfg. Написать тесты. Проверка линтера и тесты должны работать в github workflows.
Да, функция должна возвращать названия отделов. Часть про округление значений - для всех заданий общая, так вышло из-за способа генерации домашних заданий. Здесь чисел нет, всё нормально.

2023-10-01 11:18 UTC, fedya-eremin commented on setup.cfg
да, ввиду "особенностей" моей ОС не рекомендуется ставить пакеты в системный Python

2023-10-01 11:43 UTC, fedya-eremin commented on hw1.py
> +    for elem in kwargs.keys():
я бы с радостью, но линтер не пропустит :(
![image](https://github.com/siriusdevs/homeworks_23/assets/126074306/994c1670-ff0a-4e35-946c-abcff6da68f3)
![image](https://github.com/siriusdevs/homeworks_23/assets/126074306/e353ff93-ed65-431e-b72c-2afcde2a07b1)

2023-10-01 11:54 UTC, nazaroviktor2 commented on hw1.py
> +    for elem in kwargs.keys():
Окей оставь так как есть

2023-10-01 11:57 UTC, nazaroviktor2 submitted a review, later dismissed
Очень хорошо, молодец

2023-10-01 12:37 UTC, fedya-eremin commented
Доисправлял докстринги

2023-10-01 20:21 UTC, Max2288 commented on hw1.py
> +        if names is None or department in names:
Может is not None?

2023-10-01 20:31 UTC, fedya-eremin commented on hw1.py
> +        if names is None or department in names:
Нет, если names не передан, его содержимое не учитывается

2023-10-02 11:08 UTC, nazaroviktor2 approved these changes
Так держать

2023-10-02 15:25 UTC, KatyaGotskina approved these changes

2023-10-04 09:22 UTC, merged