complete hw3
siriusdevs/homeworks_23 pull request #81
Opened 2023-12-17 14:55 UTC by anonim767bn

copilot don't support me to write this code ;)

2023-12-17 15:05 UTC, anonim767bn commented
I wrote the code myself. the copilot would be turned off ;)

2023-12-17 16:19 UTC, nazaroviktor2 requested changes
Молодец, нужны не большие правки

2023-12-17 16:19 UTC, nazaroviktor2 commented on hw3.py
> +from typing import Any, List, Optional, Tuple
с версии python 3.9 можно не импортировать List Tuple, просто пиши list tuple

2023-12-17 16:19 UTC, nazaroviktor2 commented on setup.cfg
> +        WPS226
@siriusdevs 
Разбей классы на сколько файлов

2023-12-18 10:31 UTC, anonim767bn commented
@nazaroviktor2, ошибку  WPS226  из исключений убрал, List и Tuple заменил на list и tuple. И заменил тесты.

2023-12-18 15:11 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/97868d8b-6cc1-4753-9be6-987e930eefda)

2023-12-18 15:11 UTC, nazaroviktor2 commented on hw3.py
> +        types (tuple[type, ...]): The type to check against.
Это лишнее

2023-12-18 17:15 UTC, anonim767bn commented on hw3.py
> +        types (tuple[type, ...]): The type to check against.
@nazaroviktor2, без этого flake8 не проходит
./hw3.py:9:1: DAR101 Missing parameter(s) in Docstring: - check_positive
./hw3.py:9:1: DAR101 Missing parameter(s) in Docstring: - input_value
./hw3.py:9:1: DAR101 Missing parameter(s) in Docstring: - types

2023-12-18 17:22 UTC, anonim767bn commented on hw3.py
> +        types (tuple[type, ...]): The type to check against.
@nazaroviktor2, странно, я получил аппрув, но в моей ветке не появились файлы hw3.py и test_hw3.py

2023-12-19 11:14 UTC, nazaroviktor2 commented on hw3.py
> +        types (tuple[type, ...]): The type to check against.
> @nazaroviktor2, странно, я получил аппрув, но в моей ветке не появились файлы hw3.py и test_hw3.py

Надо подойти к Альберту Андреевичу и защитить домашку ему, если он ее примет, то смержит

2023-12-19 11:46 UTC, merged