hw3
siriusdevs/homeworks_23 pull request #82
Opened 2023-12-17 15:19 UTC by BBEDITE-IMUA

i don't use chatGpt and copilot

2023-12-17 16:08 UTC, nazaroviktor2 requested changes
Молодец. Не большие замечания

2023-12-17 16:08 UTC, nazaroviktor2 commented on hw3.py
> +from typing import Any, List
с версии python 3.9  можно не импортировать List из typing просто пиши list

2023-12-17 16:08 UTC, nazaroviktor2 commented on setup.cfg
> +        WPS214
@siriusdevs

2023-12-17 16:08 UTC, nazaroviktor2 commented on hw3.py
> +        check_type_of_input(price_value, float)
Цена не может быть int?

2023-12-17 16:08 UTC, nazaroviktor2 commented on setup.cfg
> +        WPS214
Раздели на несколько файлов

2023-12-19 10:21 UTC, BBEDITE-IMUA commented
@nazaroviktor2, исправил

2023-12-19 11:17 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/f5c3dc4f-fc72-4e71-8c7b-841f512e20dd)

2023-12-19 12:00 UTC, merged