Kuznetsova hw2
siriusdevs/homeworks_23 pull request #85
Opened 2023-12-19 09:13 UTC by pimparampimpim

2023-12-19 10:54 UTC, nazaroviktor2 requested changes
Молодец, не большие замечания

2023-12-19 10:54 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        if user['region'] in list(cities_dano):
Если пользователь не задал region? 
у словарей есть метод get(ключ, значение если не найдено)

2023-12-19 10:54 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    for ind, _ in enumerate(answer):
```suggestion
    for ind in range(len(answer)):
```

2023-12-19 10:54 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        date_len = TIME - datetime.strptime(user['last_login'], '%Y-%m-%d')
Если нет ключа last_login? Или он в неверном формате

2023-12-19 10:54 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        os.makedirs(op.dirname(file_path))
Наверное нет смысла создавать входной файл)

2023-12-19 10:54 UTC, nazaroviktor2 commented on hw2/hw2.py
> +            )
А вот если не найден конечный путь, куда нам надо записать, его можно создать

2023-12-19 10:54 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(dist_path, 'w') as lotfile:
если конечный путь не найден?

2023-12-19 10:59 UTC, pimparampimpim commented on hw2/hw2.py
> +    for ind, _ in enumerate(answer):
эта штучка так должна быть потому что flake8 видит неявнозаданную функцию enumerate
изначально так и было написано

2023-12-19 11:12 UTC, nazaroviktor2 requested changes

2023-12-19 11:12 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        answer[ind] = answer[ind] / len(list(dano)) * 100
А зачем приводить к list?  У словаря же тоже есть длинна

2023-12-19 11:12 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        answer[ind] = answer[ind] / len(list(dano)) * 100
Если передали пустой словарь будет ошибка

2023-12-19 11:22 UTC, pimparampimpim commented on hw2/hw2.py
> +        date_len = TIME - datetime.strptime(user['last_login'], '%Y-%m-%d')
done

2023-12-19 11:30 UTC, pimparampimpim commented on hw2/hw2.py
> +        answer[ind] = answer[ind] / len(list(dano)) * 100
dano не может быть пустым вроде

2023-12-19 11:38 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        answer[ind] = answer[ind] / len(list(dano)) * 100
Может, пример файла {}

2023-12-19 11:43 UTC, pimparampimpim commented on hw2/hw2.py
> +        if user['region'] in list(cities_dano):
Done

2023-12-19 17:24 UTC, pimparampimpim commented on hw2/hw2.py
> +        os.makedirs(op.dirname(file_path))
oke

2023-12-20 06:28 UTC, nazaroviktor2 requested changes

2023-12-20 06:28 UTC, nazaroviktor2 commented on hw2/hw2.py
> +            region = 'None'
```suggestion
       
        region = user.get('region', None)

```

2023-12-20 06:28 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        with open(dist_path, 'w') as out_file:
Если путь не найден?

2023-12-20 06:28 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        with open(dist_path, 'w') as empty_out_file:
Если путь не найден

2023-12-20 06:28 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(dist_path, 'w') as lotfile:
Это не поправила

2023-12-20 06:28 UTC, nazaroviktor2 commented on hw2/hw2.py
> +            date_len = timedelta(YEAR_TIME, MONTH_TIME, DAY_TIME)
```suggestion
        date_len = TIME - datetime.strptime(user.get('last_login', f"{YEAR_TIME}-{MONTH_TIME}-{DAY_TIME}"), '%Y-%m-%d')

```

2023-12-20 09:06 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/8f228fe4-67e9-44b8-af7d-148e4251bc15)

2023-12-20 09:11 UTC, merged