Blagodarova HW1
siriusdevs/homeworks_23 pull request #89
Opened 2023-12-19 13:15 UTC by alcutie

2023-12-19 17:02 UTC, nazaroviktor2 requested changes
Молодец, есть одно предложение

2023-12-19 17:02 UTC, nazaroviktor2 commented on hw1.py
> +        if department_names is None or name in department_names:
Смотри, у тебя department_names - typle. Проверка `name in department_names:` в этом случае будет занимать O(n)
Как насчет приводить department_names к set ? Тогда эта же проверка будет занимать O(1)- намного эффективнее

2023-12-19 17:41 UTC, alcutie commented on hw1.py
> +    average_salary = sum(all_salaries) / len(all_salaries)
случай, когда зарплат вообще нет проверяется выше, а это проверка на то, что подался список из нулей, что нелогично

2023-12-19 17:54 UTC, alcutie commented on hw1.py
> +        if department_names is None or name in department_names:
готово

2023-12-20 06:35 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/850445c0-0662-4809-a055-d15012b4f4c5)

2023-12-20 08:16 UTC, siriusdevs approved these changes

2023-12-20 08:16 UTC, merged