Otroschenko_hw1
siriusdevs/homeworks_23 pull request #91
Opened 2023-12-19 17:19 UTC by AntohaOt

2023-12-20 06:41 UTC, nazaroviktor2 requested changes
Молодец, не большое замечание

2023-12-20 06:41 UTC, nazaroviktor2 commented on hw1.py
> +                all_salaries.append(salary)
"Все числа в выводе функции округлять до второго знака после запятой. "
Это тоже надо округлить

2023-12-20 11:35 UTC, AntohaOt commented
@nazaroviktor2  Добрый день, добавил округление в выводе

2023-12-20 15:18 UTC, AntohaOt commented
@nazaroviktor2, сделал также 3-ю домашнюю работу, нужно ли создавать новый pull reques?

2023-12-20 16:10 UTC, nazaroviktor2 commented
> @nazaroviktor2, сделал также 3-ю домашнюю работу, нужно ли создавать новый pull reques?

Лучше создавать отдельный, только с третьей домашкой, но в твоих работах я не нашел замечаний, поэтому ставлю апрув на две домашки

2023-12-20 16:11 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/4431654b-147f-4513-996b-66cf697448b9)
На обе домашки

2023-12-21 13:32 UTC, siriusdevs approved these changes

2023-12-21 13:33 UTC, merged