Roganov HW2
siriusdevs/homeworks_23 pull request #94
Opened 2023-12-20 00:52 UTC by roganofff

3:52 am

2023-12-20 02:35 UTC, siriusdevs commented
you are **so** close to getting dreadful commits label.. hope i wont see more of these

2023-12-20 02:36 UTC, siriusdevs commented
@nazaroviktor2 we need a hw2 professional reviewer here :boxing_glove: :1st_place_medal:

2023-12-20 06:21 UTC, nazaroviktor2 requested changes
Молодец, есть небольшие замечания

2023-12-20 06:21 UTC, nazaroviktor2 commented on hw2/test_hw2.py
> +)
Тестовые данные должны быть в файлах

2023-12-20 06:21 UTC, nazaroviktor2 commented on .gitignore
> +hw2/src/outputs
Это тоже надо было запушить, если это результаты тестов. Я спулил твой проект, запускаю тесты, а у меня нет результатов тестирование. Мне придется их самим писать?

2023-12-20 06:21 UTC, nazaroviktor2 commented on hw2/json_parsing.py
> +    string = user_info[field]
Если у пользователя нет данного поля?

2023-12-20 06:21 UTC, nazaroviktor2 commented on hw2/json_parsing.py
> +        case 'email':
Case надо брать из  SEARCHING_REFERENCES

2023-12-20 06:21 UTC, nazaroviktor2 commented on hw2/json_parsing.py
> +            statistics_field[note] = round(statistics_field[note] / aggregate_attrs * 100, 2)
Может ли быть ошибка деления на 0?

2023-12-20 06:21 UTC, nazaroviktor2 commented on hw2/json_parsing.py
> +        for name, user_info in json_data.items():
Кажется не совсем логично, мы для каждого поля (2), идем по всем пользователям. Мне кажется, более логично для каждого пользователя идти по ключам

2023-12-20 08:01 UTC, roganofff commented on hw2/json_parsing.py
> +            statistics_field[note] = round(statistics_field[note] / aggregate_attrs * 100, 2)
В aggregate_attrs ноль будет, если json_data будет пустой. Это значит, что statistics_field не пополнится ни одним полем с годом или доменом почты и цикл с делением на ноль не выполнится ни разу

2023-12-20 08:55 UTC, roganofff commented on hw2/json_parsing.py
> +    string = user_info[field]
@nazaroviktor2

2023-12-20 08:55 UTC, nazaroviktor2 commented on hw2/json_parsing.py
> +    string = user_info[field]
Прости, не заметил

2023-12-20 10:25 UTC, roganofff commented on hw2/json_parsing.py
> +        for name, user_info in json_data.items():
А мне кажется, что удобнее для каждого поля найти их количество в пользователях и посчитать процентное соотношение.
Если для каждого пользователя считать его поля, то для вычисления процентов нужен будет ещё один отдельный цикл по пользователям, потому что после каждой итерации по пользователям посчитаны не все поля. Проще всё сделать под одним циклом, где мы сразу и считаем все совпадения по полям и проценты.

2023-12-20 10:36 UTC, roganofff commented on hw2/json_parsing.py
> +        for name, user_info in json_data.items():
@nazaroviktor2

2023-12-20 16:26 UTC, nazaroviktor2 commented on hw2/json_parsing.py
> +        for name, user_info in json_data.items():
Не совсем понял, где взял доп цикл и почему в твоей реализации стал один цикл, если их два 
>  Проще всё сделать под одним циклом, где мы считаем все совпадения по полям и сразу за ними проценты.

2023-12-20 16:34 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/b4c942ed-a96c-436b-a66a-da8ca94ac3b6)

2023-12-20 16:34 UTC, nazaroviktor2 commented on hw2/json_parsing.py
> +    with open(get_abspath(output_filename, 'outputs'), 'w') as output_file:
Тут тоже может быть не найден конечный путь, стоит тоже добавить makedirs

2023-12-20 16:34 UTC, nazaroviktor2 commented on hw2/json_parsing.py
> +    if not os.path.exists(input_abspath):
Тут нужна проверка, что это именно файл. exists - вернет true если передать папку.
Но в главной функции ты это обработаешь

2023-12-21 13:13 UTC, siriusdevs approved these changes

2023-12-21 13:14 UTC, merged