Nudga HW3
siriusdevs/homeworks_23 pull request #96
Opened 2023-12-20 11:44 UTC by Rubsun

config согласовал с @siriusdevs

2023-12-20 16:50 UTC, nazaroviktor2 requested changes
Молодец, есть небольшие замечания

2023-12-20 16:50 UTC, nazaroviktor2 commented on hw3/hw3.py
> +        self.accounts = accounts or []
На это не хватает гетеров

2023-12-20 16:50 UTC, nazaroviktor2 commented on hw3/hw3.py
> +
В аннотации не хватает ошибки

2023-12-20 19:17 UTC, nazaroviktor2 approved these changes
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/7cb2889d-0f6e-4e44-bca2-4cbaa6175e53)

2023-12-22 12:21 UTC, siriusdevs approved these changes

2023-12-22 12:21 UTC, merged