Telegin
siriusdevs/homeworks_23 pull request #98
Opened 2023-12-20 14:49 UTC by TeleginSergey

Добрый вечер. Искренне не понимаю, что делать с этими ошибками. Конечно, я мог бы просто в внести целую строку пути, однако тесты работали бы только на ОС Linux, да и, на самом деле, переписывать не хочется. Надеюсь на Вашу помощь!

2023-12-20 17:03 UTC, TeleginSergey commented
> > Конечно, я мог бы просто в внести целую строку пути, однако тесты работали бы только на ОС Linux, да и, на самом деле, переписывать не хочется.
> 
> Это ты про тесты?

Да, про тесты flake8.

2023-12-20 17:26 UTC, nazaroviktor2 requested changes
Молодец, есть небольшие замечания

2023-12-20 17:26 UTC, nazaroviktor2 commented on hw2/hw2.py
> +def check_path(input_path: str, output_path: str) -> tuple[str]:
tuple[str, str]

2023-12-20 17:26 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(output_path, 'w') as output_file:
если конечный путь не найден? 
См makedirs https://docs-python.ru/standart-library/modul-os-python/funktsija-makedirs-modulja-os/

2023-12-20 17:26 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        input_data = json.load(input_file)
Второй раз читаем один и тот же файл, может лучше передавать данные из файла?

2023-12-20 17:26 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        output_data['ages'][age] = round(percentage, 2)
ages - лучше вынести в константу

2023-12-20 17:26 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        output_data['regions'][region] = round(percentage, 2)
regions - тоже в константу

2023-12-20 21:33 UTC, TeleginSergey commented on hw2/hw2.py
> +    with open(output_path, 'w') as output_file:
> если конечный путь не найден? См makedirs https://docs-python.ru/standart-library/modul-os-python/funktsija-makedirs-modulja-os/

Немного не понял. Модуль автоматически создаст файл default_output.json на месте запуска программы (если нет файла вывода) и запишет туда выходные данные, при условии что с файлом источником все в порядке, иначе запишет строку, где описывается ошибка. Для чего мне метод makedirs()?

2023-12-21 16:52 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    if not os.path.exists(input_path):
Это проверка на наличие пути, если будет папка то exist тоже вернет true

2023-12-21 16:52 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    if not os.path.exists(output_path):
Тоже самое, если хочешь проверять, то надо именно на файл

2023-12-21 16:52 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(output_path, 'w') as output_file:
Так в чем проблема создать конечный путь? Именно для это тебе нужен makedirs

2023-12-21 19:21 UTC, TeleginSergey commented on hw2/hw2.py
> +    if not os.path.exists(input_path):
У меня сначала вызывается функция check_extensions, которая не пропустит ничего, кроме файл-источника с расширением '.json'

2023-12-21 20:40 UTC, nazaroviktor2 requested changes
Не поправил

2023-12-21 20:40 UTC, nazaroviktor2 commented on hw2/hw2.py
> +def check_path(input_path: str, output_path: str) -> tuple[str]:
Не поправил

2023-12-21 20:40 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        output_data['ages'][age] = round(percentage, 2)
Не поправил

2023-12-21 20:40 UTC, nazaroviktor2 commented on hw2/hw2.py
> +    with open(output_path, 'w') as output_file:
Не поправил

2023-12-21 20:40 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        output_data['ages'][age] = round(percentage, 2)
Не поправил

2023-12-21 20:40 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        output_data['regions'][region] = round(percentage, 2)
Не поправил

2023-12-21 20:40 UTC, nazaroviktor2 commented on hw2/hw2.py
> +        input_data = json.load(input_file)
Не поправил

2023-12-21 21:23 UTC, nazaroviktor2 submitted a review, later dismissed
1) Ключи не вынеси в константу, в дальнейшей разработке можно допустит ошибку в написании и получить различные эффекты
2) Очень много лишних проверок и псевдокода
![image](https://github.com/siriusdevs/homeworks_23/assets/45715124/892db62f-2055-4ad8-b81d-a1ebb83d920d)

2023-12-21 21:23 UTC, nazaroviktor2 commented on hw2/hw2.py
> +            os.makedirs(os.path.dirname(output_path))
Зачем передавать название папки? makedirs и файл создаст. И вообще не понятно зачем эти ты ифы нужны. Есть параметр exist_ok, который в значение True, ничего не сделает если файл уже найден

2023-12-21 21:28 UTC, TeleginSergey commented on hw2/hw2.py
> +            os.makedirs(os.path.dirname(output_path))
Спасибо, не досмотрел. Думал, что метод makedirs создает только папки и, например, при передаче файла, которому не надо создавать папки выдаст ошибку.

2023-12-21 21:34 UTC, TeleginSergey commented
Если есть время, нужна небольшая консультация по поводу тестов на hw3.py. Не понимаю как исправить flake8.

2023-12-21 21:35 UTC, nazaroviktor2 commented
> Если есть время, нужна небольшая консультация по поводу тестов на hw3.py. Не понимаю как исправить flake8.

@NazaroffV

2023-12-22 13:07 UTC, merged