Nekhoroshev_hw3
siriusdevs/homeworks_23 pull request #99
Opened 2023-12-20 17:45 UTC by fghh64

2023-12-20 19:26 UTC, nazaroviktor2 requested changes
Молодец. Много где не хватает аннотаций

2023-12-20 19:26 UTC, nazaroviktor2 commented on hw3.py
> +    def __init__(self, brand, model, year):
Аннотации?

2023-12-20 19:26 UTC, nazaroviktor2 commented on hw3.py
> +    def year(self, new_year):
Аннотации?

2023-12-20 19:26 UTC, nazaroviktor2 commented on hw3.py
> +    def car_park(self, new_car_park):
Аннотации?

2023-12-20 19:26 UTC, nazaroviktor2 commented on hw3.py
> +    def name(self, new_name):
Аннотации?

2023-12-20 19:26 UTC, nazaroviktor2 commented on hw3.py
> +    def cars(self, new_cars):
Аннотации?

2023-12-20 19:26 UTC, nazaroviktor2 commented on hw3.py
> +    def car_for_sale(self, new_car_for_sale):
Аннотации?

2023-12-20 19:26 UTC, nazaroviktor2 commented on hw3.py
> +    def owner(self, new_owner):
Аннотации?

2023-12-20 19:26 UTC, nazaroviktor2 commented on hw3.py
> +    def car_showroom(self, new_car_showroom):
Аннотации?

2023-12-20 19:26 UTC, nazaroviktor2 commented on hw3.py
> +class AbstractOwner:
Абстрактный владелец, но класс не абстрактный

2023-12-20 20:50 UTC, fghh64 commented on hw3.py
> +    def car_showroom(self, new_car_showroom):
что такое анотация

2023-12-21 01:06 UTC, fghh64 commented
исправил

2023-12-21 13:26 UTC, fghh64 commented
добрый день проверьте пожалуйста еще HW1

2023-12-21 17:01 UTC, nazaroviktor2 requested changes

2023-12-21 17:01 UTC, nazaroviktor2 commented on hw1.py
> +def get_salary_stats(limit: tuple = None, **kwargs: dict[str, dict[str, float]]):
Аннотация на return?

2023-12-21 17:01 UTC, nazaroviktor2 commented on .github/workflows/pylint.yml
> +      run: flake8 ${{ matrix.homework }}
Мне кажется это не работает. Верни как было

2023-12-21 17:01 UTC, nazaroviktor2 commented on .github/workflows/pylint.yml
> +      run: flake8 ${{ matrix.homework }}
Мне кажется это не работает. Верни как было

2023-12-21 17:01 UTC, nazaroviktor2 commented on .github/workflows/pylint.yml
> +      run: pytest ${{ matrix.homework }}
Тоже верни на .

2023-12-21 17:14 UTC, fghh64 commented on hw3.py
> +    def __init__(self, brand, model, year: int) -> None:
он у меня не работает я через гит проверяю

2023-12-21 17:18 UTC, fghh64 commented on .github/workflows/pylint.yml
> +      run: flake8 ${{ matrix.homework }}
это работает, потому что я это только сегодня дописал вчера без этого было

2023-12-21 17:20 UTC, fghh64 commented on .github/workflows/pylint.yml
> +      run: flake8 ${{ matrix.homework }}
альберт андреевич подтвердил

2023-12-21 17:20 UTC, fghh64 commented on .github/workflows/pylint.yml
> +      run: flake8 ${{ matrix.homework }}
это отдельные линкеры для дз

2023-12-21 17:35 UTC, fghh64 commented on hw3.py
> +    def __init__(self, brand, model, year: int) -> None:
а еще flake8 анотации не считает ошибкой так как это пишется как пояснение

2023-12-21 19:48 UTC, fghh64 commented
все 1 и 3 дз исправлены дай опрув пожалуйста

2023-12-21 20:34 UTC, nazaroviktor2 requested changes

2023-12-21 20:34 UTC, nazaroviktor2 commented on HW2/test_hw2.py
> +    }
Тестовые данные должны быть в файлах

2023-12-21 20:34 UTC, nazaroviktor2 commented on HW2/test_hw2.py
> +    os.remove('test_output.json')
Тоже самое

2023-12-21 20:34 UTC, nazaroviktor2 commented on HW2/test_hw2.py
> +    os.remove('test_output.json')
Не надо удалять. Надо проверять, что данные из входного файла совпадают с данными из выходного после обработки

2023-12-21 20:34 UTC, nazaroviktor2 commented on HW2/hw2.py
> +    with open(input_file, 'r') as f:
Если файл не найден?

2023-12-21 20:34 UTC, nazaroviktor2 commented on HW2/hw2.py
> +    age_categories = [0, 18, 25, 45, 60, float('inf')]
Это лучше в константу

2023-12-21 20:34 UTC, nazaroviktor2 commented on HW2/hw2.py
> +    last_online_counts = [0] * len(last_online_categories)
Тоже

2023-12-21 20:34 UTC, nazaroviktor2 commented on HW2/hw2.py
> +        age = data[client]['age']
Если нет данного ключа?

2023-12-21 20:34 UTC, nazaroviktor2 commented on HW2/hw2.py
> +        last_online = (datetime.now() - datetime.fromisoformat(data[client]['last_login'])).days
Если нет ключа? Он в не том формате?

2023-12-21 20:34 UTC, nazaroviktor2 commented on HW2/hw2.py
> +        json.dump(result, f)
Если конечный путь не найден, см makedirs

2023-12-21 20:35 UTC, nazaroviktor2 commented
При вызове основной функции пользователь не должен видеть traceback ошибок. Сообщение об ошибки или запись этого сообщения в файл - ок

2023-12-21 20:39 UTC, fghh64 commented
стой всмысле сделай мердж

2023-12-21 20:40 UTC, fghh64 commented
у нас завтра последний день а у меня нету мерджа и тиниген меня отправит далеко и надолго

2023-12-21 20:41 UTC, fghh64 commented
и тогда я ниодну дз не защищу

2023-12-21 20:42 UTC, fghh64 commented
я сейчас файлы удалю закрой мердж потом добалю обратно

2023-12-21 20:42 UTC, nazaroviktor2 commented
> стой всмысле сделай мердж

Какой мерж?

2023-12-21 20:48 UTC, fghh64 commented
все чекни сейчас нету 2 дз значит 1 и 3 прошли проверку

2023-12-21 20:48 UTC, fghh64 commented
ну я перепутал, нужно галочки получить

2023-12-21 20:54 UTC, nazaroviktor2 approved these changes

2023-12-21 20:58 UTC, fghh64 commented
спасибо огромное

2023-12-21 21:05 UTC, fghh64 commented
а можно еще пункт ready получить

2023-12-21 21:05 UTC, fghh64 commented
или что то еще надо сделать

2023-12-21 21:10 UTC, nazaroviktor2 commented
Если ты еще хочешь сдать вторую домашку. То ты должен у себя в репе сделать новую ветку, в нее добавить файлы второй домашки и создать мерж реквест в ту же ветку siriusdevs:nehoroshev

2023-12-21 21:11 UTC, fghh64 commented
ок

2023-12-22 14:02 UTC, closed without merging